### ISSUE TITLE
[Enhancement]: Highlights for e-books

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [advplyr/audiobookshelf#3534] opened 2024-10-18 17:00 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

An easy way to store highlights/notes on e-books makes it easier to export thoughts. What format of ebook would be best suited, I'm not sure, but hope epub is one of them.

### Why would this be helpful?

Being able to put highlights and notes for specific references allows a user to build up a knowledge base as well as export these to a different productivity/knowledge base app such as Obsidian/Logseq etc.

### Future Implementation (Screenshot)

Select text in e-book, right click → Highlight/Take Note → If highlight, just highlight and save snippet to a separate file with location
If Note selected, open up a text box for note and save it alongside highlight.

### Audiobookshelf Server Version

v2.15.0

**Comment by nichwall** [comment] 2024-10-18 17:14
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1558

**Closed** 2024-10-18 18:47 UTC
Labels: enhancement
