### ISSUE TITLE
[Enhancement]: Auto Delete listened podcast episodes

### ISSUE THREAD

**Issue by Drakon74** [advplyr/audiobookshelf#2439] opened 2023-12-22 11:39 UTC
Maybe i am just blind, but i cannot find a function that a podcast episode automatically gets removed when it was fully listened too.

Since my search in past issues also wasn't successfully, i open this as a feature request.

Perhaps this can even be tweaked as in, either delete immediately or after X days. My fear is just that an ongoing podcast generates more and more data over time and deleting files manually can be a bit tedious...

**Comment by nichwall** [comment] 2023-12-22 14:13
Duplicate of https://github.com/advplyr/audiobookshelf/issues/615

There is currently not a way to automatically delete podcast episodes that have been listened to from the server.

You can set a "max episodes to keep" for each individual podcast, so when downloading a new episode the oldest episode is deleted, regardless of listen state of that episode. You can access this setting on the Schedule tab for the podcast.

**Comment by advplyr** [comment] 2023-12-22 14:20
Duplicate of https://github.com/advplyr/audiobookshelf/issues/615

**Closed by advplyr** 2023-12-22 14:20 UTC
Labels: enhancement
