### ISSUE TITLE
[Enhancement]: Podcast folders / sorting / archiving

### ISSUE THREAD

**Issue by lhassell** [advplyr/audiobookshelf#1701] opened 2023-04-19 02:56 UTC
### Describe the feature/enhancement

The ability for users to easily sort podcasts into different folders/groups. Additionally, support for an "archive" tag where podcasts that have ended can be put aside without removing the subscription totally, but where they will not clutter up the feed.

**Comment by advplyr** [comment] 2023-04-29 22:02
What feed are they cluttering up?

**Comment by JJGerace** [comment] 2023-05-24 00:36
Just wanted to signal boost this suggestion, and generally request that there be more tools to organize podcasts.
 
My current use case is that there's some podcasts I listen to right away/every episode (call them group A), there's some where I listen occasionally/every few episodes (B), there's some finished ones I'm working my way through the backlog (C), and there's some finished ones that I want to save on my filesystem in case I ever want to return to them (D). 

In my previous podcast player I organized them with A on top of the list/grid, followed by B and C (group D I don't keep on my phone but do have them on my NAS). Convenient as I'm switching which episode to listen to multiple times a day and this organization reduces hunting for the right podcast.

Not being able to do so (there is no way to my knowledge to have a custom ordering of the podcasts) does mean the feed gets kinda cluttered in effect. The feed in this context would be the "Library" tab when viewing podcasts. Hope you'll consider adding this in a future release.

**Comment by advplyr** [comment] 2023-05-24 00:46
I think this is a duplicate of #1477 actually. Adding a concept of "filters" for podcast would handle this use-case.

**Comment by advplyr** [comment] 2023-05-24 00:46
Duplicate of #1477

**Closed by advplyr** 2023-05-24 00:46 UTC
Labels: enhancement

**Comment by JJGerace** [comment] 2023-05-24 01:07
> I think this is a duplicate of #1477 actually. Adding a concept of "filters" for podcast would handle this use-case.

At least insofar as I understand what that entry is asking for, it would only partially accomplish this. It seems to be much more focused on viewing the library by individual episodes, where this one, or at least what I hope this one is asking for, is more about rearranging podcast subscriptions.

Going back to my groups A-D example, it definitely would help filter out group D (which I am not actively listening to). However it wouldn't help me better organize groups A-C with A at the top of the subscriptions (or Library) page.

Not unlike the OP of that other thread, this is a feature that Pocketcasts currently has which is what I'm hoping to replace with ABS. Here's a screenshot of my subscription page currently, and then a second one after I've moved a podcast up (because, say, I started listening to it more often and it fits into group A instead of B now).

![Screenshot_20230523-205751](https://github.com/advplyr/audiobookshelf/assets/6724418/f65022dd-7df7-4c76-9091-4aecaca268c0)

![Screenshot_20230523-205757](https://github.com/advplyr/audiobookshelf/assets/6724418/5a8ac092-0ea0-406e-86b6-3321c10745bf)

**Comment by advplyr** [comment] 2023-05-24 20:06
Do you have an idea of what this would look like in Abs? I haven't checked out this app you mentioning yet. How are you re-organizing them? Would it suffice to just set a sort order in Abs for how it is displayed in the library that would be adjustable?

**Comment by JJGerace** [comment] 2023-05-24 20:27
Pocketcasts has it set up as a drag and drop sort of thing. You tap on the cover art of the podcast you want to move, then move it to a new spot and let go. And then the app inserts it at that spot. Not unlike rearranging app icons on the homescreen of iOS/Android.

For abs yeah I think you can just add an additional "custom" sort order, you could add an additional sort order called "Custom"  that enables custom rearrangement of the subscriptions. The rearrangement could be implemented with dragging and dropping the cover art like pocketcasts, or you could add an "index" variable that the user could edit manually for each subscription that determines the order.

**Comment by advplyr** [comment] 2023-05-24 20:42
I put that in a separate request #1792. Feel free to add additional notes/suggestions
