### ISSUE TITLE
[Enhancement]: Show length of local book on match tab.

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#2191] opened 2023-10-07 08:01 UTC
### Describe the feature/enhancement

1. When I try to match a book and encounter multiple versions or editions, I find myself having to exit to check the length of the copy I'm adding. Afterward, I return to the match screen. Indicating the local file's runtime, perhaps at the top right corner of the match tab, would be highly beneficial.

2. For potential matches, it would be useful to include seconds in the listed runtime. There are numerous instances where multiple versions differ by only 5-20 seconds.

Bonus.
When there are multiple hits for the same title, author, and narrator, it would be helpful to sort the potential matches based on the runtime length that is closest to the local file.

These suggestions aim to improve the likelihood of syncing chapter timings accurately.

<img width="1108" alt="Screenshot 2023-10-07 at 12 42 06 AM" src="https://github.com/advplyr/audiobookshelf/assets/7660824/c388d4d1-8ff8-4db7-9aba-a6944aa0b970">

**Comment by advplyr** [comment] 2023-10-07 12:25
Duplicate of #1803

**Closed by advplyr** 2023-10-07 12:25 UTC
Labels: enhancement
