### ISSUE TITLE
[Enhancement]: Bookmark Offline

### ISSUE THREAD

**Issue by Milor123** [advplyr/audiobookshelf#3429] opened 2024-09-16 15:25 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

The bookmark option available when the server is **turn off** and want save a note or bookmark myself.  

### Why would this be helpful?

When my docker is turn off in the night, Me and my parents try listening books but cant take bookmarks because it only works online

I think that should be inserted to the server when the server is online, as new bookmark

### Future Implementation (Screenshot)

As normal bookmark but works offline

### Audiobookshelf Server Version

v2.13.4

**Comment by nichwall** [comment] 2024-09-16 15:31
This is specific to the mobile apps.
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/163

**Closed** 2024-09-16 18:37 UTC
Labels: enhancement
