### ISSUE TITLE
[Enhancement]: Ignored folders in library

### ISSUE THREAD

**Issue by rage1337** [advplyr/audiobookshelf#2460] opened 2023-12-27 23:19 UTC
### Describe the feature/enhancement

Please add the possibility to exclude folders from library scan. This can be done via an option in the Web UI, a config file (like [Plex](https://support.plex.tv/articles/201381883-special-keyword-file-folder-exclusion/) for example), comparable to .gitignore, or any other way.

Reason: My folder structure is [libRoot]->[artist]->[album]. On the first node, next to artist, I got a working folder - "_" in my case. There I work on files, tag them etc. After they are done, I move the files one layer up and integrate them with the general structure.
ABS scans the files I'm currently working on. If I could prevent this, I could skip the removal of wrong and/or orphaned data.

**Comment by advplyr** [comment] 2023-12-27 23:23
Duplicate of #https://github.com/advplyr/audiobookshelf/issues/1641

**Closed by advplyr** 2023-12-27 23:23 UTC
Labels: enhancement
