### ISSUE TITLE
[Enhancement]: Separate library type for text (epub) books

### ISSUE THREAD

**Issue by dathbe** [advplyr/audiobookshelf#2474] opened 2024-01-02 19:39 UTC
### Describe the feature/enhancement

The current library type of “books” should be changed to “audiobooks” and a new “books” type should be created. The UI for the current library type doesn’t really work for text books (e.g., “Continue Listening” should be “Continue Reading”). I’d also propose that rectangle cover art should be standard for text books. There may be other things to tweak between the two.

**Comment by advplyr** [comment] 2024-01-02 19:48
This would remove the option for storing abooks and ebooks together. 

I prefer #2314 where we allow an ebook only setting similar to how we have an abook only setting. The alternative would be to have 3 library types, audiobook, ebook and book but that might be more confusing to people.

The "Continue Reading" shelf can still be supported even without a separate library type because we just check if the progress is from an ebook or abook. This was in a past version but I removed it temporarily until the database speed gets improved.

**Comment by dathbe** [comment] 2024-01-02 23:23
I defer to how you'd prefer to implement, but I was thinking that the abook type would still permit ebooks, it would just be "geared" toward abooks.  I presume I could select my library being a podcast and it would still let me play abooks with relatively little difficulty...there are just a few tweaks that make them display and act different.  All I'm suggesting is that there should be a way to specify the library is primarily ebooks instead of primarily abooks.  

More particularly, I'm not suggesting any changes to the way the server implements an abooks library--other than the proposed renaming, but you could easily keep the name "books" and add a new name "text books" or "e-books".  I don't really care what they library types are called as long as the documentation explains what each type does.  But I do think it would be useful to have a text books library type.  If that's accomplished through a toggle switch within the abooks type, so be it.  Though I could see a few other types down the line, including digital comics.

**Comment by advplyr** [comment] 2024-01-05 19:54
This will be a duplicate of #2314 for now but perhaps it is separated into a different media type. The problem is the data model would need to change to accommodate that whereas it wouldn't need to change if we did an e-book only setting.

**Comment by advplyr** [comment] 2024-01-05 19:54
Duplicate of #2314

**Closed by advplyr** 2024-01-05 19:54 UTC
Labels: enhancement
