### ISSUE TITLE
[Enhancement]: Socks5 Proxy support

### ISSUE THREAD

**Issue by spyhuntergenral** [advplyr/audiobookshelf#1567] opened 2023-02-28 22:09 UTC
### Describe the feature/enhancement

Adding sock5 or http/s proxy support in order to proxy connections to internet metadata sources.

**Comment by advplyr** [comment] 2023-03-16 21:48
Is this a duplicate of #1313 ?

**Closed** 2023-03-22 21:35 UTC
Labels: enhancement
