### ISSUE TITLE
[Enhancement]: Add Preview Button

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf#2585] opened 2024-02-05 20:55 UTC
### Describe the feature/enhancement

Add the ability to preview an audiobook before streaming or downloading.

- Set preview duration in settings (30, 60, or 90 seconds)
- Preview is taken from a random portion of the middle of the book.

Reasons:
- Gives the ability to hear an audio sample before downloading the file. Particularily useful in instances where streaming is disabled to reduce server load (a feature that deserves to be implemented, [see thread](https://github.com/advplyr/audiobookshelf/issues/2572)).
- Gives an audio sample from the middle of the book rather than starting at the beginning as it would if sampling the stream.

Thanks!

**Comment by advplyr** [comment] 2024-02-05 21:04
Duplicate of #1032

**Closed by advplyr** 2024-02-05 21:04 UTC
Labels: enhancement
