### ISSUE TITLE
[Bug]: Losing Library list page scroll position when deleting a book

### ISSUE THREAD

**Issue by reikrom** [advplyr/audiobookshelf#2453] opened 2023-12-27 11:08 UTC
### Describe the issue

Scroll position is being reset when a book is deleted in the Library list view.
Scroll position is persisted if a book is deleted from the book page, then navigated back to the library page list page using navigator history

### Steps to reproduce the issue

1. Scroll any distance in Library list view.
2. Delete a book

### Audiobookshelf version

v2.7.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-12-27 14:40
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1956

**Closed by advplyr** 2023-12-27 14:40 UTC
Labels: bug
