### ISSUE TITLE
[Enhancement]: Ease of use for Podcasts

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [advplyr/audiobookshelf#2074] opened 2023-09-10 09:55 UTC
### Describe the feature/enhancement

An important feature for podcasts is the ability to automatically add them to playlists.
A way to define new episodes for each podcast to be added to a specific playlist would be super helpful.
This way, news podcasts can automatically be added to a News playlist which the user can then access at their leisure.

Another enhancement would be to sort a podcast playlists - currently sorting is completely manual, but using this podcasts can be added in a custom order, be it A-Z, Z-A, released on date etc.

And finally, an option to delete episodes of a podcast after being played would ensure optimal server space usage. If a user wishes to keep an episode they've listened to, an option of "favourite" could make this possible.

I'm coming from AntennaPod, and I believe these features are what make it the go-to app for podcasts, when one is not self-hosting. I am currently in the process of moving to AudiobookShelf and see these features as essential to develop AudiobookShelf into the go-to podcast server for self-hosters.

**Comment by advplyr** [comment] 2023-09-10 12:37
I think you're talking about what we've been calling "filters". Since we already have the concept of a playlist it makes more sense to use a new term for this because it's dynamic.
These feature requests should cover what you are asking
https://github.com/advplyr/audiobookshelf/issues/1477
https://github.com/advplyr/audiobookshelf/issues/1757 (this should probably be combined with #1477)

**Comment by advplyr** [comment] 2023-09-10 12:37
Duplicate of #1477

**Closed by advplyr** 2023-09-10 12:37 UTC
Labels: enhancement
