### ISSUE TITLE
[Bug]: Some files become corrupt after embedding metadata

### ISSUE THREAD

**Issue by Dalarialus** [advplyr/audiobookshelf#1085] opened 2022-10-23 04:44 UTC
### Describe the issue

Two of my books (and only these two out of all of the ones I've tried) become corrupted when I attempt to embed metadata into the files.

```
2022-10-23 05:16:38 INFO [AudioMetadataManager] Successfully tagged audio file "/audiobooks/George R. R. Martin/2011 - A Dance With Dragons {Roy Dotrice}/A Dance With Dragons {Roy Dotrice}.m4b"
```

```
2022-10-23 05:22:04 INFO [PlaybackSessionManager] startSession: Closing open session "A Dance with Dragons" for user "dan"

2022-10-23 05:22:04 INFO [STREAM] START STREAM - Num Segments: 29336

2022-10-23 05:22:04 INFO [INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -i /metadata/streams/play_gnvaq3c4c0vii4z1lf/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/play_gnvaq3c4c0vii4z1lf/output-%d.ts /metadata/streams/play_gnvaq3c4c0vii4z1lf/final-output.m3u8

2022-10-23 05:22:04 INFO

2022-10-23 05:22:04 INFO [aac @ 0x154d50d828c0] channel element 2.3 is not allocated

2022-10-23 05:22:04 INFO [aac @ 0x154d4e8218c0] channel element 2.3 is not allocated

2022-10-23 05:22:05 INFO [PlaybackSessionManager] startSession: Closing open session "A Dance with Dragons" for user "dan"

2022-10-23 05:22:05 INFO Closing Stream play_gnvaq3c4c0vii4z1lf

2022-10-23 05:22:05 INFO

2022-10-23 05:22:05 INFO [FFMPEG] Transcode Killed

2022-10-23 05:22:05 WARN File path does not exist /metadata/streams/play_gnvaq3c4c0vii4z1lf/output-2.ts

2022-10-23 05:22:05 INFO Deleted session data /metadata/streams/play_gnvaq3c4c0vii4z1lf
```

### Steps to reproduce the issue

1. Add an m4b file to the library.
2. Edit metadata and match to audible.co.uk.
3. Embed the metadata into the file.
4. Attempt to play the file and see the errors in the included logs.

### Audiobookshelf version

v2.2.1

### How are you running audiobookshelf?

Docker

**Comment by listy-bit** [comment] 2022-12-31 02:07
Still happening on 2.2.11

**Comment by fidoriel** [comment] 2023-01-05 22:43
I am experiencing this with ALAC .m4a files

**Comment by listy-bit** [comment] 2023-02-03 02:04
I have no idea what Audiobookshelf or tone is doing to break the files, but I managed to fix them afterwards by using the command:

`ffmpeg -i [PATH TO FILE] -c copy [PATH TO NEW FILE]`. 

I don't know if this is relevant but it seems the thing that marks out these "breakable" files as different is that they report their codec as mp4a-40-2 instead of AAC-LC

**Comment by wieluk** [comment] 2023-04-09 16:23
Hey I am not sure if this is excactly the same but after embedding the metadata I get these log outputs and the files don't play.
On windows with Vlc media player they play normally.

```
2023-04-09 16:19:49

INFO

[PlaybackSessionManager] startSession: Closing open session "21 Lektionen für das 21. Jahrhundert" for user "root" (Device: Windows 10 / Firefox)

2023-04-09 16:19:49

INFO

[STREAM] START STREAM - Num Segments: 8415

2023-04-09 16:19:49

INFO

[INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -i /metadata/streams/play_dxsecv2zyrfnvmrohl/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/play_dxsecv2zyrfnvmrohl/output-%d.ts /metadata/streams/play_dxsecv2zyrfnvmrohl/final-output.m3u8

2023-04-09 16:19:49

INFO

2023-04-09 16:19:49

INFO

[aac @ 0x7fee32247a40] Number of bands (9) exceeds limit (8).

2023-04-09 16:19:49

INFO

[aac @ 0x7fee357be880] Number of bands (9) exceeds limit (8).

2023-04-09 16:19:51

INFO

[STREAM] play_dxsecv2zyrfnvmrohl notifying client that stream is ready

2023-04-09 16:19:51

INFO

[STREAM-CHECK] Check Files 790 of 8415 9.39% Furthest Segment: 789

2023-04-09 16:19:53

INFO

[STREAM-CHECK] Check Files 1594 of 8415 18.94% Furthest Segment: 1593

2023-04-09 16:19:55

INFO

[STREAM-CHECK] Check Files 2368 of 8415 28.14% Furthest Segment: 2367

2023-04-09 16:19:57

INFO

[STREAM-CHECK] Check Files 3097 of 8415 36.80% Furthest Segment: 3096

2023-04-09 16:19:59

INFO

[STREAM-CHECK] Check Files 3769 of 8415 44.79% Furthest Segment: 3768

2023-04-09 16:20:01

INFO

[STREAM-CHECK] Check Files 4379 of 8415 52.04% Furthest Segment: 4378

2023-04-09 16:20:03

INFO

[STREAM-CHECK] Check Files 4835 of 8415 57.46% Furthest Segment: 4834

2023-04-09 16:20:05

INFO

[STREAM-CHECK] Check Files 5196 of 8415 61.75% Furthest Segment: 5195

2023-04-09 16:20:07

INFO

[STREAM-CHECK] Check Files 5724 of 8415 68.02% Furthest Segment: 5723

2023-04-09 16:20:09

INFO

[STREAM-CHECK] Check Files 6131 of 8415 72.86% Furthest Segment: 6130

2023-04-09 16:20:11

INFO

[STREAM-CHECK] Check Files 6631 of 8415 78.80% Furthest Segment: 6630

2023-04-09 16:20:13

INFO

[STREAM-CHECK] Check Files 7110 of 8415 84.49% Furthest Segment: 7109

2023-04-09 16:20:15

INFO

[STREAM-CHECK] Check Files 7575 of 8415 90.02% Furthest Segment: 7574

2023-04-09 16:20:17

INFO

[STREAM-CHECK] Check Files 8043 of 8415 95.58% Furthest Segment: 8042

2023-04-09 16:20:18

INFO

2023-04-09 16:20:18

INFO

[FFMPEG] Transcoding ended
```


I tried fixing with ```ffmpeg -i [PATH TO FILE] -c copy [PATH TO NEW FILE]``` but this gives me only a new file that doen't play als not with VLC

**Comment by advplyr** [comment] 2023-04-09 16:34
If you can link to a sample audio file that has this issue that would be helpful

**Comment by wieluk** [comment] 2023-04-09 16:42
I am not sure how to send a sample.
I cut a 5min part out with ffmpeg but the problem is that this file is also silent with VLC.
I used this command:
```ffmpeg -i in.m4a -f segment -segment_time 300 -c copy out%03d.m4a```
https://ufile.io/a4fspqve

**Comment by advplyr** [comment] 2023-04-10 22:31
Can you do an `ffprobe -i in.m4a -show_streams` and post what the audio stream looks like

**Comment by advplyr** [comment] 2023-04-11 14:36
@sandreas do you notice anything with that audio file that could cause tone to corrupt the file? The tone in the current release is also not the latest so you may have fixed whatever bug this is.

**Comment by sandreas** [comment] 2023-04-11 15:59
> @sandreas do you notice anything with that audio file that could cause tone to corrupt the file? The tone in the current release is also not the latest so you may have fixed whatever bug this is.

@advplyr Unfortunately no, I don't see any issues. I would need the original audio file (or at least a short part of it) and the full command (`tone tag ...`) to reproduce the issue. Without this information it is a shot in the dark.

Latest `tone` is `0.1.5`, but there were no significant changes besides the working macOS arm64 release. I plan to upgrade `atldotnet` for the next release `0.1.6`, but atm I'm pretty busy, so this might take a while.

Let me know if I can help you with anything else, I'll try my best.

**Comment by wieluk** [comment] 2023-04-12 05:26
> @wieluk Is that the ffprobe output after the metadata is embedded?
> 
> If so, can you post the ffprobe of the audio file before using the embed metadata tool?

Yes it is. To be honest I did not backup the file like you should before embedding ... sorry

**Comment by wieluk** [comment] 2023-04-12 16:43
I think it is for every m4b file like this.

I did another one with backup this time.
original:
https://pastebin.com/6jpG33iD

embedded:
https://pastebin.com/VAbs365m

difference:
![Untitled](https://user-images.githubusercontent.com/46672054/231525458-98833b8b-669e-4115-a0a8-c0bbb7b43462.png)

**Comment by theS1LV3R** [comment] 2024-04-07 01:30
I just started experiencing this. Playback works fine before embedding, after embedding playback breaks completely. The files I've used are about a gigabyte large each, so might not be suitable for sharing, but I'll see if I can create some smaller working test files.

As for now the biggest details I can give are my server logs and the client logs:

<details>
<summary>Server logs</summary>
2024-04-07 01:10:02314 DEBUG  [PlaybackSessionManager] startSessionRequest for device Linux x86_64 / Firefox
2024-04-07 01:10:02314 DEBUG  [PlaybackSessionManager] "s1lv3r" starting direct play session for item "4d688038-2a1a-4923-8b68-68b77ee37d16" with id 32237775-77f9-44f0-9f34-105094c45036 (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:02557 DEBUG  [PlaybackSessionManager] startSessionRequest for device Linux x86_64 / Firefox
2024-04-07 01:10:02.558 INFO  [PlaybackSessionManager] startSession: Closing open session "Hunting Adeline" for user "s1lv3r" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:02.558 DEBUG [PlaybackSessionManager] closeSession "32237775-77f9-44f0-9f34-105094c45036"
2024-04-07 01:10:02.559 DEBUG [PlaybackSessionManager] Removed session "32237775-77f9-44f0-9f34-105094c45036"
2024-04-07 01:10:02.563 DEBUG [PlaybackSessionManager] "s1lv3r" starting stream session for item "4d688038-2a1a-4923-8b68-68b77ee37d16" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:02.577 INFO  [STREAM] START STREAM - Num Segments: 10449
2024-04-07 01:10:02.582 INFO  [INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -i /metadata/streams/5273cc01-16b8-40fa-bba2-55c718a425ff/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/5273cc01-16b8-40fa-bba2-55c718a425ff/output-%d.ts /metadata/streams/5273cc01-16b8-40fa-bba2-55c718a425ff/final-output.m3u8
2024-04-07 01:10:02.582 INFO
2024-04-07 01:10:02.824 INFO  [aac @ 0x7fa21475f8c0] Prediction is not allowed in AAC-LC.
2024-04-07 01:10:02.827 INFO  [aac @ 0x7fa20fafc880] Prediction is not allowed in AAC-LC.
2024-04-07 01:10:03.921 DEBUG [PlaybackSessionManager] startSessionRequest for device Linux x86_64 / Firefox
2024-04-07 01:10:03.921 INFO  [PlaybackSessionManager] startSession: Closing open session "Hunting Adeline" for user "s1lv3r" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:03.922 DEBUG [PlaybackSessionManager] closeSession "5273cc01-16b8-40fa-bba2-55c718a425ff"
2024-04-07 01:10:03.922 INFO  Closing Stream 5273cc01-16b8-40fa-bba2-55c718a425ff
2024-04-07 01:10:03.930 INFO
2024-04-07 01:10:03.931 INFO  [FFMPEG] Transcode Killed
2024-04-07 01:10:03.931 INFO  Deleted session data /metadata/streams/5273cc01-16b8-40fa-bba2-55c718a425ff
2024-04-07 01:10:03.932 DEBUG [PlaybackSessionManager] Stream closed for session "5273cc01-16b8-40fa-bba2-55c718a425ff" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:03.932 DEBUG [PlaybackSessionManager] Removed session "5273cc01-16b8-40fa-bba2-55c718a425ff"
2024-04-07 01:10:03.933 DEBUG [PlaybackSessionManager] "s1lv3r" starting stream session for item "4d688038-2a1a-4923-8b68-68b77ee37d16" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:03.950 INFO  [STREAM] START STREAM - Num Segments: 10449
2024-04-07 01:10:03.958 INFO  [INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -i /metadata/streams/5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0/output-%d.ts /metadata/streams/5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0/final-output.m3u8
2024-04-07 01:10:03.958 INFO
2024-04-07 01:10:04.583 INFO  [aac @ 0x7fc2bfd738c0] Prediction is not allowed in AAC-LC.
2024-04-07 01:10:04.584 INFO  [aac @ 0x7fc2bb110880] Prediction is not allowed in AAC-LC.
2024-04-07 01:10:05.330 DEBUG [PlaybackSessionManager] startSessionRequest for device Linux x86_64 / Firefox
2024-04-07 01:10:05.330 INFO  [PlaybackSessionManager] startSession: Closing open session "Hunting Adeline" for user "s1lv3r" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:05.330 DEBUG [PlaybackSessionManager] closeSession "5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0"
2024-04-07 01:10:05.331 INFO  Closing Stream 5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0
2024-04-07 01:10:05.339 INFO
2024-04-07 01:10:05.340 INFO  [FFMPEG] Transcode Killed
2024-04-07 01:10:05.343 INFO  Deleted session data /metadata/streams/5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0
2024-04-07 01:10:05.344 DEBUG [PlaybackSessionManager] Stream closed for session "5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0" (Device: Linux x86_64 / Firefox)
2024-04-07 01:10:05.344 DEBUG [PlaybackSessionManager] Removed session "5b1b2ba1-f7ba-44f3-8eb7-47223448f6e0"
</detail>

<detail>
<summary>Client logs</summary>
03:24:50.458 [PlayerHandler] Switching to local player
03:24:50.458 [PlayerHandler] Player state change LOADING
03:24:50.460 [LocalPlayer] Supported mime types 
Object { "audio/flac": "maybe", "audio/mpeg": "maybe", "audio/mp4": "maybe", "audio/ogg": "maybe", "audio/aac": "maybe", "audio/x-ms-wma": "", "audio/x-aiff": "", "audio/webm": "maybe" }
Array(6) [ "audio/flac", "audio/mpeg", "audio/mp4", "audio/ogg", "audio/aac", "audio/webm" ]
03:24:50.576 [PlayerHandler] Preparing Session 
Object { id: "242a2990-a86a-4039-9f4a-b07fef8c44aa", userId: "88127922-603f-489c-9f8b-6715dbb0d15e", libraryId: "f9d9d7b7-278b-4ee4-adff-9423df525add", libraryItemId: "4d688038-2a1a-4923-8b68-68b77ee37d16", bookId: "4bc0ff9d-658b-466f-bb9e-f7820dcc020c", episodeId: null, mediaType: "book", mediaMetadata: {…}, chapters: (44) […], displayTitle: "Hunting Adeline", … }
03:24:50.576 [LocalPlayer] Loading track src /api/items/4d688038-2a1a-4923-8b68-68b77ee37d16/file/642733?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODEyNzkyMi02MDNmLTQ4OWMtOWY4Yi02NzE1ZGJiMGQxNWUiLCJ1c2VybmFtZSI6InMxbHYzciIsImlhdCI6MTY5MTAyMTU3MH0.kkGtjANNi8hZBoFuB9cCOmc6TvdGBryvB0Mz3wZikek
03:24:50.577 Set media session metadata 
MediaMetadata { title: "Hunting Adeline", artist: "H. D. Carlton", album: "Cat and Mouse Duet #2", artwork: (1) […] }
03:24:50.739 Media resource https://audiobookshelf.transcodedcatgirls.com/api/items/4d688038-2a1a-4923-8b68-68b77ee37d16/file/642733?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODEyNzkyMi02MDNmLTQ4OWMtOWY4Yi02NzE1ZGJiMGQxNWUiLCJ1c2VybmFtZSI6InMxbHYzciIsImlhdCI6MTY5MTAyMTU3MH0.kkGtjANNi8hZBoFuB9cCOmc6TvdGBryvB0Mz3wZikek could not be decoded. 4d688038-2a1a-4923-8b68-68b77ee37d16
03:24:50.740 Player error 
error { target: audio#audio-player, isTrusted: true, srcElement: audio#audio-player, currentTarget: audio#audio-player
, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
03:24:50.741 [PlayerHandler] Audio player error switching to HLS stream
03:24:50.841 [PlayerHandler] Preparing Session 
Object { id: "070876a4-0b75-47df-ac13-6699d720ca49", userId: "88127922-603f-489c-9f8b-6715dbb0d15e", libraryId: "f9d9d7b7-278b-4ee4-adff-9423df525add", libraryItemId: "4d688038-2a1a-4923-8b68-68b77ee37d16", bookId: "4bc0ff9d-658b-466f-bb9e-f7820dcc020c", episodeId: null, mediaType: "book", mediaMetadata: {…}, chapters: (44) […], displayTitle: "Hunting Adeline", … }
03:24:50.847 Set media session metadata 
MediaMetadata { title: "Hunting Adeline", artist: "H. D. Carlton", album: "Cat and Mouse Duet #2", artwork: (1) […] }
03:24:51.804 [HLS] Manifest Parsed
03:24:52.196 [PlayerHandler] Player state change LOADED
03:24:52.204 [PlayerHandler] Player state change PLAYING
03:24:52.214 Media resource blob:https://audiobookshelf.transcodedcatgirls.com/4ba4600d-59c4-4a60-a4d5-714c7b642edb could not be decoded. 4d688038-2a1a-4923-8b68-68b77ee37d16
03:24:52.214 Player error 
error { target: audio#audio-player, isTrusted: true, srcElement: audio#audio-player, currentTarget: audio#audio-player
, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
03:24:52.216 [PlayerHandler] Audio player error switching to HLS stream
03:24:52.263 [HLS] Error mediaError bufferAppendError 
Object { type: "mediaError", parent: "main", details: "bufferAppendError", sourceBufferName: "audio", frag: {…}, part: null, chunkMeta: {…}, error: DOMException, err: DOMException, fatal: true, … }
03:24:52.335 [PlayerHandler] Preparing Session 
Object { id: "c2693fd3-5d85-4063-bc65-3d8dca9a1181", userId: "88127922-603f-489c-9f8b-6715dbb0d15e", libraryId: "f9d9d7b7-278b-4ee4-adff-9423df525add", libraryItemId: "4d688038-2a1a-4923-8b68-68b77ee37d16", bookId: "4bc0ff9d-658b-466f-bb9e-f7820dcc020c", episodeId: null, mediaType: "book", mediaMetadata: {…}, chapters: (44) […], displayTitle: "Hunting Adeline", … }
03:24:52.336 [HLS] Destroying HLS Instance
03:24:52.341 Set media session metadata 
MediaMetadata { title: "Hunting Adeline", artist: "H. D. Carlton", album: "Cat and Mouse Duet #2", artwork: (1) […] }
03:24:52.364 Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
03:24:53.474 [HLS] Manifest Parsed
03:24:54.175 [PlayerHandler] Player state change LOADED
03:24:54.187 [PlayerHandler] Player state change PLAYING
03:24:54.199 Media resource blob:https://audiobookshelf.transcodedcatgirls.com/83a57cf2-643d-4c62-97c7-25edd61a7b98 could not be decoded. 4d688038-2a1a-4923-8b68-68b77ee37d16
03:24:54.199 Player error
error { target: audio#audio-player, isTrusted: true, srcElement: audio#audio-player, currentTarget: audio#audio-player
, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
03:24:54.201 [PlayerHandler] Audio player error switching to HLS stream
03:24:54.326 [HLS] Error mediaError bufferAppendError 
Object { type: "mediaError", parent: "main", details: "bufferAppendError", sourceBufferName: "audio", frag: {…}, part: null, chunkMeta: {…}, error: DOMException, err: DOMException, fatal: true, … }
03:24:54.330 [PlayerHandler] Preparing Session 
Object { id: "3286fac4-b0ef-43f0-87b8-98727f715592", userId: "88127922-603f-489c-9f8b-6715dbb0d15e", libraryId: "f9d9d7b7-278b-4ee4-adff-9423df525add", libraryItemId: "4d688038-2a1a-4923-8b68-68b77ee37d16", bookId: "4bc0ff9d-658b-466f-bb9e-f7820dcc020c", episodeId: null, mediaType: "book", mediaMetadata: {…}, chapters: (44) […], displayTitle: "Hunting Adeline", … }
03:24:54.331 [HLS] Destroying HLS Instance
03:24:54.336 Set media session metadata 
MediaMetadata { title: "Hunting Adeline", artist: "H. D. Carlton", album: "Cat and Mouse Duet #2", artwork: (1) […] }
03:24:54.351 Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
03:24:55.309 [HLS] Manifest Parsed
03:24:55.616 [PlayerHandler] Player state change LOADED
03:24:55.622 [PlayerHandler] Player state change PLAYING
03:24:55.631 Media resource blob:https://audiobookshelf.transcodedcatgirls.com/46827b77-1602-41a1-9ff0-4dfc25753608 could not be decoded. 4d688038-2a1a-4923-8b68-68b77ee37d16
03:24:55.632 Player error
error { target: audio#audio-player, isTrusted: true, srcElement: audio#audio-player, currentTarget: audio#audio-player
, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
03:24:55.634 [PlayerHandler] Audio player error switching to HLS stream
03:24:55.681 [HLS] Error mediaError bufferAppendError 
Object { type: "mediaError", parent: "main", details: "bufferAppendError", sourceBufferName: "audio", frag: {…}, part: null, chunkMeta: {…}, error: DOMException, err: DOMException, fatal: true, … }
03:24:55.703 [PlayerHandler] Preparing Session 
Object { id: "98754a3e-f197-43bb-a824-471dcdad29db", userId: "88127922-603f-489c-9f8b-6715dbb0d15e", libraryId: "f9d9d7b7-278b-4ee4-adff-9423df525add", libraryItemId: "4d688038-2a1a-4923-8b68-68b77ee37d16", bookId: "4bc0ff9d-658b-466f-bb9e-f7820dcc020c", episodeId: null, mediaType: "book", mediaMetadata: {…}, chapters: (44) […], displayTitle: "Hunting Adeline", … }
03:24:55.704 [HLS] Destroying HLS Instance
03:24:55.714 Set media session metadata 
MediaMetadata { title: "Hunting Adeline", artist: "H. D. Carlton", album: "Cat and Mouse Duet #2", artwork: (1) […] }
03:24:55.728 Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.
03:24:57.337 [HLS] Manifest Parsed
03:24:57.569 [PlayerHandler] Close Player
03:24:57.569 [HLS] Destroying HLS Instance
</detail>

Weirdly enough this didn't use to happen, previously this has worked fine, though I am not able to tell exactly when it broke. I'm sure it was working after this issue was initially created though, as well as after the last person commented.

**Comment by sandreas** [comment] 2024-04-07 05:13
> I just started experienI just started experiencing this. cing this. 

I'm working on it. Release 0.1.6 is soon to come, however I did not fully reproduce the problem yet. It might be specific to arch (x64 vs x64-musl)

**Comment by sandreas** [comment] 2024-04-24 06:16
@theS1LV3R @advplyr @Dalarialus @listy-bit 
The new `tone 0.1.6` is out. Would you be able to recheck, if it works again? Otherwise I have to file an issue on `atldotnet`, the main audio metadata library used.

There already is a [tone issue](https://github.com/sandreas/tone/issues/59), that may be related.

**Comment by mttgl** [comment] 2024-05-23 18:04
Ran into this today on `2.9.0` in Docker with `.m4b` files 800MB and 1.5GB large using metadata sourced from Audible and quick embed. 

Playback works normally in-app, then after quick embed, progress bar buffers and restarts in loop.

**Closed** 2024-12-21 16:55 UTC
Labels: bug
