### ISSUE TITLE
[Enhancement]: Should we support ability to set default user type on auto register instead of hardcoded it?

### ISSUE THREAD

**Issue by vanviethieuanh** [advplyr/audiobookshelf#2759] opened 2024-03-17 18:28 UTC
### Describe the feature/enhancement

🌟 Hi! First, thank you all for creating this amazing repo, I appreciate it and have a good time using it!

# Issues
 
When I set up OIDC with `audiobookshelf`, it works well but my newly created user has a type `user`. I think I could change it on OIDC settings, but we do not seem to have it yet. After that, I found [in the code](https://github.com/advplyr/audiobookshelf/blob/master/server/models/User.js#L202) that we currently hardcoded the user type on the auto register as `user`.

# Enhancement

Could we create a configuration field with the OIDC configuration form that can change the default user type that was newly created by OIDC?

Thank you!

**Comment by nichwall** [comment] 2024-03-17 19:38
Currently the only types of account are `admin`, `user`, and `guest`. The difference between `user` and `guest` is that a guest can't change their password, but otherwise they're functionally the same.

**Comment by nichwall** [comment] 2024-03-17 19:38
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2523

**Comment by Sapd** [comment] 2024-03-17 21:21
With the planned feature in https://github.com/advplyr/audiobookshelf/issues/2523 which nichwall linked, it will be possible to change it from the idP side.

**Comment by advplyr** [comment] 2024-03-18 18:41
Duplicate of #2523

**Closed by advplyr** 2024-03-18 18:41 UTC
Labels: enhancement
