### ISSUE TITLE
[Bug]: iOS App Crashes after some time.

### ISSUE THREAD

**Issue by sarg3nt** [advplyr/audiobookshelf#2239] opened 2023-10-22 21:29 UTC
### Describe the issue

As of about a month ago the iOS app will start crashing or getting killed by iOS after a very short period of inactivity. i.e. if you pause playback for more then a few seconds the app is killed by the OS.  
This may have started when I installed iOS 17 Beta, but I'm not 100% sure.  I'm of course now on the release version and it's still happening.  

The fix is to completely uninstall the app and reinstall.  This fixes it for a few days to a week, then the behavior starts again.
I hadn't seen anything about this in the Github Issues or Sub Reddit so I thought it was maybe my old phone and a lack of memory issue (iPhone 10S max) but I just upgraded to a 15 Pro Max and it happened there almost immediately.  I've uninstalled and reinstalled the app and that has fixed it so far, but it's only been a couple days. 

I've tried other fixes, such as killing all apps and restarting the phone but it continues to illicit the same behavior until the app is uninstalled and reinstalled.  

### Steps to reproduce the issue

This is tough as it "Just starts to happen". 
I'm hoping that by posting this we can get some other iOS folks to chime in to see if they are or are not experiencing this issue.

### Audiobookshelf version

Server 2.4.4.  iOS 0.9.66 (23)

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2023-10-22 23:13
This has been reported several times in the app repo and on the Discord. For many people, reinstalling the app has fixed the issue, but no everyone. The specific cause hasn't been found yet.

Each of the issues seem to be the same which is where some of the confusion is coming from.

https://github.com/advplyr/audiobookshelf-app/issues/910
https://github.com/advplyr/audiobookshelf-app/issues/770
https://github.com/advplyr/audiobookshelf-app/issues/844

**Comment by sarg3nt** [comment] 2023-10-22 23:55
Oops, sorry @nichwall, I should have looked for a different repo for the app.  My bad.

**Comment by nichwall** [comment] 2023-10-23 01:22
No worries, it happens.

**Comment by advplyr** [comment] 2023-10-23 21:59
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/770

**Closed by advplyr** 2023-10-23 21:59 UTC
Labels: bug
