### ISSUE TITLE
[Enhancement]: Supplementary document tagging

### ISSUE THREAD

**Issue by darth3pio** [advplyr/audiobookshelf#1809] opened 2023-06-01 04:57 UTC
### Describe the feature/enhancement

[Audible: Doctor Who: The TV Episodes Collection](https://www.audible.com.au/pd/Doctor-Who-The-TV-Episodes-Collection-Audiobook/1529143489)

Using the above as an example,

As I am an individual who keeps eBooks alongside audiobooks I like the progress tracking that's available from the eBook alone, however in some instances there might be supplementary documents that might also be stored alongside from which it may be desired that progress tracking be disabled.

The downloadable PDF with the above example is largely made up of cast credits and set photos that are supplementary and it is these circumstances that it would be nice to have an option to toggle off progress tracking for selected files.

**Comment by advplyr** [comment] 2023-06-01 09:15
Duplicate of #1664

**Closed by advplyr** 2023-06-01 09:15 UTC
Labels: enhancement
