### ISSUE TITLE
[Enhancement]: View indivdual podcast episode covers

### ISSUE THREAD

**Issue by Bitwolfies** [advplyr/audiobookshelf#1771] opened 2023-05-12 00:41 UTC
### Describe the feature/enhancement

Some podcasts have custom covers per episode, it would be nice to have the option to download and view them for each episode as it plays.

**Comment by advplyr** [comment] 2023-05-12 23:03
Duplicate of #1573

**Closed by advplyr** 2023-05-12 23:03 UTC
Labels: enhancement
