### ISSUE TITLE
[Bug]: authors with two surnames are sorted improperly

### ISSUE THREAD

**Issue by random-human-being** [advplyr/audiobookshelf#3077] opened 2024-06-14 10:20 UTC
### What happened?

Currently, when sorting authors, the last word in the "authors" field is assumed to be the surname.

This is not always the case, especially in countries where people take both parents' surnames. For example, the author "Gabriel García Márquez" is currently erroneously sorted as "Márquez, Gabriel García". In fact, it should be sorted as "García Márquez, Gabriel".

### What did you expect to happen?

OPF files generated via Calibre already include an "author_sort" field, which could be scraped as-is. Not sure about other providers.

### Steps to reproduce the issue

Add any book written by an author with two surnames; sort books by "Author Last, First"

### Audiobookshelf version

v2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

**Comment by advplyr** [comment] 2024-06-17 21:26
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1409

**Closed by advplyr** 2024-06-17 21:26 UTC
Labels: bug
