### ISSUE TITLE
[Enhancement]: eBook Reading and Highlighting

### ISSUE THREAD

**Issue by CoryGH** [advplyr/audiobookshelf#3583] opened 2024-11-03 04:40 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be nice to have an eBook style reader/highlighter which does speech-to-text translation to build out an eBook from an audiobook as a background process and has time synchronization to text to highlight what is being said while displaying it.

### Why would this be helpful?

As an accessibility feature.

### Future Implementation (Screenshot)

Sort of like:
![tpvuoxaifcbc1](https://github.com/user-attachments/assets/71148ca9-4f6e-4270-bc85-4eaa5ca725a5)
but with highlighting over actively-read text, in the body of the playback area.

### Audiobookshelf Server Version

2.16.2

### Current Implementation (Screenshot)

The playback bottom bar when listening to an audiobook.

**Comment by nichwall** [comment] 2024-11-03 04:41
Duplicate of https://github.com/advplyr/audiobookshelf/issues/189

**Closed** 2024-11-03 04:44 UTC
Labels: enhancement
