### ISSUE TITLE
[Enhancement]: option to read the next / previous podcast when the currently playing podcast finished playing

### ISSUE THREAD

**Issue by silkyclouds** [advplyr/audiobookshelf#3456] opened 2024-09-25 08:18 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

We use to listen to a lot of podcasts at home, and audiobookshelf allowed us to move away from youtube, since google podcasts was discontinued. Thank you for this ! 

One little issue we do have is, especially for short capsules (2 minutes duration podcasts), we have to go back to the UI and press play again, and again, each time a podcast ends. 

The feature is simple, it is a checkbox to add, that enables the previous (or next) podcast to start playing automatically, at the end of the currently playing podcast. 

### Why would this be helpful?

This would allow anyone listening to podcasts to avoid having to go back to the GUI and press play again, when listening to "capsules" (short podcasts) 

### Future Implementation (Screenshot)

<img width="1362" alt="image" src="https://github.com/user-attachments/assets/18803305-49c8-4152-9b8f-decf70c8917a">
podcasts would then be played continuously in this order. 

Another way this could be implemented would be to automatically play the list from top to bottom, when the "genral" play button gets pressed. 

mono-playing would still be possible by clicking the play button of a single episode

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/132e4c29-7efc-4243-b7e8-c5cc0640688f">

### Audiobookshelf Server Version

2.13.4

### Current Implementation (Screenshot)

no existing feature for now as far as I know

**Comment by advplyr** [comment] 2024-09-27 22:07
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1321

**Closed by advplyr** 2024-09-27 22:07 UTC
Labels: enhancement

**Comment by silkyclouds** [comment] 2024-09-29 06:57
> Duplicate of #1321

Can you eventually let me know if the problem is localted on my end (podcasts are not playing the previous episode at all on my end (ios / webui) and I have to click play every two minutes). ? 

Is issue #1321 worked on ? 

Thanks !

**Comment by cameronj86** [comment] 2024-10-31 04:28
I think that everyone experiences the same issue? I know I do. I am not quite sure I understand the reason for playlists as a result but c'est la vie.
