### ISSUE TITLE
[Enhancement]: Allow purging of zero-book authors in a library

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2846] opened 2024-04-12 23:20 UTC
### Describe the feature/enhancement

Because of either bad MP3 tag information (narrators in the field expected for authors and vice verssa) as well as creating and moving books to new libraries (e.g. Moving a selection of books from "Fiction" to newly created "Science Fiction & Fantasy"), I have a bunch of authors with zero books attached to them Here is an example from my Fiction library:

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/b32348d5-dbab-4a23-b45c-1cb721854fea)

Right now, I have to delete each "zero book" author individually, but it would be nice to do a bulk delete.

**Comment by nichwall** [comment] 2024-04-12 23:24
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2466

**Comment by advplyr** [comment] 2024-04-13 16:47
Duplicate of #2466

**Closed by advplyr** 2024-04-13 16:47 UTC
Labels: enhancement
