### ISSUE TITLE
[Bug]: Stats do not accurately reflect iOS listening sessions of downloaded books 

### ISSUE THREAD

**Issue by gregory0906** [advplyr/audiobookshelf#2718] opened 2024-03-07 15:32 UTC
### Describe the issue

Stats do not accurately reflect iOS listening sessions of downloaded books. When I exclusively streamed, it seemed to work well, but even then, did always report way day behind (i.e., if I listen on Monday, that appears to be reported as Tuesday's listening). However, once I started to download the files to my iOS, it all got wonky, and started only reporting listening sessions in large bursts. 99% of my listening is on iOS.

<img width="394" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/48144055/4c797861-b2e5-4810-9441-7611a8cabc9f">

I know that I am only 1 of many huge Tolkien fans using ABS, but even I did not listen to 33 hours of Fellowship in one sitting during one day. I listened to it across Jan and Feb, but those days report no listening sessions:
<img width="451" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/48144055/e58ecf73-f051-4aae-9585-6ac76b4c4920">

This seems to happen for downloaded books to ios, that only report a session once marked complete:
<img width="868" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/48144055/1ca5d777-4634-4e5d-8a09-6a87ccb09779">

Above, those hours got report as a single session once I had concluded the book and marked it complete. However, if I listen from the web browser, it reports no problem, I just listened as a test for this issue report a moment ago via the browser, and sure enough it adds a new session:
<img width="383" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/48144055/381a3e7c-0e27-4fff-a227-f031018f56d1">
This isn't mission critical stuff, but the stats are fun to track, and I was proud of my Days in a row, and lost my record even though I was actually listening.

### Steps to reproduce the issue

1. Stream a book from iOS
2. at some point thereafter, download the book locally
3. continue listening
4. finish the book, and mark as complete

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2024-03-07 15:38
Is this a duplicate of #2548?

The long listening sessions is a known issue. I'm not sure if you are pointing out something specific to downloaded books. Can you reproduce this in a few steps right now or is this something that you notice later on and can't reproduce it consistently?

**Comment by gregory0906** [comment] 2024-03-07 15:57
> Is this a duplicate of #2548?
> 
> The long listening sessions is a known issue. I'm not sure if you are pointing out something specific to downloaded books. Can you reproduce this in a few steps right now or is this something that you notice later on and can't reproduce it consistently?

Yes. Sorry I missed that. This is something that I notice later other than as I listen I notice my Days in a row not keeping up. My experience indicates that it happens when I have it downloaded to iOS vs. streaming from iOS; however, even then, I am rarely offline am still able to sync with the server. I do apologize for the duplicate; thanks for all your hard work.

**Comment by advplyr** [comment] 2024-03-07 15:58
Duplicate of #2548

**Closed by advplyr** 2024-03-07 15:58 UTC
Labels: bug
