### ISSUE TITLE
[Bug]: Duplicate Pod Cast Episodes in UI

### ISSUE THREAD

**Issue by davidmgrantham** [advplyr/audiobookshelf#2122] opened 2023-09-19 13:08 UTC
### Describe the issue

Duplicate podcast episodes show in Web UI and beta IOS app.

From syslog

Sep 19 07:45:21 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:21] INFO: [PodcastManager] Successfully downloaded podcast episode "***Special Guest Episode on Roman Slavery and Gladiators w/Fiona Radford***"
Sep 19 07:45:27 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:27] INFO: [LibraryItem] Library item "bb76e457-1d54-4543-ad0b-5181edbda0da" updated
Sep 19 07:45:27 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:27] INFO: [PodcastManager] Successfully downloaded podcast episode "080 Hekate and Magic"
Sep 19 07:45:37 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:37] INFO: [LibraryItem] Library item "bb76e457-1d54-4543-ad0b-5181edbda0da" updated
Sep 19 07:45:37 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:37] INFO: [PodcastManager] Successfully downloaded podcast episode "079 Old Age, Death, and Burial"
Sep 19 07:45:43 BookSVR audiobookshelf[214647]: [2023-09-19 07:45:43] INFO: [LibraryItem] Library item "bb76e457-1d54-4543-ad0b-5181edbda0da" updated

Episodes 080 shows twice with the exact same metadata in WebUI. This is just one example of many across all podcasts. 

<img width="339" alt="dups" src="https://github.com/advplyr/audiobookshelf/assets/7535078/0916673c-1319-4dc7-b450-b769be64af82">

### Steps to reproduce the issue

1. Add new Podcast in search feature
2. Edit podcast
3. Select Episodes
4. Select date older than podcast start
5. Select unlimited episodes
6. Allow audiobookshelf to download all known episodes

### Audiobookshelf version

2.4.3

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment] 2023-09-21 20:19
I think we discussed this in discord the other day. This isn't reproducible every time but I have seen this.

The workaround until this is fixed is to disable the watcher for the podcast library.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/9b803f3e-0549-4059-b1ab-9a2c10456c1a)

**Comment by KrzaQ** [comment] 2023-09-27 11:59
Can we somehow remove duplicates from already downloaded podcasts? I don't fancy re-downloading some with over 1000 episodes.

**Comment by advplyr** [comment] 2023-09-30 22:01
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)

**Closed by advplyr** 2023-09-30 22:01 UTC
Labels: bug, awaiting release

**Comment by advplyr** [comment] 2023-09-30 22:04
Unfortunately to remove duplicates you will have to do it manually.
You can tell which one is the duplicate by pressing edit on the episode. It won't have a linked audio file from an RSS feed
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/03f92f2a-c9d0-46c3-9e78-f8f4fef56491)

Then when you delete that episode make sure you don't enable "Hard Delete" because you don't want to delete the actual audio file.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/052d2a9e-51a1-409b-b5dc-868a895f680a)

If you are familiar with sqlite you could spin your server down and delete those from the `podcastEpisodes` table

**Comment by advplyr** [comment] 2023-09-30 22:05
The fix I made is to stop duplicates from being created when downloading new episodes

**Comment by seitzbg** [comment] 2023-10-02 04:17
FYI the dupes are on disk too :(

```
-rw-r--r--  1 containers containers 211373692 Oct  2 04:16 POD 67 -  Ketamine telemedicine with Dylan Beynon (5999c78d-92da-4a60-aa30-3715664665a8).mp3
-rw-r--r--  1 containers containers 211373692 Aug 27 08:29 POD 67 -  Ketamine telemedicine with Dylan Beynon.mp3
-rw-r--r--  1 containers containers 160559252 Oct  2 04:16 POD 69 -  The Alchemist with Dr. Tarik Peterson (d81fa165-da75-4747-a3d2-530eab1f1f1f).mp3
-rw-r--r--  1 containers containers 160559252 Aug 27 08:28 POD 69 -  The Alchemist with Dr. Tarik Peterson.mp3
```
