### ISSUE TITLE
[Enhancement] Alternate auto rewind behavior

### ISSUE THREAD

**Issue by gauravsuman007** [advplyr/audiobookshelf#1026] opened 2022-10-01 21:53 UTC
I'm coming from another android app (Smart Audiobook Player) and I really like their implementation of the "Auto rewind" feature. They rewind a few seconds (2s, I believe) when I pause playback briefly but rewind for a longer time (5s) when I pause the playback for a little longer.

In the current implementation of the audiobookshelf, the auto-rewind kicks in only when the playback has been paused for a some minimum duration. For me, it's much more useful to have the 2s auto-rewind if I pause the playback even for a few seconds as it reminds me of the sentence I was listening to.

**Comment by advplyr** [comment] 2022-10-01 22:31
Are you referring to the mobile application or the web client?

**Comment by advplyr** [comment] 2022-10-01 22:34
This is a duplicate of https://github.com/advplyr/audiobookshelf-app/issues/205 since I think you are referring to the mobile app. The mobile app has a different repo for issues.

**Closed by advplyr** 2022-10-01 22:34 UTC

**Comment by gauravsuman007** [comment] 2022-10-01 23:26
It's for the Android app, I will look into the other repo you pointed to
