### ISSUE TITLE
[Enhancement]: Make the fast-forward and rewind button times customizable.

### ISSUE THREAD

**Issue by boomschtick** [advplyr/audiobookshelf#1969] opened 2023-07-26 18:10 UTC
### Describe the feature/enhancement

I'd like to be able to set the fast-forward number of seconds to greater than 10 (usually 30.)  I'm good with a rewind of 10, but someone else might like to customize that as well.  My podcatching app does this and I find it's quite useful.

The setting should be reflected on the mobile apps.

**Comment by nichwall** [comment] 2023-07-26 18:15
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1722

**Comment by nichwall** [comment] 2023-07-26 18:21
The hard part is knowing exactly how someone else would have worded what you want. You can react to that other issue to help show you'd like that feature (instead of bumping it)

**Comment by advplyr** [comment] 2023-07-26 18:43
Duplicate of #1722

**Closed by advplyr** 2023-07-26 18:43 UTC
Labels: enhancement
