### ISSUE TITLE
[Enhancement]: allow -c:a copy as advanced option?

### ISSUE THREAD

**Issue by mayli** [advplyr/audiobookshelf#1818] opened 2023-06-04 05:57 UTC
### Describe the feature/enhancement

Most my audiobooks are encoded properly and I don't like to re-encode them, can we add an option to allow `-c:a copy`?

https://github.com/advplyr/audiobookshelf/blob/8243da69f69b2e4a65aa29acbee1898a89fbff62/server/managers/AbMergeManager.js#L70

**Comment by advplyr** [comment] 2023-06-04 13:34
You could use copy here
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/d9534ece-0bb9-4d50-92eb-40da179e28d8)

Although I'm not sure how ffmpeg will behave if the bitrate and channels are different. I have tested this using copy.

I'm not sure how common mp3 codec is in m4b files

**Comment by mayli** [comment] 2023-06-04 22:39
Maybe we could have some UI improvement with a copy checkbox and disable other options.

**Comment by advplyr** [comment] 2024-05-03 14:57
I'm merging this with https://github.com/advplyr/audiobookshelf/issues/1257

**Comment by advplyr** [comment] 2024-05-03 14:57
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1257

**Closed by advplyr** 2024-05-03 14:57 UTC
Labels: enhancement

**Comment by devnoname120** [comment] 2024-09-16 21:27
I was wondering why converting my AAX files to a M4B audiobook with audiobookshelf would destroy the quality. A combination of reading the source code,`git blame`, and some clicking around led me to this issue. I agree that it would be nice if discoverability of this “feature” was improved.
