### ISSUE TITLE
[Enhancement]: Custom covers for Series and Collections

### ISSUE THREAD

**Issue by SAS-1** [advplyr/audiobookshelf#2627] opened 2024-02-19 12:46 UTC
### Describe the feature/enhancement

Currently both Series and Collections use auto generated covers based on the books included in those options for the covers.
I would like to see an enhancement to this to allow users to add custom covers to both options I think this would give more control to users and maybe speed the loading up as it doesn't have to create covers by merging multiple ones as it does now.

**Comment by nichwall** [comment] 2024-02-19 14:30
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2589

**Comment by advplyr** [comment] 2024-02-20 13:59
Duplicate of #2589

**Closed by advplyr** 2024-02-20 13:59 UTC
Labels: enhancement
