### ISSUE TITLE
[Enhancement]: Android Automotive OS (AAOS) app

### ISSUE THREAD

**Issue by JFPCreations** [advplyr/audiobookshelf#3617] opened 2024-11-16 16:26 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

AudioBookShelf app for Android Automotive OS.

https://developers.google.com/cars/design/automotive-os

### Why would this be helpful?

Since some new cars, like mine, are shipped with Google Android Automotive OS (AAOS) and no Android Auto, it could be nice to have an Audiobookshelf app for it.

### Future Implementation (Screenshot)

AudioBookShelf app for Android Automotive OS.

### Audiobookshelf Server Version

2.16.2

**Comment by nichwall** [comment] 2024-11-16 16:32
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/621

**Comment by JFPCreations** [comment] 2024-11-16 16:34
> Duplicate of [advplyr/audiobookshelf-app#621](https://github.com/advplyr/audiobookshelf-app/issues/621)

Sorry, I did a research and it found nothing. Thank you.

**Closed** 2024-11-16 21:32 UTC
Labels: enhancement
