### ISSUE TITLE
[Enhancement]: Automatically create Bookmarks

### ISSUE THREAD

**Issue by user2223** [advplyr/audiobookshelf#1720] opened 2023-04-25 09:10 UTC
### Describe the feature/enhancement

I would be great if Audiobookshelf automatically created certain bookmarks. 
Sometimes a single missclick causes me to lose the position in my audiobook, some audiobook apps (for example Bookplayer https://github.com/TortugaPower/BookPlayer) create bookmarks in certain situations to prevent this from happening.

These bookmarks should overwrite themselves to prevent cluttering the bookmark list, each event should always have one bookmark created until the same event happens again and the bookmark gets overwritten.

This would be my proposed events for automated bookmark creation(1. and 3. are probably the most useful):

1. Starting playback
2. Stopping playback
3. Changing playback position by more than x Minutes.
4. jumping to the next chapter/changing chapter

**Comment by Dr-Blank** [comment] 2023-04-27 07:00
This has already been implemented in the history section for the app in the 3-dot menu, I think the ui is missing in the web version.

**Comment by user2223** [comment] 2023-04-27 09:36
I apologize, but I have been unable to locate what you are describing on either the iOS App or the Webview.

**Comment by Dr-Blank** [comment] 2023-04-27 20:38
you are correct, it's only present in the Android app for now.

**Comment by advplyr** [comment] 2023-04-29 21:36
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/466

**Closed by advplyr** 2023-04-29 21:36 UTC
Labels: enhancement
