### ISSUE TITLE
[Enhancement]: Collapse Collections 

### ISSUE THREAD

**Issue by VinylscratchOP** [advplyr/audiobookshelf#2383] opened 2023-12-04 06:18 UTC
### Describe the feature/enhancement

checkmark box in the library section in the same way the "collapse series" button works, it would be useful for me sorting my new library so that only the unsorted things are visible in the library when the collections and series are collapsed.

**Comment by nichwall** [comment] 2023-12-04 13:51
Hm. Although, looking at the data model filtering by "not in a collection" will be a difficult filter to add. In the meantime, you could add series to a placeholder series (maybe named "In Collection") whenever you add it to a Collection, use the "Missing Series" filter, and then when you're done remove the books from the placeholder series.

**Comment by nichwall** [comment] 2023-12-09 21:15
Didn't realize that there is already a "Missing Collection" feature request https://github.com/advplyr/audiobookshelf/issues/599

**Comment by advplyr** [comment] 2023-12-09 21:45
Duplicate of #599

**Closed by advplyr** 2023-12-09 21:45 UTC
Labels: enhancement
