### ISSUE TITLE
[Bug]: New library scan crashes server

### ISSUE THREAD

**Issue by szethh** [advplyr/audiobookshelf#2750] opened 2024-03-15 22:16 UTC
### Describe the issue

This is on a fresh install of audiobookshelf.
I added a new library for ebooks. I pointed the folder to my calibre data location and started the first scan. This maxes out the ram and eventually the server becomes unresponsive and I have to reboot the VM.

At first I tried with 4GB of RAM, and it crashed. I gave it 8GB and it crashed again. This is with around ~150 ebooks, so nothing big (5.4GB in total).

I have seen similar issues where the culprit is ffprobe spawning without limit, but it seems it is not the case here. All the ram is taken up by the node process, only 1/2 instances of ffprobe are running.

### Steps to reproduce the issue

1. Install the latest docker audiobookshelf image
2. Add a book library, point to a folder with books
3. Start a scan

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2024-03-15 22:27
What are the file formats of the ebooks you are scanning in? If you check the scan log is there a place where it stops that we can see?

**Comment by szethh** [comment] 2024-03-15 22:32
These are the logs from the container:

```
audiobookshelf  | [2024-03-15 22:29:41.339] INFO: === Starting Server ===
audiobookshelf  | [2024-03-15 22:29:41.544] INFO: [Server] Init v2.8.0
audiobookshelf  | [2024-03-15 22:29:41.982] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-03-15 22:29:42.447] INFO: [Database] Db connection was successful
audiobookshelf  | [2024-03-15 22:29:43.673] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting, customMetadataProvider
audiobookshelf  | [2024-03-15 22:29:44.038] INFO: [LogManager] Init current daily log filename: 2024-03-15.txt
audiobookshelf  | [2024-03-15 22:29:44.168] INFO: [BackupManager] 0 Backups Found
audiobookshelf  | [2024-03-15 22:29:44.169] INFO: [BackupManager] Auto Backups are disabled
audiobookshelf  | [2024-03-15 22:29:44.358] INFO: [Watcher] Initializing watcher for "Books".
audiobookshelf  | Warning: connect.session() MemoryStore is not
audiobookshelf  | designed for a production environment, as it will leak
audiobookshelf  | memory, and will not scale past a single process.
audiobookshelf  | [2024-03-15 22:29:44.471] INFO: Listening on port :80
audiobookshelf  | [2024-03-15 22:29:45.247] INFO: [Watcher] "Books" Ready
audiobookshelf  | [2024-03-15 22:29:45.938] INFO: [SocketAuthority] Socket Connected Dnmu_xhTgeLU9OEFAAAB
audiobookshelf  | [2024-03-15 22:30:02.373] INFO: [SocketAuthority] Socket Dnmu_xhTgeLU9OEFAAAB disconnected from client "root" after 16435ms (Reason: transport close)
audiobookshelf  | [2024-03-15 22:30:03.637] INFO: [SocketAuthority] Socket Connected 243an9Uks3ISqBIRAAAD
audiobookshelf  | [2024-03-15 22:30:04.939] INFO: [LibraryScanner] Library metadata precedence changed since last scan. From [Unset] to [folderStructure,audioMetatags,nfoFile,txtFiles,opfFile,absMetadata]
audiobookshelf  | [2024-03-15 22:30:04.941] INFO: [LibraryScanner] Starting (forced) library scan 206d37a8-2505-43a9-a924-a28b3855abc2 for Books
audiobookshelf  | [
audiobookshelf  |   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
audiobookshelf  | ]
audiobookshelf  | [ 'falling back to ArrayBuffer instantiation' ]
audiobookshelf  | [
audiobookshelf  |   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
audiobookshelf  | ]
audiobookshelf  | [ 'falling back to ArrayBuffer instantiation' ]
...
```

That last part keeps repeating until I kill the process

**Comment by szethh** [comment] 2024-03-15 22:55
also, regarding the file formats:
```
szeth@kite:/mnt/storage/media/books/calibre$ find . -type f | awk -F. '{print $NF}' | sort | uniq -c
      7 DS_Store
      4 azw3
      3 cbr
     10 cbz
      2 db
      2 djvu
     93 epub
     82 jpg
      1 json
     39 mobi
      3 mp3
     82 opf
     28 pdf
```

The `.db` are calibre databases. The json is also for calibre. So it's mostly epub, mobi, pdf and azw3. The jpgs are covers, opf is calibre book metadata. Some comics too (cbr, cbz).

Is any of these formats known to cause issues?

**Comment by advplyr** [comment] 2024-03-15 23:28
I think the `cbr` comics are having issues right now I'm still investigating. Can you take those out for a test scan?

**Comment by szethh** [comment] 2024-03-16 00:06
yup that fixes it. both cbr and cbz seem to be causing issues.

one thing to note though, they do seem to be getting partially processed. If i start a scan with a cbr/cbz file present, it goes into the wasm error loop. if i then move the files out of the directory, this shows up in the logs:
```
audiobookshelf  | [
audiobookshelf  |   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
audiobookshelf  | ]
audiobookshelf  | [ 'falling back to ArrayBuffer instantiation' ]
audiobookshelf  | [2024-03-16 00:03:07.718] ERROR: [FileUtils] ReadTextFile error Error: ENOENT: no such file or directory, open '/storage/media/books/calibre/Tatsuki Fujimoto/Chainsaw Man 04 (83)/metadata.opf' (fileUtils.js:126)
audiobookshelf  | [2024-03-16 00:03:07.741] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 03" - marking as missing
audiobookshelf  | [2024-03-16 00:03:07.822] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 05" - marking as missing
audiobookshelf  | [2024-03-16 00:03:07.890] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 05" - marking as missing
audiobookshelf  | [2024-03-16 00:03:10.205] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 01" - marking as missing
audiobookshelf  | [2024-03-16 00:03:10.331] INFO: [LibraryItem] Library item "cb5d548e-4767-47e2-9957-e186275d4ce3" updated
audiobookshelf  | [2024-03-16 00:03:10.342] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 01" - marking as missing
audiobookshelf  | [2024-03-16 00:03:10.458] INFO: [LibraryItem] Library item "428b0783-4d28-48f0-9fa3-dc28cddb2d7e" updated
audiobookshelf  | [2024-03-16 00:03:10.463] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 02" - marking as missing
audiobookshelf  | [2024-03-16 00:03:10.980] INFO: [LibraryItem] Library item "1a54e417-dbcb-4a1b-9c6b-65da5c4376d6" updated
audiobookshelf  | [2024-03-16 00:03:10.987] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 02" - marking as missing
audiobookshelf  | [2024-03-16 00:03:11.145] INFO: [LibraryItem] Library item "7da281b9-de93-4c96-a113-6770eac6bbd8" updated
audiobookshelf  | [2024-03-16 00:03:11.159] INFO: [LibraryScanner] Scanning file update group and library item was deleted "Chainsaw Man 03" - marking as missing
audiobookshelf  | [2024-03-16 00:03:11.272] INFO: [LibraryItem] Library item "638fb745-307b-414c-8686-8cb2526d0bcd" updated
```

So they do seem to be somewhat processed. I do not know much about this project so no clue why this is 😅

**Comment by Maran123** [comment] 2024-03-20 10:40
I think i'm also encountering this issue with cbz files. It works if you have enough RAM and/or swap-space for the entire library of cbz files. Otherwise the memory fills up and the scan is slow/halted. 


![Audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/7037781/adfee3b6-7139-40f0-a5d1-02092194bd71)

**Comment by szethh** [comment] 2024-03-20 10:50
this seems unfeasible for moderately big libraries.

are all book files buffered in memory at once?? 😬

also, does this happen with audiobooks too? or just cbz?

**Comment by nichwall** [comment] 2024-03-20 13:28
It's only with some cbz and ebook files.

**Comment by Tsamsiyu1** [comment] 2024-03-20 19:07
i have the same problem. i just created a new Library and added about 40 cbz files. the first 20 where scanned but it took ages. after that it just crashes the server.

**Comment by maxcovergold** [comment] 2024-04-11 09:46
Tested adding comics for the first time and ran into this issue.  System froze then crashed.  Tried creating a small <1GB library and that completed, but noticed memory wasn't released on completion of successful scan.  ABS required restart to resolve.

I also see the below error, both when memory completely fills and crashes and when scaning a small library so no crash, but memory is not released:

'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'

On a separate note, I'm struggling with understanding how to structure comics so that they appear in a series.

**Comment by maxcovergold** [comment] 2024-04-23 17:05
Unfortunately fixing of error #2856 doesn't resolve this issue.  It possibly is stopping the application from crashing, but just makes my entire Synology grind to a halt indefinitely

**Comment by Codex966** [comment] 2024-06-11 16:45
Still running into this issue as well.  
I added a Comics library last week, primarily with pdf, cbr, and cbz files in it and once I got to about 20~ items any scan crashes the app, requiring a restart (running Docker on UnRaid).

I've tried removing new entries to back-track if there might be a corrupt cbz file causing it, but haven't pinpointed a specific file for it yet.
My ebook/audiobook library is about 2 years old and is up to about 600 items and has no problems. Still think it might be something with how ABS is trying to scan these cbz/cbr.

**Comment by pekempy** [comment] 2024-08-05 11:07
I also have this issue with .cbr files.

I've noticed that 64/75 of `The Sandman` have processed properly, but it's having issues with the same sets of files after I delete and re-create the library (issue 1, issues 10-19). I've confirmed those files are not corrupted and have no differences to the other issues.

Docker logs:
```
2024-08-05 12:04:13   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:13 ]
2024-08-05 12:04:13 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:16 [
2024-08-05 12:04:16   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:16 ]
2024-08-05 12:04:16 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:19 [
2024-08-05 12:04:19   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:19 ]
2024-08-05 12:04:19 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:22 [
2024-08-05 12:04:22   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:22 ]
2024-08-05 12:04:22 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:25 [
2024-08-05 12:04:25   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:25 ]
2024-08-05 12:04:26 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:29 [
2024-08-05 12:04:29   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:29 ]
2024-08-05 12:04:29 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:32 [
2024-08-05 12:04:32   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:32 ]
2024-08-05 12:04:32 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:33 [
2024-08-05 12:04:33   'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
2024-08-05 12:04:33 ]
2024-08-05 12:04:33 [ 'falling back to ArrayBuffer instantiation' ]
2024-08-05 12:04:22 [2024-08-05 11:04:22.352] INFO: [SocketAuthority] Socket Connected Z-sfFta0-vKtwBH6AAAF
2024-08-05 12:04:38 Config /config /metadata
2024-08-05 12:04:38 [2024-08-05 11:04:38.824] INFO: === Starting Server ===
2024-08-05 12:04:38 [2024-08-05 11:04:38.849] INFO: [Server] Init v2.11.0
2024-08-05 12:04:38 [2024-08-05 11:04:38.850] INFO: [Server] Node.js Version: v20.15.0
2024-08-05 12:04:38 [2024-08-05 11:04:38.879] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
2024-08-05 12:04:39 [2024-08-05 11:04:39.023] INFO: [Database] Db connection was successful
2024-08-05 12:04:39 [2024-08-05 11:04:39.417] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting, customMetadataProvider, mediaItemShare
2024-08-05 12:04:39 [2024-08-05 11:04:39.608] INFO: [LogManager] Init current daily log filename: 2024-08-05.txt
2024-08-05 12:04:39 [2024-08-05 11:04:39.659] INFO: [BackupManager] 0 Backups Found
2024-08-05 12:04:39 [2024-08-05 11:04:39.660] INFO: [BackupManager] Auto Backups are disabled
2024-08-05 12:04:39 [2024-08-05 11:04:39.712] INFO: [Watcher] Initializing watcher for "Audiobooks".
2024-08-05 12:04:39 [2024-08-05 11:04:39.714] INFO: [Watcher] Initializing watcher for "Books".
2024-08-05 12:04:39 [2024-08-05 11:04:39.716] INFO: [Watcher] Initializing watcher for "Comics".
2024-08-05 12:04:39 Warning: connect.session() MemoryStore is not
2024-08-05 12:04:39 designed for a production environment, as it will leak
2024-08-05 12:04:39 memory, and will not scale past a single process.
2024-08-05 12:04:39 [2024-08-05 11:04:39.731] INFO: Listening on port :80
2024-08-05 12:04:40 [2024-08-05 11:04:40.073] INFO: [SocketAuthority] Socket Connected FEaOXX0DjzYvdg4NAAAB
2024-08-05 12:04:40 [2024-08-05 11:04:40.871] INFO: [SocketAuthority] Socket Connected wTivDwz3iBNb_ylAAAAD
2024-08-05 12:04:42 [2024-08-05 11:04:42.006] INFO: [Watcher] "Audiobooks" Ready
2024-08-05 12:04:42 [2024-08-05 11:04:42.260] INFO: [Watcher] "Comics" Ready
2024-08-05 12:04:43 [2024-08-05 11:04:43.029] INFO: [Watcher] "Books" Ready
```

**Comment by pierrejo** [comment] 2024-08-06 09:29
Hi, i've the same issue. I'm on a raspberry pi with 4Gb of RAM. And i can't add my CBZ files. 

**Error :**
```bash
wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'
```

I've also try to limit my container with :

```yaml
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M" 
        reservations:
          cpus: "0.5"
          memory: "256M"
```


Still get the error .... 😒

**Comment by danielb2** [comment] 2024-08-07 01:41
I'm also having the same issues with cbr files:

```
'wasm streaming compile failed: TypeError: Failed to parse URL from /client/dist/libarchive/wasm-gen/libarchive.wasm'       
```

Init v2.12.1
Node.js Version: v20.16.0
Platform: linux
Arch: x64

**Comment by Atfynt** [comment] 2024-08-08 20:29
It looks like the issue is in libarchive.js preventing it from automatically closing the archive once it has been opened adding archive.close() wherever we have Archive.open() just before returning would prevent having everything in memory all at the same time. at the very least parseComicMetadata.js parse function and extractCoverImage. it probably also needs to be added wherever the comic reader is extracting files but I have not really looked into that.

**Comment by nichwall** [comment] 2024-08-20 05:17
> It looks like the issue is in libarchive.js preventing it from automatically closing the archive once it has been opened adding archive.close() wherever we have Archive.open() just before returning would prevent having everything in memory all at the same time. at the very least parseComicMetadata.js parse function and extractCoverImage. it probably also needs to be added wherever the comic reader is extracting files but I have not really looked into that.

Thanks for helping track that down. I attempted a fix here https://github.com/advplyr/audiobookshelf/pull/3312 for the server crashing during a scan if you want to help test it (I don't actually have any comic files and am testing with homemade CBR/CBZ).

**Comment by advplyr** [comment] 2024-11-22 23:26
Is this still an issue?

**Comment by danielb2** [comment] 2024-11-23 14:48
works for me 👍

another issue now that I can read it is that i can't zoom out to see all of it, but I have to scroll a lot

**Comment by danielb2** [comment] 2024-11-23 14:51
<img width="651" alt="Screenshot 2024-11-23 at 21 50 58" src="https://github.com/user-attachments/assets/155551bc-a47a-414f-8e65-54523fd6e8e1">

also seeing this for some

**Closed** 2024-12-21 17:19 UTC
Labels: bug, waiting

**Comment by maxcovergold** [comment] 2025-01-02 17:14
Just to confirm that the change has resolved the problem for me.  Thank you!
