### ISSUE TITLE
CarPlay for iOS app

### ISSUE THREAD

**Issue by tedstriker** [advplyr/audiobookshelf#2024] opened 2023-08-21 18:18 UTC
### Describe the feature/enhancement

It would be really nice, if the Audiobookshelf app would show up on the Apple CarPlay display just like Spotify.

**Comment by nichwall** [comment] 2023-08-21 18:54
https://github.com/advplyr/audiobookshelf-app/issues/475

**Comment by advplyr** [comment] 2023-08-21 21:24
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/475

**Closed by advplyr** 2023-08-21 21:24 UTC
Labels: enhancement
