### ISSUE TITLE
[Bug]: Comics and ebooks direct press not work in library

### ISSUE THREAD

**Issue by PoepieFloepie** [advplyr/audiobookshelf#812] opened 2022-07-06 11:27 UTC
### Describe the issue

if i go to library for comics or ebooks.
and i hover over the comic or ebook then there display a white book (when i press it nothing happens ,only if you go a little bit to the side (that white book going smaller) then it works.

this works within home /recent added
but not in library

both with comics and ebooks

### Steps to reproduce the issue

1. 

### Audiobookshelf version

Always the latest version

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-07-06 12:21
I have no idea what you are talking about. You prompted me to update the bug report form

![image](https://user-images.githubusercontent.com/67830747/177548886-fe32a9f9-b301-4612-92d2-30dd3310d1f8.png)

**Comment by PoepieFloepie** [comment] 2022-07-06 12:56
![Schermopname](https://user-images.githubusercontent.com/46219717/177554918-6f006a53-1df8-4673-b1e6-1de8cf488128.png)

library    --> press white book nothing happens

this works in recents in home

**Comment by skyzuma** [comment] 2022-07-06 13:17
if an ebook or comic not work, there is error in the logs ... if is an ebook, abs cant read the files inside (and need to be the extracted files from this ebook) ... i think its the same with comic ...

**Comment by skyzuma** [comment] 2022-07-06 13:28
ive tested an comic with comicinfo.xml and the comicpage inside the root of the *.cbz and abs can read this comic ... maybe abs cant read the comic if an folder is in the root and there are the pages?

**Comment by skyzuma** [comment] 2022-07-06 13:52
ive tested other cbz and there is an issue: all cbz can read in the webbrower chrome amd mobile BUT and cbz with 500 mb > mobile cant read >>> plz wait (maybe the file is too big?)

we need more log informations if an comic cant load or the time is very long ... idk the system behind the ebook / comic reader but there is only (error) loginformation for ebook

**Comment by skyzuma** [comment] 2022-07-06 14:00
bzw the ebook / comic reader need a fullscreen option :) and close this back navigation (only the x for close)

**Comment by skyzuma** [comment] 2022-07-06 21:13
comic > root / folder / pages = "Unable to extract pages"
comic > root / pages = ABS can read

**Comment by advplyr** [comment] 2022-07-14 00:46
I just checked and I did not make the comic reader support nested folders. Is this common?
I think it can be added but I'm curious if this is a common way to package comics and why it would be done that way?

**Comment by advplyr** [comment] 2022-07-14 12:49
I'll hold off on it then. Don't want to put a bunch of effort into getting something working for a few comics poorly formatted.

**Comment by skyzuma** [comment] 2022-07-14 14:40
i edit comics / manga with an folder inside  ... i think its an missconfiguration but idk ... i dont like folders inside these books ...

if anyone interessted how theres books can edited:

i use total commander:

one side > strg + page down > enter the book > enter the folder and copy the files to the other sides book root ... 

or

extract the book with 7-Zip to an folder > go into the folder >compress the files to a new book (windows: send to "zip-compressed folder" )

and if u need any additionl informations like comicinfo.xml use comicrack with the comicvine plugin

**Comment by advplyr** [comment] 2022-07-14 22:56
This is a duplicate of #811 actually because I believe it is for the same reason. The issue was broken down by the comment in that thread https://github.com/advplyr/audiobookshelf/issues/811#issuecomment-1182720394

**Closed by advplyr** 2022-07-14 22:56 UTC
Labels: bug
