### ISSUE TITLE
v2.12.0 broken on Arm64 (using docker)

### ISSUE THREAD

**Issue by Sanicle87** [advplyr/audiobookshelf#3238] opened 2024-08-05 12:06 UTC
### What happened?

Hosted on Arm64 (a raspberry pi in my case), it's not possible to connect to the server. I suspect this may be due to an incompatability with the new unicode for sqlite binary, but I'm not certain. I'm happy to follow any troubleshooting instructions to the best of my ability. I'm unsure how to produce logs, please be patient and explain how to, if they're required.

### What did you expect to happen?

On starting the docker container, it should be possible to connect to the server through webui or smartphone app.

### Steps to reproduce the issue

update audiobookshelf to 2.12.0 on an arm64 device

### Audiobookshelf version

2.12.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment] 2024-08-05 13:35
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3231

**Closed** 2024-08-05 13:56 UTC
Labels: bug
