### ISSUE TITLE
[Enhancement]: Plex SSO for User Accounts

### ISSUE THREAD

**Issue by nebb00** [advplyr/audiobookshelf#1214] opened 2022-11-25 06:50 UTC
### Describe the feature/enhancement

Not sure how much work is required here. But being able to allow AudiobookShelf to user Plex user accounts would save having duplicate accounts

**Comment by DDriggs00** [comment] 2022-11-26 00:47
Dupe of https://github.com/advplyr/audiobookshelf/issues/998

**Closed** 2022-12-18 21:24 UTC
Labels: enhancement
