### ISSUE TITLE
[Enhancement]: When manually matching a book, show thumbnail of existing cover similar to existing author, genre, etc.

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#1555] opened 2023-02-25 16:12 UTC
### Describe the feature/enhancement

When matching a book, it tells you what the existing author, genre, etc. contain, but doesn't tell you what the existing cover looks like. It would be nice to be able to compare.

Furthermore, showing the old and new resolution would be helpful in making that decision as well.

**Comment by advplyr** [comment] 2023-03-31 22:31
Duplicate of #1605

**Closed by advplyr** 2023-03-31 22:31 UTC
Labels: enhancement
