### ISSUE TITLE
[Enhancement]: Mark all episodes as listened to

### ISSUE THREAD

**Issue by muppie** [advplyr/audiobookshelf#766] opened 2022-06-22 15:09 UTC
### Describe the feature/enhancement

Hi,
I suggest adding the possibility to mark all episodes of a podcast show as listened to. Currently (as far as I can tell), I need to mark each individual episode as listened to. I can’t code, but would be happy to help out with something else

**Comment by advplyr** [comment] 2022-07-02 17:00
Duplicate of #626

**Closed by advplyr** 2022-07-02 17:00 UTC
Labels: enhancement
