### ISSUE TITLE
Add read count/lists

### ISSUE THREAD

**Issue by Jmanko16** [advplyr/audiobookshelf#1905] opened 2023-07-01 10:56 UTC
### Is your feature request related to a problem? Please describe.

new feature request

### Describe the solution you'd like

Since audiobookshelf has gotten so good with not just audiobooks but epub, can we have a way to track reading status and counts.  Currently an audiobook/book is marked unmarked, in progress, or finished.  It would be great if it recorded total number of "reads/listens" and gave the dates of "reads/listens." 

### Describe alternatives you've considered

I use separate book trackers for this but would like to have the read counts and dates in one place.

### Additional context

Used to use book tracker for tracking and metadata.  ABS does all the metadata and at least has a "read" status, so does everything but read count and dates.  There are several books that I routinely read every year or 2 and like to track this data.

**Comment by advplyr** [comment] 2023-07-15 14:16
I'm merging this one with #1653, feel free to add comments over there

**Comment by advplyr** [comment] 2023-07-15 14:16
Duplicate of #1653

**Closed by advplyr** 2023-07-15 14:16 UTC
Labels: enhancement
