### ISSUE TITLE
[Bug]: Fatal javascript OOM in GC during deserialization

### ISSUE THREAD

**Issue by searay345** [advplyr/audiobookshelf#1976] opened 2023-07-28 21:25 UTC
### Describe the issue

I am running AudioBookShelf on a RPi 4 with the latest OMV 6. I stopped AudioBookShelf to update to the latest version and now I can't get it running again. When I do Compose Up, it'll run for a moment then go back down. I have tried removing and pulling a new image but it'll just stop running after a moment. I was able to copy this from the logs before I lost them. 

`<--- Last few GCs --->

<--- JS stacktrace --->

#
# Fatal javascript OOM in GC during deserialization
#

<--- Last few GCs --->

<--- JS stacktrace --->

#
# Fatal javascript OOM in GC during deserialization
#

<--- Last few GCs --->

<--- JS stacktrace --->

#
# Fatal javascript OOM in GC during deserialization
#

END OF LINE`

### Steps to reproduce the issue

1. click Docker-Compose-Up inside OMV. 

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-07-28 23:04
Duplicate of #1938

**Comment by advplyr** [comment] 2023-07-28 23:04
You can use the `edge` image if you want until the next release. Or follow the workaround in that issue

**Closed by advplyr** 2023-07-28 23:04 UTC
Labels: bug
