### ISSUE TITLE
[Enhancement]: Associate hyperlinks with an audiobook

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2813] opened 2024-04-02 14:25 UTC
### Describe the feature/enhancement

It would be nice if I can include Hyperlinks within a books data so that I can bring up additional information about a book. Examples include:

- Hyperlinks mentioned in the book itself
- Publisher page (e.g. GraphicAudio)
- Hyperlinks to external organizations mentioned in a book
- Online study guides

As the usage can vary, it should be a separate table associated with the book with custimizable text fields and associated hyperlinks. It may be possible to have the hyperlink import the favorites icon.

**Comment by nichwall** [comment] 2024-04-02 14:32
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1820

**Comment by advplyr** [comment] 2024-04-02 14:32
Yeah I think it would be better to support #1820 then to add new inputs to manage that most users will never use.

**Comment by advplyr** [comment] 2024-04-02 14:33
Duplicate of #1820

**Closed by advplyr** 2024-04-02 14:33 UTC
Labels: enhancement
