### ISSUE TITLE
Can’t add podcasts from mobile

### ISSUE THREAD

**Issue by genebean** [advplyr/audiobookshelf#693] opened 2022-06-05 23:16 UTC
### Describe the issue

The series tab doesn’t chang to search on mobile like it does on desktop when changing to a podcast library. On the iOS app the third tab is just not there at all. 

Mobile web:

![221F9038-9BB3-458C-A440-C1FFBCFBBD04](https://user-images.githubusercontent.com/966789/172074624-720d8f01-158d-43fb-a2dc-fc70a5b6c4fc.png)

iOS app:

![56B486D6-028B-4F58-AC7A-997AE247C867](https://user-images.githubusercontent.com/966789/172074640-ceaadc9d-94a5-4624-9d1f-851ad61c2b94.png)

### Steps to reproduce the issue

1. Open Audiobookshelf in a phone’s browser
2. Select a podcast library 

This is also true on mobile app

### Audiobookshelf version

2.0.18 server, 0.9.47-beta iOS app

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-06-05 23:20
The mobile version of the toolbar on web is a bug. It needs to be updated to show Home/Library/Search

On the mobile app it is not a bug that search wouldn't show up there because podcasts are added on the server. It would be a feature request if you requested to be able to add podcasts onto your server from the mobile app.

**Comment by genebean** [comment] 2022-06-05 23:23
Gotcha. I’ll make the feature request shortly.

**Comment by advplyr** [comment] 2022-07-03 14:27
Fixed in [2.0.23](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.23)

**Closed by advplyr** 2022-07-03 14:27 UTC
Labels: bug
