### ISSUE TITLE
 [Enhancement]: Author - Pseudonym-Relation

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#1322] opened 2022-12-27 14:23 UTC
### Describe the feature/enhancement

Often authors use a pseudonym under which they publish other books.
It would be very helpful if you could map the relationship. This could avoid redundancies 
For example, as shown in the following print screen:
![image](https://user-images.githubusercontent.com/72630160/209680317-1ff59d30-6d56-482d-ab31-1b6e608fb13a.png)

**Comment by advplyr** [comment] 2022-12-27 14:26
Is this a duplicate of #908

**Closed** 2022-12-28 23:21 UTC
Labels: enhancement
