### ISSUE TITLE
[Bug]: Search results are too strict resulting in no results found.

### ISSUE THREAD

**Issue by KellicTiger** [advplyr/audiobookshelf#2987] opened 2024-05-18 17:09 UTC
### What happened?

Uncertain if this would be a "bug" or a feature request.  Also I did search issues for this and didn't see any other mentions.  So I HOPE that this isn't a duplicate like the last submission I did.  

I have the audio book Shōgun by James Clavell.  When doing a search from either the web interface or the Android client for shogun no results are found.
![image](https://github.com/advplyr/audiobookshelf/assets/42510565/f5d426dd-67d9-471f-870b-bcf4d327f6bb)

https://en.wikipedia.org/wiki/Ch%C5%8Donpu
The chōonpu (Japanese: 長音符, lit. "long sound symbol"), also known as chōonkigō (長音記号), onbiki (音引き), bōbiki (棒引き), or Katakana-Hiragana Prolonged Sound Mark by the Unicode Consortium, is a Japanese symbol that indicates a chōon, or a long vowel 

If you use the special character the results show. (Which I will be honest I have no idea how to get from either the Google Keyboard or my desktop character set, I had to copy and paste from an example on a webpage.)

![image](https://github.com/advplyr/audiobookshelf/assets/42510565/299d929f-f8e1-40c5-8be4-c71a99ae4028)

### What did you expect to happen?

The search should be a bit looser when it comes to results.  e.g.  
ā = a
ī = i
ū = u
ē = e
ō = o

### Steps to reproduce the issue

1. Add a title that has one of these special characters in the title.
2. Search on it without using special characters.  

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Other (list in "Additional Notes" box)

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

Environment:

Server:
QNAP TVS-H1288X
Package from https://www.myqnap.org repository run on the NAS, not in a container.

Client:
Fedora 39 -  Web interface Firefox v126
Android 14 (Samsung Fold4) - Audiobookshelf v0.9.73-beta

**Comment by nichwall** [comment] 2024-05-18 17:57
https://github.com/advplyr/audiobookshelf/issues/1401

Adding a fuzzy search should help with this. Part of the problem is that searches are done by converting to lowercase, but non-ASCII characters do not have a "to lowercase" in SQLite. (Mentioned in https://github.com/advplyr/audiobookshelf/issues/2187#issuecomment-1749685811 and https://github.com/advplyr/audiobookshelf/issues/2234)

**Comment by advplyr** [comment] 2024-05-18 19:23
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2678

**Closed by advplyr** 2024-05-18 19:23 UTC
Labels: bug
