### ISSUE TITLE
[Enhancement]: Add a home screen widget to the Android Version.

### ISSUE THREAD

**Issue by Buchhems** [advplyr/audiobookshelf#1407] opened 2023-01-15 19:00 UTC
### Describe the feature/enhancement

I like to be able to start abs directly from a widget on the home screen. Also Pause, play, ff, aso.
Right now I'm using ubiquity music widget (https://play.google.com/store/apps/details?id=com.jackthakar.musicwidget) as a substitute. But it's buggy and only works at 70% of times.

**Comment by advplyr** [comment] 2023-01-15 20:00
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/307

**Closed by advplyr** 2023-01-15 20:00 UTC
Labels: enhancement
