### ISSUE TITLE
[Bug]: Library name and the library order only temporarily saves 

### ISSUE THREAD

**Issue by JamesDean3** [advplyr/audiobookshelf#3079] opened 2024-06-15 23:31 UTC
### What happened?

After changing the library name and the order that the libraries show up, it will only reflect the change for a short time, then it resets back to what it was.

### What did you expect to happen?

For the library name and order they are shown to stick long term and across all users and platforms.

### Steps to reproduce the issue

1. Change the Name or the order that the libraries show up.
2. Watch them change, but then later see that they are back to what they were before, or use another user account or platform, and see that the change didn't stick 

### Audiobookshelf version

v2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by advplyr** [comment] 2024-06-17 21:22
I'm not able to reproduce this. Are you able to reproduce this every time?
Can you give more exact steps to reproduce the issue?

**Comment by JamesDean3** [comment] 2024-06-18 03:44
Oddly I am unable to get it to do it now, but the first time it happened there was a decent delay.

A couple days ago I changed it over a browser on my computer and everything seemed fine,  later went and used it in the app and saw that the changes weren't reflected on the app. I logged out and back in on the app and it still showed the old names. 

I then went on to my computer and checked on there, and for a couple minutes it showed everything correctly with the new names and order I placed them in, I moved a few files into the library folder and ran matches and then I noticed both the names and the order went back to what they were, this time it was on my browser.

So I then went and changed them again, a few minutes later it changed back again, so I changed them again and logged out and back in, when I got back it had the old names again, I tried this a few more times, along with changing users, no luck. 

When talking to my brother about it, he mentioned having this same problem (both using the same server), but he said it was a few weeks ago when he was trying. Which is why I figured it was worth posting as a bug.


Just now I changed them again and logged out and back in twice and everything seems to be working, I checked the app and it is fine on there, checked another user account on both the browser and my phone and the changes seem to be sticking, at least for now.

**Comment by JamesDean3** [comment] 2024-06-18 13:22
This morning when checking it again, everything reverted back to what they were before again. The two different library names that I changed and the order that they displayed all changed back to what they used to be.

**Comment by JamesDean3** [comment] 2024-06-18 16:56
I've changed the library names back to what I want them to be again, and fixed the order once again, then I restarted the docker container, I logged out and logged back in on both the app and web version of the client, and everything seems to be staying how I want for now...

**Comment by devnoname120** [comment] 2024-06-18 22:20
I have a similar issue where the settings of my library get unexpectedly reset on a frequent basis.
<img width="1239" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/2824100/a7a6f133-4d18-4ab7-a653-2b34ef7055ea">

I'm not sure yet what triggers it but it happens really frequently (at least multiple times per hour).

**Comment by advplyr** [comment] 2024-06-18 22:24
If you are able to look at the database after updating the setting and then again after it resets that would help a lot. It is the `libraries` table which also includes the settings.
I'm not sure if this is a cache issue or data is actually being reverted somehow.

**Comment by devnoname120** [comment] 2024-06-18 22:37
Will do next time it happens.

**Comment by advplyr** [comment] 2024-06-20 22:09
> I suspect the bug might be triggered when the `Schedule Automatic Library Scan` CRON happens

Thanks, this helped me track it down. The cron was using the same copy of the library object that was used when initializing it so when the cron job ran it would revert.
This is the same as #2894 but I don't think it is the same as #3060

**Comment by devnoname120** [comment] 2024-06-21 21:08
Great! I just tried commit 72c1407aa74b8d78cebb06a552c64d9eb19bc1ac and I confirm that it solves my issue — thanks a lot.

**Comment by advplyr** [comment] 2024-07-09 20:40
Fixed in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)

**Closed by advplyr** 2024-07-09 20:40 UTC
Labels: bug, awaiting release
