### ISSUE TITLE
[Enhancement]: Audible match in different languages (ex. german - audible.de)

### ISSUE THREAD

**Issue by Manantra** [advplyr/audiobookshelf#1017] opened 2022-09-27 16:56 UTC
### Describe the feature/enhancement

I cant match my audiobooks with audible, because they are german and not listed on us audible page.
Please add support for different audible pages and metadata. I need to match files from audible.de.

Edit:
The file I tried to find as an example: https://www.audible.de/pd/Die-drei-und-der-Super-Papagei-Hoerbuch/B0B1QKF361?action_code=ASSGB149080119000H&share_location=pdp&shareTest=TestShare

**Comment by advplyr** [comment] 2022-09-27 21:31
Duplicate of #731

**Closed by advplyr** 2022-09-27 21:31 UTC
Labels: enhancement
