### ISSUE TITLE
[Bug]: Empty entries in the library view

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1174] opened 2022-11-18 09:05 UTC
### Describe the issue

Since the update to version 2.2.4 I have empty entries in the library view (see picture). I have not changed anything in the library itself. A reread of the whole library did not help. The other views (Series, Home) are ok.

![Unbenannt](https://user-images.githubusercontent.com/40667862/202663030-4422feca-eef0-440f-a607-14213ecc25a6.jpg)

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.2.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-11-18 10:28
Duplicate of #1162

**Closed by advplyr** 2022-11-18 10:28 UTC
Labels: bug
