### ISSUE TITLE
[Enhancement]: Logging to show login attempts

### ISSUE THREAD

**Issue by talkingseedling** [advplyr/audiobookshelf#2994] opened 2024-05-20 16:00 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Currently there is no log output for successful or unsuccessful login attempts. Ideally they'd be present, and include timestamp, username, ip address, X-Forwarded-For.

### Why would this be helpful?

Use case is parsing logs in elastic/logstash/kibana/beats to generate notifications for login attempts.

### Future Implementation (Screenshot)

{timestamp} WARN: [AuthService] Failed login attempt for user {username} from ip address {ip address} (Reason: wrong password)

### Audiobookshelf Server Version

v2.9.0

### Current Implementation (Screenshot)

docker logs -f audiobookshelf

**Comment by advplyr** [comment] 2024-05-20 16:05
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2533

**Closed by advplyr** 2024-05-20 16:05 UTC
Labels: enhancement
