### ISSUE TITLE
[Enhancement]: Default Sorting, Remember Sorting Order for Podcasts

### ISSUE THREAD

**Issue by apoapostolov** [advplyr/audiobookshelf#2960] opened 2024-05-09 20:29 UTC
### Describe the feature/enhancement

Right now every podcast, when viewed, sorts by Time, Descending. I want to be able to set Time, Ascending so I can start from the first episode, but this needs to be done manually every time now.

**Comment by nichwall** [comment] 2024-05-09 20:47
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1321

https://github.com/advplyr/audiobookshelf-app/issues/473

**Closed** 2024-05-10 00:42 UTC
Labels: enhancement
