### ISSUE TITLE
[Bug]: Windows installer continues to check and install the same update

### ISSUE THREAD

**Issue by Dinglyberry** [advplyr/audiobookshelf#2546] opened 2024-01-23 13:32 UTC
### Describe the issue

After completing the install, ABS says there is an update and would you like to install it, after clicking yes, ABS Shuts down, downloads the latest update, installs it and then repeats there is another update, and wants to install the same update and this continues until you say no.

### Steps to reproduce the issue

1. run the AudiobookshelfInstaller.v2.7.2.1.exe and accept the default install options and tick the create shortcut on desktop option

### Audiobookshelf version

2.7.2.1

### How are you running audiobookshelf?

Other

**Comment by nichwall** [comment] 2024-01-23 13:44
https://github.com/mikiher/audiobookshelf-windows/issues

**Comment by theboo** [comment] 2024-01-23 14:14
Have reported here already: https://github.com/mikiher/audiobookshelf-windows/issues/7

**Comment by advplyr** [comment] 2024-01-23 15:11
Duplicate of https://github.com/mikiher/audiobookshelf-windows/issues/7

**Closed by advplyr** 2024-01-23 15:11 UTC
Labels: bug
