### ISSUE TITLE
[Bug]: PublishedYear in Book metadata has mismatched type

### ISSUE THREAD

**Issue by jakoss** [advplyr/audiobookshelf#1626] opened 2023-03-21 10:26 UTC
### Describe the issue

I'm trying to use the API. When i download by library i stumbled upon issue in the Book Metadata model. The property "PublishedYear" sometimes is returned as string (with quotes) and sometimes as an integer. This is quite an issue for static typed languages and their json decoders setup

### Steps to reproduce the issue

I don't know if there is an reproduction pattern. In my library one of the books i have returns the PublishedYear as an integer

### Audiobookshelf version

v2.2.17

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-03-21 22:38
Have you updated any data via the API? I think this should always be a string unless you passed in a number via the API.

We should coerce to a string even when updating via the API but we are moving to a new relational model so I don't think this is an important update with the current API.

**Comment by jakoss** [comment] 2023-03-22 07:38
I didn't update data via the api, but i did update it via the "match" functionality, maybe issue was something there? The issue is minor, i can just ignore that field for now.

**Comment by advplyr** [comment] 2023-03-22 21:40
This can fall under the same issue as #1434

**Comment by advplyr** [comment] 2023-03-22 21:40
Duplicate of #1434

**Closed by advplyr** 2023-03-22 21:40 UTC
Labels: bug
