### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by dchardin** [advplyr/audiobookshelf#1506] opened 2023-02-14 16:43 UTC
### Describe the feature/enhancement

I have been using Airsonic as my audio server since there are already a lot of "Subsonic-compatible" clients for both iOS and Android. I was wondering if it would be feasible to add "subsonic-client" support into Audiobookshelf. That way, we could make use of the existing Subsonic-compatible clients that are already out there.

**Comment by advplyr** [comment] 2023-02-14 17:20
Duplicate of #399

**Closed by advplyr** 2023-02-14 17:20 UTC
Labels: enhancement
