### ISSUE TITLE
[Bug]: Speed not carrying across play sessions

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#1576] opened 2023-03-03 22:38 UTC
### Describe the issue

This used to work great, set the speed and next time you opened the book and continued it would be the same speed you set. Now every time the app closes it resets to 1x

Video: https://www.dropbox.com/s/rkz7mefq2gvful9/2023_03_03_22_32_38.mp4?dl=0

### Steps to reproduce the issue

1. Open app
2. Start playback
3. Set speed
4. close app
5. open app
6. start playback
7. speed has reset

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by MrBearedJoe** [comment] 2023-03-03 22:48
@barelylit This is the service repo. There is a bug listing for this issue somewhere in the app repo

**Comment by advplyr** [comment] 2023-03-03 23:02
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/532

**Closed by advplyr** 2023-03-03 23:02 UTC
Labels: bug
