### ISSUE TITLE
[Enhancement]: Add setting to the playlist to remove already listened episodes.

### ISSUE THREAD

**Issue by edersong** [advplyr/audiobookshelf#2456] opened 2023-12-27 14:36 UTC
### Describe the feature/enhancement

Add setting to the playlist to remove already listened episodes.

**Comment by advplyr** [comment] 2023-12-27 14:37
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1405

**Closed by advplyr** 2023-12-27 14:37 UTC
Labels: enhancement
