### ISSUE TITLE
[Enhancement]: Auto skip ADs within a podcast

### ISSUE THREAD

**Issue by upamanyudas** [advplyr/audiobookshelf#2908] opened 2024-05-02 22:03 UTC
### Describe the feature/enhancement

This would be a awesome feature to have when listening to podcasts hands-free, e.g. while running or walking or driving. Annoying if an AD starts in-between a podcast and manual skipping is super inconvenient.
There is some development happening in this space with [podcast-sponsor-block](https://github.com/ericmedina024/podcast-sponsor-block).

**Comment by nichwall** [comment] 2024-05-02 23:03
Is there a reason you can't just request the RSS feed from there?

**Comment by upamanyudas** [comment] 2024-05-04 07:23
just bettering the feature-set of audiobookshelf and keeping all things to on service? my intention would be for us to have a native integration or maybe even adopt and extend.

**Comment by nichwall** [comment] 2024-05-04 15:31
I'm confused. The project you linked to says it returns an RSS feed with files edited to remove the sponsored sections so ABS doesn't need to do anything because it will only ever see the edited files, right?

Adding this functionality is unlikely to be done within the core ABS and falls more under a third party service or provider that you can request the RSS feed from.

**Comment by upamanyudas** [comment] 2024-05-05 05:51
hmm, i'm more thinking of a feature along the brand of skip intro / skip credits on plex, but only so much better for pods...

**Comment by nichwall** [comment] 2024-05-05 14:04
That would be a duplicate of https://github.com/advplyr/audiobookshelf/issues/2203

**Closed** 2024-05-07 14:47 UTC
Labels: enhancement
