### ISSUE TITLE
[Enhancement]: Ignore all folders matching a certain expression

### ISSUE THREAD

**Issue by Hoempi** [advplyr/audiobookshelf#1003] opened 2022-09-22 08:53 UTC
### Describe the feature/enhancement

As a user running audiobookshelf on a NAS I would like to be able to ignore all folders matching a certain expression. 

For instance on Synology devices with Universal search enabled, a directory "@eaDir" is created inside the folders of my audiobooks.

Placing an ".ignore" file into each subfolder is quite a hassle, especially when migrating larger libraries to audiobookshelf. That's why I would like an option for administrators to provide multiple expressions to filter out matching folders in general. Either via the settings page or via environment variables. For a MVP simple matching would be sufficient and RegEx expressions would not be needed.

**Comment by advplyr** [comment] 2023-07-15 18:53
The consensus was that we add support for a `.absignore` file similar to `.plexignore`. This was discussed #1641 so will use that as the main thread

**Comment by advplyr** [comment] 2023-07-15 18:53
Duplicate of #1641

**Closed by advplyr** 2023-07-15 18:53 UTC
Labels: enhancement
