### ISSUE TITLE
[Enhancement]: Possibility to stream audiobooks in Android Auto

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf#2664] opened 2024-02-25 21:19 UTC
### Describe the feature/enhancement

Currently it's only possible to listen to audio books in Android Auto after downloading them to your android phone.
It would be great if these could also be streamed directly instead of downloading them first.

**Comment by advplyr** [comment] 2024-02-25 21:26
This is already supported but there is a bug in the current release I already have fixed for the next release. See https://github.com/advplyr/audiobookshelf-app/issues/1081

**Comment by advplyr** [comment] 2024-02-25 21:26
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/1081

**Closed by advplyr** 2024-02-25 21:26 UTC
Labels: enhancement
