### ISSUE TITLE
[Bug]: Podcasts with many episodes cause (frontend) performance issues

### ISSUE THREAD

**Issue by martini1992** [advplyr/audiobookshelf#2393] opened 2023-12-06 13:08 UTC
### Describe the issue

Podcasts with many episodes cause (frontend) performance issues, huge memory usage in browser causing unresponsiveness and communication errors with backend.

I recently found this gem of a pre-podcast podcast, I suppose it would be an old public-access radio show who also published their episodes online. [http://radiotiki.com/](http://radiotiki.com/)
It was running from early 2000 to 2016, it started as a weekly thing but because of the dialup most people had back then the episodes were cut into more manageably sized pieces, in all there are 1579 "episodes" according to AudioBookShelf.

While on the podcasts episodes page in ABS the performance is very unresponsive and the browser tab uses 1.6GB RAM. I assume the same issue also affects the android app because similar performance issues are observed there.

I assume this is because all episode entries are loaded into memory as one json object and inserted into the DOM too. Maybe a fix would be to use paging/lazyloading of the episodes since what's not visible on the screen need not be loaded into browser memory.

I realise this is an extreme case, however ABS can also be used for listening to radio shows, and there are many which have been running for decades which have large numbers of episodes, For (an even more extreme) instance [https://en.wikipedia.org/wiki/The_Archers](https://en.wikipedia.org/wiki/The_Archers) at 20,000+ episodes.

### Steps to reproduce the issue

1. Add https://radiotiki.s3.amazonaws.com/archive.rss as RSS podcast
2. Manually discover all the episodes (Dec 1999 is back far enough)
3. Wait for them to download (~13GB)
4. Try to play the first episode and interact with the UI.

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2023-12-06 13:36
This is a known issue with podcasts since server version `2.4.0`.

Fixes are still in progress since it requires an update to the API and how data is handled by the apps.

https://github.com/advplyr/audiobookshelf/issues/2073

**Comment by nichwall** [comment] 2023-12-06 14:07
No worries, it's not named something you'd think to search.

In the meantime if you need large podcasts and can't live with the delay, you could use server version `2.3.3`. You won't have new features/fixes, but some people are hanging out on that version in the meantime. You could also run two servers, one for audiobooks (on the newer versions) and one for podcasts (on `2.3.3`).

**Comment by advplyr** [comment] 2023-12-06 14:21
Duplicate of #2075 

Also https://github.com/advplyr/audiobookshelf-app/issues/200 and https://github.com/advplyr/audiobookshelf/issues/2073

**Closed by advplyr** 2023-12-06 14:21 UTC
Labels: bug
