### ISSUE TITLE
[Enhancement]: M4b Menge

### ISSUE THREAD

**Issue by letternews** [advplyr/audiobookshelf#2911] opened 2024-05-03 13:59 UTC
### Describe the feature/enhancement

First if all I love your program. One Feature I would appreciate is an automatic merging of mp3 files into an m4b. If that is not possible, is there an option to detect the bitrate and merge the files with that bitrate instead of reencoding, just like m4b-merge or bragi books?

**Comment by nichwall** [comment] 2024-05-03 14:14
M4b merging is already implemented (but is not available in the Windows native install yet).

There are some issues with large books, and tone (the tool that is doing the merging) had some issues so it is planned to be replaced with ffmpeg. There was a recent release of tone that may fix some of the issues.

**Comment by letternews** [comment] 2024-05-03 14:22
Thanks for your prompt response. I use Audiobookshelf through docker on a mac and as for as I can tell there is an option to merge, but the kbps rate is not detected and therefore sometimes the standard rate of 128 kbps is used even though the source is 64 kbps. Sure it's no Problem to check the rate first and use the specified rate but it would be much simpler to automate? And would it be possible to add an option to merge the files in the library automatically?

**Comment by advplyr** [comment] 2024-05-03 14:56
We've talked about this in Discord a few times and maybe GH but I couldn't find the specific conversation. This would fall into #1257 though

As for automatic m4b merging it is unlikely to be added but if it was added we would need to handle #1267 and #1936 first. I believe that has been brought up and linked to those issues also.

Also related https://github.com/advplyr/audiobookshelf/issues/1818

**Comment by advplyr** [comment] 2024-05-03 14:56
Duplicate of #1257

**Closed by advplyr** 2024-05-03 14:56 UTC
Labels: enhancement
