### ISSUE TITLE
[Bug]: FantLab Metadata Provider Fails to Load

### ISSUE THREAD

**Issue by cor-bee** [advplyr/audiobookshelf#3004] opened 2024-05-24 12:34 UTC
### What happened?

FantLab.ru metadata provider fails to load.

https://github.com/advplyr/audiobookshelf/assets/40601422/61af247d-35f1-4945-9ba1-3def78fbb5fb

It wouldn't have been an issue since I'm not using FantLab.ru but this is causing me to wait 2-3 minutes every time I'm searching for book covers with "All" providers selected. 

### What did you expect to happen?

It seems that FantLab.ru has been blocked for Ukrainian users since the Russian full-scale invasion of Ukraine.

To fix that you need to either remove the FantLab.ru metadata provider entirely or change it to .org mirror.

### Steps to reproduce the issue

1. Use a Ukrainian VPN address
2. Try to load the book cover with the "All" or "FantLab.ru" metadata provider selected

### Audiobookshelf version

v2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment] 2024-05-24 13:38
Are there any server logs indicating a connection timeout or unreachable that can be used?

**Comment by cor-bee** [comment] 2024-05-24 16:09
> Are there any server logs indicating a connection timeout or unreachable that can be used?

Here you are:

![Arc_X7ztxi2F0a](https://github.com/advplyr/audiobookshelf/assets/40601422/2ff90dbf-7444-40be-8be8-f03ac194bd90)

**Comment by advplyr** [comment] 2024-05-24 16:12
I'm not sure if we can do anything more than set a reasonable timeout which is requested here https://github.com/advplyr/audiobookshelf/issues/3000

As for the "All" option causing issues with this @nichwall put in https://github.com/advplyr/audiobookshelf/issues/3005 for that

**Comment by advplyr** [comment] 2024-05-24 16:12
Duplicate of #3000

**Closed by advplyr** 2024-05-24 16:12 UTC
Labels: bug
