### ISSUE TITLE
[Enhancement]: Merge tags

### ISSUE THREAD

**Issue by bahuma20** [advplyr/audiobookshelf#2713] opened 2024-03-06 10:17 UTC
### Describe the feature/enhancement

When importing data from online services, the tags have no unique naming scheme.

This could be caused by different translations or slightly different naming.

The idea of this feature request is, that admins can go to the tags management page, select multiple tags and choose the action "merge". 

They can then enter a new name for these tags.

On save it will update the tags in the audiobooks and replace them with the new common tag name.

**Comment by nichwall** [comment] 2024-03-06 13:41
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1864

**Comment by advplyr** [comment] 2024-03-06 21:01
Duplicate of #1864

**Closed by advplyr** 2024-03-06 21:01 UTC
Labels: enhancement
