### ISSUE TITLE
[Enhancement]: Remove/Hide All Authors With 0 Books

### ISSUE THREAD

**Issue by valdearg** [advplyr/audiobookshelf#3325] opened 2024-08-22 22:33 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Throughout the long time I've been using ABS I've had lots of occasions where the authors are perhaps incorrect and I've updated these.

ABS will still display these in the Authors tab.

I was wondering if it might be possible to either, not display authors who have 0 books. Or have an option to purge these items.

![image](https://github.com/user-attachments/assets/407f9435-c515-4b65-9f43-2da3f9f2b28e)

### Why would this be helpful?

Really it's purely an OCD thing for when I'm going through the metadata!

### Future Implementation (Screenshot)

In the below screenshot you can see a couple, e.g. A.G Riddle which was then changed to A.G. Riddle. 

A.G Riddle entry remains showing.

![1246-507-max](https://github.com/user-attachments/assets/a089aae3-2cd8-4255-b9f5-545691238e9b)

### Audiobookshelf Server Version

2.12.3

**Comment by nichwall** [comment] 2024-08-22 23:09
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2466

Authors with zero books only show up for admin users and are hidden for other users (such as if a user does not have access to any books by that author).

**Closed** 2024-08-23 21:05 UTC
Labels: enhancement
