### ISSUE TITLE
[Enhancement]: Allow iOS app to Delete Media from Server.

### ISSUE THREAD

**Issue by slyfoxgh** [advplyr/audiobookshelf#2603] opened 2024-02-12 01:15 UTC
### Describe the feature/enhancement

Please add an option for the iOS app to delete media files from the server. This is useful after listening to something that you no longer want to keep. Doing this right away is better than trying to remember to do it later.

**Comment by nichwall** [comment] 2024-02-12 01:45
The app is designed for consuming media not server management, but the podcast workflow makes this a bit inconsistent. Server management (deleting files, updating tags, editing details and metadata, etc) should be done from within a web client, which you can access using your mobile web browser to delete it right away.

Related: https://github.com/advplyr/audiobookshelf/issues/615

Also potential duplicate of https://github.com/advplyr/audiobookshelf-app/issues/955 if you're talking about deleting podcasts

**Comment by advplyr** [comment] 2024-02-12 22:52
I updated https://github.com/advplyr/audiobookshelf-app/issues/955 to be for deleting books & podcasts since it is the same process, they are both library items.

This is also opened in the wrong repo

**Comment by advplyr** [comment] 2024-02-12 22:52
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/955

**Closed by advplyr** 2024-02-12 22:52 UTC
Labels: enhancement
