### ISSUE TITLE
[Bug]: New Books Not being Scanned and Added 2.10.0

### ISSUE THREAD

**Issue by BlwAvg** [advplyr/audiobookshelf#3025] opened 2024-05-27 16:18 UTC
### What happened?

I updated to 2.10 before scanning my library. I was able to add books in all versions of 2.9.0. My guess the issue is with advplyr/audiobookshelf/blob/master/server/scanner/AudioFileScanner.js. Only because it was changed in the last three days. I did a compare with old code to the new, but I dont actually know anything about coding. The changes looks like mostly formatting and obviously the new chapter sorter. I am happy to troubleshoot more if you can point me in a direction.

 **ABS Logs** 
ERROR
[AudioFileScanner] Probe Failed : "/mnt/nas_audio_books/ABS/Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure/Azarinth Healer- Book One - A LitRPG Adventure.m4b"

DEBUG
[LibraryScan] "Audio Book Library": Library item at path "Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure" has no audio files and no ebook file - ignoring

**Manual Probe 1**
SuperCoolUser@ABS_Stuff:/mnt/ThisIsAMount/ABS/Rhaegar/Azarinth Healer/Azarinth Healer Book One  A LitRPG Adventure$ /usr/lib/audiobookshelf-ffmpeg/ffprobe -v error -show_entries format_tags -of default=noprint_wrappers=1:nokey=1 'Azarinth Healer- Book One - A LitRPG Adventure.m4b'
M4A
512
M4A isomiso2
2022-11-30T18:06:34.000000Z
Azarinth Healer: Book One - A LitRPG Adventure
... More output showing the probe worked

**Manual Probe 2**
SuperCoolUser@ABS_Stuff:/mnt/ThisIsAMount/ABS/Rhaegar/Azarinth Healer/Azarinth Healer Book One  A LitRPG Adventure$ /usr/lib/audiobookshelf-ffmpeg/ffprobe -v error -show_format -show_streams 'Azarinth Healer- Book One - A LitRPG Adventure.m4b'
[STREAM]
index=0
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
... More output showing the probe worked

### What did you expect to happen?

Th scan should add the books to the library.

### Steps to reproduce the issue

1. Update to 2.10
2. add books to library 
3. run an update library scan.

### Audiobookshelf version

2.10.0

### How are you running audiobookshelf?

Debian/PPA

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Logs

```shell
2024-05-27 08:22:59.719

ERROR

[AudioFileScanner] Probe Failed : "/mnt/nas_audio_books/ABS/Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure/Azarinth Healer- Book One - A LitRPG Adventure.m4b"

2024-05-27 08:22:59.719

DEBUG

[LibraryScan] "Audio Book Library": Library item at path "Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure" has no audio files and no ebook file - ignoring

2024-05-27 08:34:12.771

ERROR

[AudioFileScanner] Probe Failed : "/mnt/nas_audio_books/ABS/Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure/Azarinth Healer- Book One - A LitRPG Adventure.m4b"

2024-05-27 08:34:12.771

DEBUG

[LibraryScan] "Audio Book Library": Library item at path "Rhaegar/Azarinth Healer/Azarinth Healer Book One A LitRPG Adventure" has no audio files and no ebook file - ignoring
```

### Additional Notes

If this only effects me just let me know and I will keep troubleshooting on my side. I do not want to burn your cycles working on my issue.

**Comment by BlwAvg** [comment] 2024-05-27 16:20
This is only one example that has a pretty complicated folder structure, I can provide other examples if you would like that are much less complicated.

**Comment by advplyr** [comment] 2024-05-27 16:50
Not just you https://github.com/advplyr/audiobookshelf/issues/3024 but does seem to be specific to Debian/PPA.

I'm not sure what else to try atm

**Comment by advplyr** [comment] 2024-05-27 16:50
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3024

**Closed as not planned by advplyr** 2024-05-27 16:50 UTC
Labels: bug
