### ISSUE TITLE
[Enhancement]: Option to hide Series from Series overview 

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1393] opened 2023-01-11 17:03 UTC
### Describe the feature/enhancement

An Option for a Series to hide in Series overwiew would be nice, so we can create a Series that is only shown in another Series for a more granular sort.

**Comment by hobesman** [comment] 2023-01-11 20:07
Another approach might be to provide a toggle "show primary series only" vs "show primary series AND subseries"

**Comment by Blindie92** [comment] 2023-01-11 22:42
Another Idea, on the start page, the next audiobook for the series should be only from the sub series, not two from sub and main series.

**Comment by advplyr** [comment] 2023-09-17 13:00
Can this be merged with #2092? It seems like the same

**Comment by Blindie92** [comment] 2023-09-17 15:54
Yes, looks like the same

**Comment by advplyr** [comment] 2023-09-17 16:13
Duplicate of #2092

**Closed by advplyr** 2023-09-17 16:13 UTC
Labels: enhancement
