### ISSUE TITLE
[Enhancement]: Search should cross libraries

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2903] opened 2024-05-01 20:07 UTC
### Describe the feature/enhancement

As my implementation is currently configured, I have my collection separated into several libraries to make management easier. This includes having separate Fiction, Non-Fiction, Science Fiction, Western, and Great Courses libraries (not to mention Star Wars, Lord of the Rings, Sherlock Holmes, Doctor Who, and DC Comics). 

As currently designed, a search is limited to the currently selected library. While quick search should remain with the selected library, an extended search should go across all accessable libraries with the results being the current selected library first, then other libraries second.

**Comment by advplyr** [comment] 2024-05-01 21:55
Duplicate of https://github.com/advplyr/audiobookshelf/issues/556

**Closed by advplyr** 2024-05-01 21:55 UTC
Labels: enhancement
