### ISSUE TITLE
[Enhancement]: Extract episode number from title as a fallback

### ISSUE THREAD

**Issue by mikiher** [advplyr/audiobookshelf#2996] opened 2024-05-22 06:37 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

I've recently encountered this on my Podcasts homepage:
<img width="475" alt="Screenshot 2024-05-22 092435" src="https://github.com/advplyr/audiobookshelf/assets/22557398/3f402dd0-8b53-498f-ace0-b459d23176f0">

Looking at the server response payload, the episode number does seem to be missing:
<img width="460" alt="Screenshot 2024-05-22 092850" src="https://github.com/advplyr/audiobookshelf/assets/22557398/7ef48c3e-7ec0-4b0b-8dd8-47a9e08224f3">

Not sure why the payload is missing the episode number. Assuming it's not a bug, it looks like we can extract it from the title quite easily.

### Why would this be helpful?

It will show the correct episode number.

### Future Implementation (Screenshot)

Shows "Episode #365" instead of "Episode"

### Audiobookshelf Server Version

v2.9.0

**Comment by advplyr** [comment] 2024-05-22 09:43
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2698

**Closed by advplyr** 2024-05-22 09:43 UTC
Labels: enhancement
