### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gaspoweredflea** [advplyr/audiobookshelf#1733] opened 2023-04-27 13:38 UTC
### Describe the issue

Whenever i add SOME new books, it gives me an error in logs and a completely unrelated random book is marked as 'missing'

Reference Discord chat with advplyr in #server-troubleshooting.
Might be related to #1447

### Steps to reproduce the issue

1. move new book into folder
2. nothing happens in abs, but the screenshot shows in log
3. remove new book from folder, a random book is marked as 'missing'

### Audiobookshelf version

2.2.19

### How are you running audiobookshelf?

Docker

**Comment by gaspoweredflea** [comment] 2023-04-28 08:23
Update: 
Switched hdd2 to ext4, and the problem went away, so definitely looks like inode collision issue as described in #1447  ... the ext4 inode numbers are much higher and longer than btrfs inode numbers. Likely this issue can be merged with #1447

**Comment by advplyr** [comment] 2023-04-28 21:01
Thanks for digging into this. I didn't realize that some file system would provide such a small inode value.

I'm glad we tracked this down. I'm not sure how to handle renames without using an inode though

**Comment by advplyr** [comment] 2023-04-28 21:01
Duplicate of #1447

**Closed by advplyr** 2023-04-28 21:01 UTC
Labels: bug
