### ISSUE TITLE
[Enhancement]: Listen to audiobooks together (A listen party, if you will)

### ISSUE THREAD

**Issue by freedbygrace** [advplyr/audiobookshelf#3203] opened 2024-07-29 17:22 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

To be able to listen to an audiobook with a friend that is not close in distance, and be able to discuss the content live time.

### Why would this be helpful?

It would take audiobooks to the next level.

### Future Implementation (Screenshot)

N/A

### Audiobookshelf Server Version

2.11.0

**Comment by nichwall** [comment] 2024-07-29 17:27
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2725

**Closed** 2024-07-29 21:46 UTC
Labels: enhancement
