### ISSUE TITLE
[Enhancement]: Support for merging authors with multiple pen names

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#2951] opened 2024-05-08 20:45 UTC
### Describe the feature/enhancement

Some authors publish under multiple names. Currently, if I want all books by such an author to appear in the same list, I need to choose one pen name and assign all books they've written to that author. This is not ideal for at least two reasons:

- It's a bad metadata practice. Books should have the author listed in metadata as published.
- It hinders searchability. If I chose "Samuel Clemens" and you searched for "Mark Twain," You wouldn't find anything he'd written, even if I have his complete works.

**Comment by nichwall** [comment] 2024-05-08 20:48
You can add multiple authors to a book, so in the meantime you could add "Samuel Clemens" to all books by him, and then also add "Mark Twain" to the appropriate books.

**Comment by advplyr** [comment] 2024-05-08 21:22
Duplicate of https://github.com/advplyr/audiobookshelf/issues/908

**Closed by advplyr** 2024-05-08 21:22 UTC
Labels: enhancement
