### ISSUE TITLE
[Enhancement]: Linked Files Section

### ISSUE THREAD

**Issue by colvdv** [advplyr/audiobookshelf#2588] opened 2024-02-06 05:25 UTC
### Describe the feature/enhancement

I have a book that I also have the audiobook for and I have both in separate libraries on the same server. I want them linked together so that when viewing the book I can see that the audiobook is also available, and when viewing the audiobook I can see that the PDF readable version is also available, without having a separate PDF in the audiobook folder.

If this is already doable, I appreciate a walkthrough on how to do this.

Thank you for all the energy and effort put into this project. I simply love it so far!

**Comment by nichwall** [comment] 2024-02-06 05:38
There is not a way to merge library items. It's been discussed, but not sure when it will be implemented (can't find an open issue for it but pretty sure there's one somewhere)

In the meantime you'll either need to add the PDF to the same folder like you mentioned or add a symlink in the filesystem if you don't want two copies of both files.

**Comment by advplyr** [comment] 2024-06-11 18:22
Making the primary issue for this https://github.com/advplyr/audiobookshelf/issues/3062 because it is using the updated issue template

**Comment by advplyr** [comment] 2024-06-11 18:22
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3062

**Closed by advplyr** 2024-06-11 18:22 UTC
Labels: enhancement, backlog
