### ISSUE TITLE
[Enhancement]:  Lack of functionality for artists

### ISSUE THREAD

**Issue by vsuh** [advplyr/audiobookshelf#1713] opened 2023-04-24 09:55 UTC
### Describe the feature/enhancement

- Selection books by performer
- Performer description
- Performer rating (Perhaps an overall rating as the average rate of books already heard)
- Possibly, performer photos

**Comment by advplyr** [comment] 2023-04-24 22:32
Duplicate of #860

**Comment by advplyr** [comment] 2023-04-24 22:33
Duplicate of #1139

**Closed by advplyr** 2023-04-24 22:32 UTC
Labels: enhancement
