### ISSUE TITLE
[Enhancement]: Support for Audiobook Series that have no Author

### ISSUE THREAD

**Issue by kuldan5853** [advplyr/audiobookshelf#2922] opened 2024-05-05 13:21 UTC
### Describe the feature/enhancement

Hi Team,

I'm loving ABS so far but I struggle with setting up my media library, which mainly consists not of Audiobooks, but Radio Dramas (a very popular genre in Germany). 

The main difference is that a Radio Drama has no specific Author, but operates more like a TV Show - it has a Title and Episodes. 

This unfortunately means that the current scanner does not autodetect Series and Sequences, as it does not recognize Title\<sequence number> - Title of Episode as a valid format. 

A bypass right now is to double the Title (Title\Title\01 - Episode), but that is obviously not really pretty and also not desirable if you use your library with other tools than ABS as well. 

My suggestion would be to either make the search much more customizable (custom define what counts as a title / show / episode), but for my / the Radio Drama use case, it would be enough to add a mode that does the following:

- Look at Folder Tree
- Take the second to last Folder as the "Series"
- Take the last Folder as the "Episode", and the Sequence Number from it
(With the caveat that the "last" Folder still could contain a CD1/CD2/CD3... folder).

**Comment by advplyr** [comment] 2024-05-05 13:28
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2208

**Closed by advplyr** 2024-05-05 13:28 UTC
Labels: enhancement
