### ISSUE TITLE
[Enhancement]: Exportable reports for viewing locally

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2829] opened 2024-04-06 02:48 UTC
### Describe the feature/enhancement

As server administrator, I want to be able to export a list of books and their associated values for data analysis. I can then do filtering to see which books are missing "Tags" and perform the appropriate data imports (as an example). There are libraries available so that you can create Excel and OpenDocument spreadsheets in addition to CSVs.

**Comment by nichwall** [comment] 2024-04-06 06:43
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2085

**Comment by advplyr** [comment] 2024-04-06 21:55
Duplicate of #2085

**Closed by advplyr** 2024-04-06 21:55 UTC
Labels: enhancement
