### ISSUE TITLE
[Enhancement]: iOS App - get Feature from Android App

### ISSUE THREAD

**Issue by kaiminator** [advplyr/audiobookshelf#1858] opened 2023-06-20 11:54 UTC
### Describe the feature/enhancement

Hi,

Is it possible to get the following Android App Settings for the iOS App?.

- Auto Sleep Timer
- Auto Sleep Timer Auto rewind

**Comment by advplyr** [comment] 2023-06-20 13:45
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/260

**Closed by advplyr** 2023-06-20 13:45 UTC
Labels: enhancement
