### ISSUE TITLE
[Enhancement]: Filter to show Audiobooks where information differes from Audiobookshelf and file

### ISSUE THREAD

**Issue by b3nd1k** [advplyr/audiobookshelf#1935] opened 2023-07-18 21:02 UTC
### Describe the feature/enhancement

As described in #1934, I often find my server crashing when I have books in queue waiting to be embedded. When this happen, I would like to know which books made it through the embedding and which does not. 

I'd like to propose a filter named "Information differs from Audioobokshelf and file" or something similar that shows books where information difers. Then you can manually go through and restart the embedding again on these files.

**Comment by advplyr** [comment] 2023-07-18 21:06
Duplicate of #1054

**Closed by advplyr** 2023-07-18 21:06 UTC
Labels: enhancement
