### ISSUE TITLE
[Bug]: Web interface fails playback: 'Invalid data found when processing input'

### ISSUE THREAD

**Issue by ak-42** [advplyr/audiobookshelf#2848] opened 2024-04-13 20:24 UTC
### Describe the issue

Hello. First of all, thank you for this excellent solution for self-hosted audiobooks.

I have an audiobook that fails to play using the web interface. Works fine using VLC and it also works fine using the Audiobookshelf Android app.

These are the relevant logs created when you press play and the playback fails:

<details>
<summary>Logs</summary>

```
audiobookshelf           | [2024-04-13 22:07:40.054] INFO: [PlaybackSessionManager] startSession: Closing open session "Meditations" for user "user" (Device: Linux x86_64 / Firefox)
audiobookshelf           | [2024-04-13 22:07:40.064] INFO: [STREAM] START STREAM - Num Segments: 2635
audiobookshelf           | [2024-04-13 22:07:40.073] INFO: [INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -i /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/files.txt -y -loglevel error -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/output-%d.ts /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/final-output.m3u8
audiobookshelf           | [2024-04-13 22:07:40.074] INFO: 
audiobookshelf           | [2024-04-13 22:07:40.226] WARN: File path does not exist /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/output-0.ts (HlsRouter.js:75)
audiobookshelf           | [2024-04-13 22:07:40.338] INFO: [adts @ 0x780448efa740] Scalable configurations are not allowed in ADTS
audiobookshelf           | [2024-04-13 22:07:40.339] INFO: [out#0/hls @ 0x780448f06340] Could not write header (incorrect codec parameters ?): Invalid data found when processing input
audiobookshelf           | [2024-04-13 22:07:40.339] INFO: Error opening output file /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/final-output.m3u8.
audiobookshelf           | [2024-04-13 22:07:40.339] INFO: Error opening output files: Invalid data found when processing input
audiobookshelf           | [2024-04-13 22:07:40.367] INFO: 
audiobookshelf           | [2024-04-13 22:07:40.368] ERROR: Ffmpeg Err "ffmpeg exited with code 183: Error opening output file /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56/final-output.m3u8.
audiobookshelf           | Error opening output files: Invalid data found when processing input
audiobookshelf           | " (Stream.js:342)
audiobookshelf           | [2024-04-13 22:07:40.370] INFO: Closing Stream c95d1776-5ab8-487e-8f13-76a974b22f56
audiobookshelf           | [2024-04-13 22:07:40.374] INFO: Deleted session data /metadata/streams/c95d1776-5ab8-487e-8f13-76a974b22f56
audiobookshelf           | [2024-04-13 22:07:41.358] ERROR: [HlsRouter] Stream "c95d1776-5ab8-487e-8f13-76a974b22f56" does not exist (HlsRouter.js:56)
```

</details>

<details>
  <summary>Probe of the offending file using the web interface</summary>

```
{
  "programs": [],
  "streams": [
    {
      "index": 0,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_tag_string": "mp4a",
      "codec_tag": "0x6134706d",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "initial_padding": 0,
      "id": "0x1",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/44100",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 834560,
      "duration": "18.924263",
      "bit_rate": "125589",
      "nb_frames": "815",
      "extradata_size": 2,
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "non_diegetic": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "language": "und",
        "handler_name": "SoundHandler",
        "vendor_id": "[0][0][0][0]"
      }
    },
    {
      "index": 1,
      "codec_name": "bin_data",
      "codec_long_name": "binary data",
      "codec_type": "data",
      "codec_tag_string": "text",
      "codec_tag": "0x74786574",
      "id": "0x2",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/1000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 18924,
      "duration": "18.924000",
      "bit_rate": "10",
      "nb_frames": "1",
      "extradata_size": 43,
      "disposition": {
        "default": 1,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0,
        "non_diegetic": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      },
      "tags": {
        "creation_time": "2024-04-04T11:18:08.000000Z",
        "language": "und",
        "handler_name": "Chapter titles"
      }
    },
    {
      "index": 2,
      "codec_name": "mjpeg",
      "codec_long_name": "Motion JPEG",
      "profile": "Baseline",
      "codec_type": "video",
      "codec_tag_string": "[0][0][0][0]",
      "codec_tag": "0x0000",
      "width": 500,
      "height": 500,
      "coded_width": 500,
      "coded_height": 500,
      "closed_captions": 0,
      "film_grain": 0,
      "has_b_frames": 0,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "1:1",
      "pix_fmt": "yuvj420p",
      "level": -99,
      "color_range": "pc",
      "color_space": "bt470bg",
      "chroma_location": "center",
      "refs": 1,
      "id": "0x0",
      "r_frame_rate": "90000/1",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 0,
      "start_time": "0.000000",
      "duration_ts": 1703184,
      "duration": "18.924267",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 1,
        "timed_thumbnails": 0,
        "non_diegetic": 0,
        "captions": 0,
        "descriptions": 0,
        "metadata": 0,
        "dependent": 0,
        "still_image": 0
      }
    }
  ],
  "chapters": [
    {
      "id": 0,
      "time_base": "1/1000",
      "start": 0,
      "start_time": "0.000000",
      "end": 18000,
      "end_time": "18.000000",
      "tags": {
        "title": "Chapter 1"
      }
    }
  ],
  "format": {
    "filename": "/audiobooks/Marcus Aurelius/Meditations/01 - Meditations - Marcus Aurelius.m4b",
    "nb_streams": 3,
    "nb_programs": 0,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "format_long_name": "QuickTime / MOV",
    "start_time": "0.000000",
    "duration": "18.924263",
    "size": "327586",
    "bit_rate": "138482",
    "probe_score": 100,
    "tags": {
      "major_brand": "M4A ",
      "minor_version": "512",
      "compatible_brands": "isomiso2",
      "title": "01 - Meditations",
      "artist": "Marcus Aurelius",
      "comment": "redacted",
      "genre": "Audiobook",
      "copyright": "redacted",
      "album": "Meditations",
      "track": "1/17",
      "disc": "1/1",
      "date": "2024",
      "encoder": "Lavf58.29.100"
    }
  }
}
```

</details>

Happy to share one of the files in question, but will only do so if requested not to cause any copyright issues to this repo.

### Steps to reproduce the issue

1. Run Audiobookshelf.
2. Add the file in question.
3. Play using the web interface.

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2024-04-13 20:27
What browser are you using for the web interface?

**Comment by advplyr** [comment] 2024-04-13 22:28
Linux firefox from the logs. The same m4b firefox specific issue that continually comes up. 

Someone wrote the specifics about the issue here https://rentry.co/n4ost

It is old audible encodings that can be easily fixed with a one ffmpeg command to re-encode the file.

There is probably a dozen issues that have been opened up about this but this is the most recent active open one https://github.com/advplyr/audiobookshelf/issues/2720

**Comment by advplyr** [comment] 2024-04-13 22:28
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2720

**Closed by advplyr** 2024-04-13 22:28 UTC
Labels: bug

**Comment by ak-42** [comment] 2024-04-14 00:13
@advplyr If it is Firefox specific, then it's all good, my ABS is almost exclusively accessed via the Android app, Thank you for the efforts, I really appreciate it.
