### ISSUE TITLE
[Enhancement]: Do not re-download Completed/deleted episodes

### ISSUE THREAD

**Issue by mohammed90** [advplyr/audiobookshelf#3475] opened 2024-10-02 10:13 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

If an episode is downloaded, then marked as "Completed" and deleted by the user, the server should not download it again. If marked as "Completed" but not deleted, then it should be kept.

### Why would this be helpful?

Like all other users, I self-host this application. Most of the podcasts are configured with auto-download to make it easier for me to catch new episodes. If I'm not interested in an episode or have finished it already, I mark it "Completed" and delete it. I don't want to clutter my storage with files I won't need or refer to. The current implementation re-downloads the completed-and-deleted episode, no matter how many times I delete it.

### Future Implementation (Screenshot)

UI changes are not expected.

### Audiobookshelf Server Version

v2.13.4

**Comment by mohammed90** [comment] 2024-10-02 10:14
I'm not sure whether to consider the current behavior as bug or enhancement, so I went with "Enhancement".

**Comment by advplyr** [comment] 2024-10-02 12:33
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3085

**Closed by advplyr** 2024-10-02 12:33 UTC
Labels: enhancement
