### ISSUE TITLE
[Enhancement]: Placeholder books for wishlisted and pre-ordered books

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3561] opened 2024-10-29 01:18 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be nice to be able to put in a placeholder in our audiobook library for books that are in the following categories:

- Wishlisted for future purchase
- Pre-order for later addition

Visibility should be controlled to be admin-only or all users.

### Why would this be helpful?

There are books that I would like to purchase in the future when there is an audiobook sale and also if I'm waiting for the next book in the series. Having  a filter would help as well.

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/fcfb7fb5-cd3c-4355-8003-51f430315636)

### Audiobookshelf Server Version

v2.15.1

### Current Implementation (Screenshot)

Not currently existing

**Comment by nichwall** [comment] 2024-10-29 02:22
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3221

**Comment by ZLoth** [comment] 2024-10-29 02:38
I see. I passed the two links back to the Discord channels.

**Closed** 2024-11-06 23:04 UTC
Labels: enhancement
