### ISSUE TITLE
[Question]: Batch abs meta data to mp3 tag???

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1284] opened 2022-12-18 19:20 UTC
### Question:

Is there currently the possibility to write metadata stored as abs file into the tags of mp3 audio books by means of batch processing?

**Comment by advplyr** [comment] 2022-12-18 20:19
Not yet. Duplicate of #700

**Closed by advplyr** 2022-12-18 20:19 UTC
Labels: enhancement

**Comment by Hallo951** [comment] 2022-12-18 20:23
Thanks...
