### ISSUE TITLE
Apple Car Play

### ISSUE THREAD

**Issue by eximo84** [advplyr/audiobookshelf#894] opened 2022-08-04 16:48 UTC
### Describe the feature/enhancement

Would be nice to have a car play app.

**Comment by advplyr** [comment] 2022-08-04 21:11
Duplicate of https://github.com/advplyr/audiobookshelf-app/discussions/81

**Closed by advplyr** 2022-08-04 21:11 UTC
Labels: enhancement

**Comment by eximo84** [comment] 2022-08-04 22:47
Thanks. Sorry I did search but couldn't find anything.
