### ISSUE TITLE
[Bug]: Not able to remove books from the "Continue Listening" tray

### ISSUE THREAD

**Issue by oboe45** [advplyr/audiobookshelf#2368] opened 2023-11-29 18:58 UTC
### Describe the issue

When I have completed a book, the progress line shows 100%, the book is noted as completed, but it stays in the continue listening tray.  If I specifically "remove the item from the continue reading list",  sometimes the book disappears from the list, but it also sometimes reappears in the list", sometimes it just does not disappear.  This behaviour is evident in any book in the "continue reading" tray.

### Steps to reproduce the issue

1. select the option bottom right on book image in tray to "remove from continue listening" tray
2. book may, or may not disappear.
3. if it disappears, check later, and often it will have reappeared in the list, sometimes it disappears from the list

### Audiobookshelf version

V 2.6

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2023-11-29 18:59
Are you using the iOS app?

**Comment by oboe45** [comment] 2023-11-29 19:01
This behaviour occurs in the app running via Safari on IMAC.  I haven't tried same process on the IOS App

**Comment by advplyr** [comment] 2023-11-29 19:02
This is the issue https://github.com/advplyr/audiobookshelf/issues/1983#issuecomment-1783864608

Unfortunately right now the only way to resolve it is by manually deleting those duplicate rows in the db.

Did you have downloaded books you were listening to on an old server version v2.2.23 or below?

**Comment by oboe45** [comment] 2023-11-29 19:05
Probably, have been using for a long time. Is there a (simple, non-technical) guide to removing the duplicate rows.  Does this removal have any side effects??

**Comment by oboe45** [comment] 2023-11-29 19:07
OK I went to the #1983 - looks like the kind of solution that a simple user (like me) will probably screw up.  So, will live with it till a fix is available

**Comment by advplyr** [comment] 2023-11-29 19:12
Do you still have the books downloaded to a device?

**Comment by advplyr** [comment] 2023-11-29 19:14
In the mobile app you can try going to the book and using the "Discard Progress" option. Once you discard progress check the continue listening shelf

**Comment by advplyr** [comment] 2023-12-09 21:43
I realize you were probably coming up against #2392 which is a bug with the cache that I fixed. So it may not have been a duplicate record in the DB but instead just a caching issue. I'll close this as a duplicate until we can rule that out.

**Comment by advplyr** [comment] 2023-12-09 21:43
Duplicate of #2392

**Closed by advplyr** 2023-12-09 21:43 UTC
Labels: bug

**Comment by oboe45** [comment] 2023-12-09 22:21
Why close this as not planned?  There is a real problem here, the line
recently read is meaningless if it doesnt update. My version for examples
begins with several books read some time ago and the idea of using this
tool as a way to keep "several books on the go" is useless.  If these is
not intent to fix the problem, remove the "recently read" line - or make
its display optional.

**Comment by advplyr** [comment] 2023-12-09 22:34
This isn't marked as not planned that is just what github says when you mark something as a duplicate. If click into the duplicate issue I linked it is the same problem you have with continue listening and the issue I fixed for the next release already.

If you were having a different issue then the one described then it may have been #1983 but you didn't answer my follow questions so I will assume it will be fixed in the next release. If it is not fixed in the next release you can follow up and say it is not and hopefully willing to have a back and forth to resolve it.

**Comment by oboe45** [comment] 2023-12-09 23:47
Thanks will check next release
