### ISSUE TITLE
[Bug]: Search fails to find known item if the query includes multiple spaces between words

### ISSUE THREAD

**Issue by DavidPesticcio** [advplyr/audiobookshelf#2684] opened 2024-02-28 09:47 UTC
### Describe the issue

If the search string contains multiple spaces, between words, the search will fail to find a known item.

Multiple spaces at the beginning or end of the search string do not effect search results.

### Steps to reproduce the issue

1. Select search box
2. Enter search string of known item with multiple spaces between any words
3. Nothing found

### Audiobookshelf version

2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2024-05-08 14:48
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1401

**Closed by advplyr** 2024-05-08 14:48 UTC
Labels: bug

**Comment by DavidPesticcio** [comment] 2024-05-08 15:18
> Duplicate of #1401

Not a duplicate - but the bug may be inadvertently fixed if a fuzzy search feature was implemented.

**Comment by advplyr** [comment] 2024-05-08 15:21
It's not a bug. The search was built very basic to search full text strings. If I had built the search to be a fuzzy search and remove multiple spaces and it didn't work then it would be a bug.

**Comment by DavidPesticcio** [comment] 2024-05-19 10:08
IMHO, ignoring multiple white-space and trimming white-space when performing searches is de facto - not exclusive to fuzzy matching.
