### ISSUE TITLE
[Enhancement]: Series cover

### ISSUE THREAD

**Issue by sveinbjornpalsson** [advplyr/audiobookshelf#2540] opened 2024-01-21 12:54 UTC
### Describe the feature/enhancement

How it is:
A series currently shows one of the book covers in the series. 

What to add:
It would be nice to be able to set a specific cover for the series itself. Not to replace individual covers, just to show when you're browsing with 'collapse series" on.

Why?
some of my series are quite episodic, so their individual covers aren't great.

**Comment by nichwall** [comment] 2024-01-21 15:10
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1086

I think this could be reconsidered as part of when main/sub series are implemented (related https://github.com/advplyr/audiobookshelf/issues/870 and https://github.com/advplyr/audiobookshelf/issues/2092), but not exactly sure how it would be implemented right now.

**Comment by advplyr** [comment] 2024-01-21 19:08
Duplicate of #1086

**Closed by advplyr** 2024-01-21 19:08 UTC
Labels: enhancement
