### ISSUE TITLE
[Enhancement]: Dismiss scanning library notification box

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2180] opened 2023-10-04 14:43 UTC
### Describe the feature/enhancement

I'm trying to access my filters while at the same time scanning a library.  There's no way to dismiss the library scanning notification except to cancel it and it obscures the filter/search dropdowns.

**Comment by advplyr** [comment] 2023-10-04 15:05
Duplicate of #1279

**Closed by advplyr** 2023-10-04 15:05 UTC
Labels: enhancement
