### ISSUE TITLE
[Enhancement]: Merge author names into one author: Tolkien, J.R.R. Tolkien, J. R. R. Tolkien, John Ronald Reuel....etc.

### ISSUE THREAD

**Issue by zzyzx-dc** [advplyr/audiobookshelf#3467] opened 2024-09-28 16:49 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

My instance of ABS is pulling author data from both the folder on disk and the metadata embedded in tags, so I'm wrestling with multiple versions of single author names. It is a bit of a chore to open each book and change the author name to attempt to merge them all into one. 

In a Plex music library, you can select multiple artists and simply click 'merge' - then edit the final lone artist entry how you wish. Furthermore on future music library scans, versions of the author name are automatically merged to the single artist entry.

Alternatively, would there be some way to scan and auto-merge authors into one entry?

Thanks. I apologize if this is a duplicate request - I did not find another one like it after searching.

### Why would this be helpful?

Removing multiple versions of one author in the library tab.

### Future Implementation (Screenshot)

n/a

### Audiobookshelf Server Version

v2.10.1

**Comment by nichwall** [comment] 2024-09-28 17:35
Duplicate of https://github.com/advplyr/audiobookshelf/issues/908

**Comment by ZLoth** [comment] 2024-09-28 19:26
If you rename J.R.R. Tolkien to J. R. R. Tolkien, then the books will be merged to J. R. R. Tolkien.

**Comment by advplyr** [comment] 2024-09-28 19:32
You should use the authors page to rename instead of going into each book manually.

**Closed by advplyr** 2024-09-28 19:32 UTC
Labels: enhancement
