### ISSUE TITLE
[Enhancement]: sortalbum tag support

### ISSUE THREAD

**Issue by scapix** [advplyr/audiobookshelf#1761] opened 2023-05-07 20:33 UTC
### Describe the feature/enhancement

Adding support for sortalbum tag will allow for custom audiobook sorting, allows to have books from series to be in sequence in books view without collapsing series.

**Comment by advplyr** [comment] 2023-09-17 13:25
Duplicate of #1074

**Closed by advplyr** 2023-09-17 13:25 UTC
Labels: enhancement
