### ISSUE TITLE
[Enhancement]: Make the search case-insensitive

### ISSUE THREAD

**Issue by ra3ggi** [advplyr/audiobookshelf#3192] opened 2024-07-23 08:42 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Make the search case-insensitive

### Why would this be helpful?

Easy to search

### Future Implementation (Screenshot)

Make the search case-insensitive

### Audiobookshelf Server Version

v2.11.0

**Comment by advplyr** [comment] 2024-07-23 13:25
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2260

**Closed by advplyr** 2024-07-23 13:25 UTC
Labels: enhancement
