### ISSUE TITLE
[Bug]: Submitting Match changes crashes audiobookshelf. Possibly only for one author. 

### ISSUE THREAD

**Issue by Johnt5818** [advplyr/audiobookshelf#2084] opened 2023-09-12 16:44 UTC
### Describe the issue

I am trying to grab the Metadata for the  Galaxy's Edge Series. Every time I go to submit the Match update, it crashes and I have to restart it. This is happening for all of the Jason Anspach books that I have. 
I have just recently started setting up audiobookshelf and this is the only author that I am having this problem with. I do have Jason Anspach properly matched up in the author's section. 

Here is what I am seeing in the logs:
-------------------------------------------------------------------------------------------------------------------------------------------
[2023-09-12 16:19:24] INFO: === Starting Server ===
[2023-09-12 16:19:24] INFO: [Server] Init v2.4.1
[2023-09-12 16:19:24] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
[2023-09-12 16:19:24] INFO: [Database] Db connection was successful
[2023-09-12 16:19:25] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
[2023-09-12 16:19:25] INFO: [BackupManager] 0 Backups Found
[2023-09-12 16:19:25] INFO: [BackupManager] Auto Backups are disabled
[2023-09-12 16:19:25] INFO: [LogManager] Init current daily log filename: 2023-09-12.txt
[2023-09-12 16:19:25] INFO: [Watcher] Initializing watcher for "Audiobooks".
[2023-09-12 16:19:25] INFO: Listening on port :80
[2023-09-12 16:19:25] INFO: [SocketAuthority] Socket Connected v8HiKri7cEPA9H5fAAAB
[2023-09-12 16:19:25] INFO: [SocketAuthority] Socket Connected fOdJL9AB5QaqgCG9AAAD
[2023-09-12 16:19:28] INFO: [Watcher] "Audiobooks" Ready
[2023-09-12 16:19:29] INFO: [SocketAuthority] Socket Connected EpwVuN5mGCTbo42_AAAF
[2023-09-12 16:20:43] INFO: [CoverManager] Downloaded libraryItem cover "/audiobooks/Jason Anspach/Galaxy's Edge/Tin Man - A Galaxy's Edge Prequel/cover.jpg" from url "https://m.media-amazon.com/images/I/813WqAvNR5L.jpg" for "Tin Man - A Galaxy's Edge Prequel"
[2023-09-12 16:20:43] INFO: [LibraryItem] Library item "74cbddae-37de-40d1-b144-21cf1e908c39" updated
[2023-09-12 16:20:43] WARN: [ApiRouter] Author id "new-512" does not exist (ApiRouter.js:558)
[2023-09-12 16:20:43] WARN: [ApiRouter] Author id "new-1251" does not exist (ApiRouter.js:558)
[2023-09-12 16:20:43] WARN: [ApiRouter] Series id "new-5141" does not exist (ApiRouter.js:595)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error
    at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.select (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Function.findAll (/node_modules/sequelize/lib/model.js:1140:21)
    at async Function.findOne (/node_modules/sequelize/lib/model.js:1240:12)
    at async Function.getOldByNameAndLibrary (/server/models/Series.js:106:21)
    at async ApiRouter.createAuthorsAndSeriesForItemUpdate (/server/routers/ApiRouter.js:600:30) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: near "s": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Galaxy's Edge Series' COLLATE NOCASE AND `series`.`libraryId` = '1100413a-554b-4b35-b3c7-3f171ac1b110') LIMIT 1;"
  },
  original: [Error: SQLITE_ERROR: near "s": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Galaxy's Edge Series' COLLATE NOCASE AND `series`.`libraryId` = '1100413a-554b-4b35-b3c7-3f171ac1b110') LIMIT 1;"
  },
  sql: "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Galaxy's Edge Series' COLLATE NOCASE AND `series`.`libraryId` = '1100413a-554b-4b35-b3c7-3f171ac1b110') LIMIT 1;",
  parameters: {}
}

### Steps to reproduce the issue

1. Go to the Galaxy's Edge Series by Jason Anspach
2. Open up the edit option on one of the books. (In the log I submitted it was for "Tin Man") 
3. Select the Match Tab and set the following options
 - Provider: Audible.com
 - Search Title or ASIN: Tin Man - Galaxy's Edge Prequel
 - Author: Jason Anspach
4. Select the only option
5. Go to the bottom and select Submit.
6. I do get the following notifications
 - Item Cover Updated
 - Failed to Update Item Details

Things I have tried to get around it.
- Multibale diffent books by Jason Anspach. all with the same issue.
- trying to only select particular options to update at a time. I didn't try all the combinations but quite a few.
- Deleting the metadata.json file that gets created in the book folder. It does get recreated

### Audiobookshelf version

v2.4.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-09-12 16:46
Duplicate of #2070

**Comment by advplyr** [comment] 2023-09-12 16:47
This is already fixed for the next update. Has to do with the apostrophe in the series name

**Closed by advplyr** 2023-09-12 16:46 UTC
Labels: bug
