### ISSUE TITLE
[Bug]: upload issues

### ISSUE THREAD

**Issue by nathanapples** [advplyr/audiobookshelf#3733] opened 2024-12-19 04:14 UTC
### What happened?

When I attempt to upload a book format that already has a different format of the same book in the library, a toast message appears stating: Filepath "/[path]/[author]/[book]" already exists on server

### What did you expect to happen?

I expected the book to be added as another format option to the original upload.

### Steps to reproduce the issue

1. Pick a book you already have in a library (e.g. mp3)
2. upload a different format of the same book (e.g. epub)

### Audiobookshelf version

v2.17.5

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

**Comment by nichwall** [comment] 2024-12-19 04:27
Multiple audio formats for the same book are not supported. https://github.com/advplyr/audiobookshelf/issues/2315

Uploading an ebook file to an existing audiobook: https://github.com/advplyr/audiobookshelf/issues/1894

**Comment by advplyr** [comment] 2024-12-19 21:05
Duplicate of #2315 and #1894

**Closed by advplyr** 2024-12-19 21:05 UTC
Labels: bug
