### ISSUE TITLE
Certain Folder Structures "hide" audiobooks from Scanner.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#29] opened 2021-09-09 02:03 UTC
There are 4 books in this particular collection (Dennis Taylor's Bobiverse Series). 

They are in the folders like this:
![image](https://user-images.githubusercontent.com/25695143/132606709-9e3ace3c-c8a8-43b9-94cc-0fd57a423d91.png)

Notice the three .m4b files and a folder.

In AudioBookShelf, the only thing detected by the scan were the contents of that last folder
![image](https://user-images.githubusercontent.com/25695143/132609715-4c813542-6871-44dc-b2ee-425346c5939d.png)

View from ABS:
![image](https://user-images.githubusercontent.com/25695143/132609958-c3d84ae4-b8a3-435f-aee5-064f816cbaff.png)

**Comment by advplyr** [comment] 2021-09-11 01:17
There were some major flaws in the scanner when it came to nested paths, so I had to rewrite it again. I'm calling it scanner version 3.

#31 I explained the difference with scanner v3 in a discussion. It should resolve the case you mentioned.

There is another downside though, which I point out in the second example of the discussion post. There are some workarounds that can be added later to make that better.

I really appreciate your help with testing all these features and your suggestions, you've played a significant part in taking this project out of pre-release, so thank you!

**Comment by Budlyte** [comment] 2021-09-16 04:17
I'm mainly posting so I can get an updated when v3 is released, because I now had the opposite happen, Book 1 in the series folder was discovered and everything else was ignored. And until we can get Series tokens for file naming in Readarr, messes like this are going to be common.  :(

![image](https://user-images.githubusercontent.com/4451365/133548522-b3ea3fe7-fc38-4d8a-a8b9-0df2418f21f6.png)

**Comment by advplyr** [comment] 2021-09-16 11:33
Scanner v3 is released already. In your picture all of those Book audio files should be detected by the scanner.
Are the audio files being ignored or what is happening?

**Comment by Budlyte** [comment] 2021-09-16 12:39
It had only detected Book 1 - Off To Be The Wizard in that folder.  So I went back and fixed the mess that Readarr had made of the folder, deleted the book from Audiobookshelf, and did a rescan.  This time it detected all the files but piled them under Book 1.

Here's the folder structure I have used throughout my collection, which the scanner did well with until I deleted a book and re-scanned.

`Author/Series Name/Series Name - Book X - Title/ Series Name - Book X - Title.ext`
![image](https://user-images.githubusercontent.com/4451365/133609729-e1968d55-a23c-4ac6-8c2a-8b43ea196c38.png)

![image](https://user-images.githubusercontent.com/4451365/133610153-6ad26846-de39-4bd9-bdbc-0be9ed090f06.png)

Result this time.
![image](https://user-images.githubusercontent.com/4451365/133610199-bffc51bf-e34b-45f2-a509-f0710986c7eb.png)


In looking for others in the same situation I found the Kid Sensation directory that hadn't been detected at all. There were two stray books sitting in the Author folder (At the same level as the Series folders), and once I reorganized them to the correct subfolders the scanner now picked them all up.

**Comment by Budlyte** [comment] 2021-09-16 22:02
Here's another one.

Looks like it was caused by an image I had for the series.  I removed it and the series sorted properly now.
![image](https://user-images.githubusercontent.com/4451365/133691349-94d14e42-aa0e-4aae-ae56-de3c4c51764f.png)

Each folder containing the book and a cover image.
![image](https://user-images.githubusercontent.com/4451365/133691395-b2dfed84-03ad-47aa-856c-e90d78ad13c2.png)


But for some reason the sorter grabbed Book 2 and matched the others under it.
![image](https://user-images.githubusercontent.com/4451365/133691463-50997f62-777a-4deb-a96c-5440572a4d2e.png)

**Comment by advplyr** [comment] 2021-09-17 01:34
So the scanner is detecting them, but it is not getting the order correct. If you press "Manage Tracks" there is a column for the track number detected from the metadata, and the track number that the scanner was able to extract from the filename.
The scanner prefers to use the metadata, but will fallback to the filename.

Can you share a screenshot of the manage tracks page?

**Comment by Budlyte** [comment] 2021-09-17 02:03
Removing the cover.jpg image in the series directory already fixed it.

They're not tracks out of order, those are all separate books getting treated as tracks under one book.

Looks like the sorter is finding the first instance of a file and treating everything below that file as a track to the files level.

**Comment by advplyr** [comment] 2021-09-17 03:46
Oh, right. That is the use-case I pointed out in the [discussion](https://github.com/advplyr/audiobookshelf/discussions/31#discussion-3566106). That should be fixed to only look for audio files when building the file structure.

**Comment by advplyr** [comment] 2021-09-17 23:50
In `v1.1.12` the scanner now ignores non-audio files that are not in the audiobook directory. So an image inside the series directory will no longer throw off the scanner.
I think that should close this one.

**Closed by advplyr** 2021-09-17 23:50 UTC
