### ISSUE TITLE
[Bug]: Import fails to ffprobe or create metadata for audiobooks with whitespace in the target directory/book name on CIFS NAS share

### ISSUE THREAD

**Issue by deddc23efb** [advplyr/audiobookshelf#2511] opened 2024-01-13 17:34 UTC
### Describe the issue

Importing books that have spaces in the name fail to be imported and no metadata is created.  Forcing a scan doesn't fix it and errors are shown in the logs.   Renaming the directory in CLI to have NO whitespace and rerunning the scan succeeds.
LOG Excerpt:

2024-01-13 17:14:47.515 ERROR [Utils] Failed to get ino for path /audiobooks/Neal Asher/Polity/The Engineer ReConditioned Error: ENOENT: no such file or directory, stat '/audiobooks/Neal Asher/Polity/The Engineer ReConditioned'
2024-01-13 17:14:47.529 ERROR [fileUtils] Recurse files error Error: ENOENT: no such file or directory, scandir '/audiobooks/Neal Asher/Polity/The Engineer ReConditioned/'
2024-01-13 17:14:47.529 ERROR [fileUtils] Failed to getFileTimestampsWithIno Error: ENOENT: no such file or directory, stat '/audiobooks/Neal Asher/Polity/The Engineer ReConditioned'
2024-01-13 17:15:13.135 INFO [Audnexus] Searching for author "https://api.audnex.us/authors?name=the%20engineer%20reconditioned"
2024-01-13 17:15:13.141 INFO [Audnexus] Searching for author "https://api.audnex.us/authors?name=neal%20asher"
2024-01-13 17:15:38.749 INFO Uploading 1 files to /audiobooks/Neal Asher/Polity/The Engineer ReConditioned
2024-01-13 17:15:47.223 ERROR [AudioFileScanner] Invalid data found when processing input : "/audiobooks/Neal Asher/Polity/The Engineer ReConditioned/The Engineer ReConditioned.m4b"
2024-01-13 17:17:22.254 INFO [LibraryScanner] Starting library scan 77c4c8d5-e158-4a4a-8f1c-d0b91ed53ce1 for audiobooks
2024-01-13 17:17:25.713 ERROR [LibraryScanner] Library scan 77c4c8d5-e158-4a4a-8f1c-d0b91ed53ce1 completed in 0:03.0 | 0 Added | 0 Updated | 0 Missing
2024-01-13 17:17:26.159 INFO [LibraryController] Scan complete

Renaming the book directory to "Engineer"  and rerunning the scan succeeds with no errors in the log.

### Steps to reproduce the issue

1. Import book with spaces in Title, notice it doesn't appear in the bookshelf
2. The issue doesn't always happen, for example importing "The Skinner" had no issues.  Repeatedly attempting to import "The Engineer ReConditioned" failed over and over - perhaps its multiple spaces or maybe the camel case title.

### Audiobookshelf version

2.7.1   UPDATED

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2024-01-13 18:00
It's most likely a coincidence that removing the space fixed the issue for you. Can you double check the audiobookshelf version you are running because 4.7.1 is not a valid version.

When you are importing a book are you doing this with the uploader in the web client or in your file system directly?

**Comment by deddc23efb** [comment] 2024-01-13 19:33
Sorry - fingerpokin problem - version is 2.7.1

**Comment by advplyr** [comment] 2024-02-28 00:03
This is an issue with CIFS not persisting inode values. Same as #2509

**Comment by advplyr** [comment] 2024-02-28 00:03
Duplicate of #2509

**Closed by advplyr** 2024-02-28 00:03 UTC
Labels: bug, waiting, unable to reproduce
