### ISSUE TITLE
[Bug]: Inconsistency between numbers of titles displayed in Series view verses Collection view

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3483] opened 2024-10-04 14:43 UTC
### What happened?

One thing that I've noticed is that the series view can display up to ten titles while the collections view only displays two titles. This is inconsistant.

### What did you expect to happen?

Series view and collections view show display the same number of titles. 

### Steps to reproduce the issue

No steps to replicate. Here are screenshots:

Series view:
![image](https://github.com/user-attachments/assets/64d3f956-a4f6-436d-8e4d-fcaba8c90821)

Collections view:
![image](https://github.com/user-attachments/assets/2c0fe594-b8e1-484d-8ffd-121d07bf1a32)

![image](https://github.com/user-attachments/assets/9fd5c414-c256-4771-a052-8106dc9e9895)

### Audiobookshelf version

v2.13.4

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
No logs.
```

**Comment by advplyr** [comment] 2024-10-04 22:13
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3482

**Comment by advplyr** [comment] 2024-10-04 22:14
Not sure what the difference is

**Closed by advplyr** 2024-10-04 22:13 UTC
Labels: bug

**Comment by ZLoth** [comment] 2024-10-04 23:36
> Duplicate of #3482

Not a duplicate. Enhancement #3482 asks that Playlists follow the same cover scheme as Collections and Series. This one covers the inconsistency between the number of covers displayed between Series and Collections. 

> Not sure what the difference is

In my examples, I use two series that have at least ten books, in this case, _Car Talk_ (15 Titles) and _NPR Driveway Moments_ (12 Titles). The behavior is as expected... the first ten covers are being displayed. 

The second example is from a Collection I set up which has 16 titles. Following the example from series, the first ten covers should be displayed, but instead, only the first two covers are being displayed. This is inconsistent with how series are being displayed. 

If I could, I would set up a control from the admin interface to control the maximum number of covers used from 3 to 10. I personally would like the first eight covers displayed.

**Comment by advplyr** [comment] 2024-10-05 00:34
Collections show the first 2 covers intentionally. I think you're confused in that series and collections are displayed the same but they aren't.
I took #3482 to be an enhancement request to make series, collections and playlists use the same format
