### ISSUE TITLE
[Enhancement]: Native custom branding

### ISSUE THREAD

**Issue by DonQuinleone** [advplyr/audiobookshelf#2771] opened 2024-03-19 20:11 UTC
### Describe the feature/enhancement

Of course, we can easily customise branding ourselves by modifying the source and building the Docker image ourselves. But, it would be really nice if this were natively possible.

Could the option to specify a custom application name, logo and favicon be added? Obviously keep the linkback to ABS in the footer so you're being credited! I refer to ABS by a different name with our users, and having this be consistent with that name would be superb.

### Proposed Change

Add three extra configurable options in **Settings** (/config):

* Application Display Name (text box)
* Logo Image (upload)
* Favicon Image (upload)

The values displayed would then be updated dynamically accordingly.

**Comment by advplyr** [comment] 2024-03-31 20:46
Duplicate of #1102

**Comment by advplyr** [comment] 2024-03-31 20:47
This is unlikely to be added especially the favicon and logo but you can add that to #1102 it'll stay open

**Closed by advplyr** 2024-03-31 20:46 UTC
Labels: enhancement
