### ISSUE TITLE
[Enhancement]: add user settings to customize the main page

### ISSUE THREAD

**Issue by lkshunter** [advplyr/audiobookshelf#3458] opened 2024-09-26 08:32 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be nice if the categories shown on the home page such as Recently Added, Recent Series, Discover, Listen Again and Newest Authors were not mandatory. Also, something like a "Favorites List" or "Listen Later" collection that can be displayed would be handy.

### Why would this be helpful?

I host my instance of Audiobookshelf for my family and friends. Experience and feedback show that my users don't use most of the categories displayed. They prefer to browse through all the books to find something they want to listen to. If they find something but are in another book, they can't remember it for the future. Sure, they could create a collection, but most users don't think of that right away. Also, a button that puts a book directly into the standard favorites collection would be much more user-friendly.

### Future Implementation (Screenshot)

![Screenshot 2024-09-26 100457](https://github.com/user-attachments/assets/3604d59a-59ae-4606-9c65-6ec31aded24b)

### Audiobookshelf Server Version

2.13.4

**Comment by nichwall** [comment] 2024-09-26 13:34
Custom shelves are duplicate of https://github.com/advplyr/audiobookshelf/issues/1273

**Closed** 2024-09-28 21:07 UTC
Labels: enhancement
