### ISSUE TITLE
[Enhancement]: Really hope to add the function to skip the intro and outro of audiobooks.

### ISSUE THREAD

**Issue by xyswordzoro** [advplyr/audiobookshelf#2761] opened 2024-03-18 08:37 UTC
### Describe the feature/enhancement

Many audiobook intros contain advertisements, etc. I hope to be able to manually set to skip intros. Thank you very much.

**Comment by nichwall** [comment] 2024-03-18 13:55
Delicate of https://github.com/advplyr/audiobookshelf/issues/2203

**Comment by advplyr** [comment] 2024-03-18 18:40
Duplicate of #2203

**Closed by advplyr** 2024-03-18 18:40 UTC
Labels: enhancement
