### ISSUE TITLE
[Enhancement]: Flag for abridged / unabridged

### ISSUE THREAD

**Issue by skronenwerth** [advplyr/audiobookshelf#1588] opened 2023-03-07 13:59 UTC
### Describe the feature/enhancement

It would be great if you could specify whether the audiobook is abridged or unabridged. I'm thinking of a flag like there already is one for explicit content.

**Comment by advplyr** [comment] 2023-03-07 14:17
Duplicate of #1408

**Closed by advplyr** 2023-03-07 14:17 UTC
Labels: enhancement
