### ISSUE TITLE
[Enhancement]: Enable hyperlink within description text

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2621] opened 2024-02-16 16:12 UTC
### Describe the feature/enhancement

It woukd be very helpful to be able to insert a Hyperlink into Description.
Like this:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/b24cf428-8909-4b09-9b6a-28979ceabe83)

I updated the content of the related author-Record like this:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/95b8b226-a169-49eb-8306-98f3df2aa456)
But within WebGui  no hyperlink appears
Or am i wrong with my Content?

**Comment by nichwall** [comment] 2024-02-16 18:48
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1820

**Comment by advplyr** [comment] 2024-02-16 20:23
Duplicate of #1820

**Closed by advplyr** 2024-02-16 20:23 UTC
Labels: enhancement
