### ISSUE TITLE
Add tooltip/hover text for book titles in library view (for all books, or only when display is truncated)

### ISSUE THREAD

**Issue by methosinhiding** [advplyr/audiobookshelf#2459] opened 2023-12-27 00:35 UTC
When viewing books in the library view, it would be great to be able to see the full name of a long-titled book without having to open its specific page. 
![image](https://github.com/advplyr/audiobookshelf-app/assets/146374353/011c1043-b815-481f-ab00-bdd6888930ee)

When hovering the mouse over the title of a book item in library view, show a tooltip/hover-text of the full book name.
It may make sense to only display the requested tooltip/hover text if the book currently being moused over is actually truncated, but it would be understandable if that is burdensome to determine.

**Comment by nichwall** [comment] 2023-12-28 15:16
Duplicate of #2451

**Comment by advplyr** [comment] 2023-12-28 15:23
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2451

**Comment by advplyr** [comment] 2023-12-28 15:24
Didn't even notice it was opened again, thanks!

**Closed by advplyr** 2023-12-28 15:23 UTC
Labels: enhancement
