### ISSUE TITLE
[Enhancement]: Better handling of new podcast episodes (waiting list; inbox; episodes)

### ISSUE THREAD

**Issue by update-freak** [advplyr/audiobookshelf#1757] opened 2023-05-06 18:16 UTC
### Describe the feature/enhancement

Hi developer,

I think the handling of new released podcast episodes could be improved.
Currently there is only the "Latest Epidsodes"-list which include the manually downloaded episodes which are not listened or the automatic downloaded ones (all new podcasts without preselecting the interesting podcasts).

A solution could be like that (see screenshot):
![Screenshot_20230506_195341_AntennaPod](https://user-images.githubusercontent.com/40196995/236639662-bd7d213d-7f1a-42b9-aa6d-6ad9376949e7.jpg)

**Posteingang (inbox)**: list of all new episodes. Here the interesting podcasts could be selected for the download. If selected for download the item disappears and this episode is moved to Warteschlage (waiting list). If some episodes in the inbox are not relevant to listen (not interesting) they could be removed from inbox. There is also an option to delete all items from the inbox.

**Warteliste (waiting list)**: list of all the podcasts which are downloaded and selected from the inbox. These episodes are interesting to listen.

**Episoden (episodes)**: list of all episodes regardless if they are in the waiting list or inbox or not. Use case: If you marked all items in the inbox as read (= no entries), so you could add episodes to Warteschlange (wait list) wich this overview.

I think which such an approach it could be easier select interesting podcasts and have then in a list to listen.

**Comment by advplyr** [comment] 2023-06-10 13:39
Is this the same as #1477?

**Comment by update-freak** [comment] 2023-06-10 14:28
As I unterstand in https://github.com/advplyr/audiobookshelf/issues/1477 the goal is to have smart playlists (e.g. list every unfinished episode from podcast X and podcast Y).
I have a similar idea, but I think it would be good to have only a selection of the unplayed/unfinished episodes in that list (reason: I did want to listen to every episode of a podcast X, so only the interesting ones). So this represents then the "Warteliste (wainting) list" in my comment above. Maybe it would be good when you have a look at the Android App AntennaPod (the screenshot in my first comment is from that app) to see the functionality.

**Comment by update-freak** [comment] 2023-07-17 18:36
any news on that? I have put my proposal into a graphic:

![diagram_1](https://github.com/advplyr/audiobookshelf/assets/40196995/06f2d576-96f6-4a9d-8b6a-9c0663252f05)

**Comment by update-freak** [comment] 2023-07-21 16:21
Other possibility would be to have a sync function with AntennaPod.

From the App [Podfetch](https://github.com/SamTV12345/PodFetch/issues/219) I found the comment: [GPodder](https://gpodder.github.io/docs/user-manual.html) has a very extensive API documentation how their endpoints are named and configured. So I just went into implementing the required API endpoints. So PodFetch becomes with this option essentially GPodder.net.
-> which means sync between PodFetch <-> AntennaPod.

Would be great if we could have also a sync function of the playing state (how long did we hear to the podcast yet) for audiobookshelf. This was already mentioned here: https://github.com/advplyr/audiobookshelf/issues/1414

**Comment by update-freak** [comment] 2023-11-12 09:53
Should this also be closed as https://github.com/advplyr/audiobookshelf/issues/2074 is closed as unplaned?

**Comment by nichwall** [comment] 2023-11-12 14:19
> Should this also be closed as https://github.com/advplyr/audiobookshelf/issues/2074 is closed as unplaned?

It was closed as a duplicate of this one. There isn't a "close as duplicate" option.

**Comment by advplyr** [comment] 2023-11-12 14:48
I've read through this a few times now and I'm still confused about what is actually being requested here. 

> As I unterstand in #1477 the goal is to have smart playlists (e.g. list every unfinished episode from podcast X and podcast Y).
> I have a similar idea, but I think it would be good to have only a selection of the unplayed/unfinished episodes in that list (reason: I did want to listen to every episode of a podcast X, so only the interesting ones). So this represents then the "Warteliste (wainting) list" in my comment above.

This is the same as #1477. You are just adding that you want more control over the smart playlist. 



> any news on that? I have put my proposal into a graphic:
> 
> ![diagram_1](https://user-images.githubusercontent.com/40196995/254037391-06f2d576-96f6-4a9d-8b6a-9c0663252f05.png)

This graphic is where things get confusing. Abs is not a traditional podcast app in the sense that you are listening to episodes from an RSS feed hosted on some other server. The podcast episodes already have to be on your server. At this time we don't want to build a full traditional podcast app on top of everything else.

**Comment by advplyr** [comment] 2023-11-12 14:48
Duplicate of #1477

**Closed by advplyr** 2023-11-12 14:48 UTC
Labels: enhancement, waiting

**Comment by nichwall** [comment] 2023-11-12 14:51
Oh whoops. Mixed up which issues were referencing each other.
