### ISSUE TITLE
[Enhancement]: Relocate the blue info box.

### ISSUE THREAD

**Issue by nanofred** [advplyr/audiobookshelf#1942] opened 2023-07-19 13:27 UTC
### Describe the feature/enhancement

Can the blue info box pop-up that blocks the menu be moved to the space between the search bar and the settings? 
It's empty when there are no books selected and when there are. Where it currently is blocks both menus on the library page. When you are matching a large library it's there for a while.

**Comment by advplyr** [comment] 2023-07-19 16:01
Duplicate of #1279

**Closed by advplyr** 2023-07-19 16:01 UTC
Labels: enhancement
