### ISSUE TITLE
[Enhancement]: Add Support for Book Title Sort Field

### ISSUE THREAD

**Issue by torchyboy** [advplyr/audiobookshelf#1368] opened 2023-01-05 18:26 UTC
### Describe the feature/enhancement

The default sort order on some titles may not be desirable and therefore need the capability to explicitly set the title sort for those titles. This could be for titles that start with specials characters (e.g., Spanish punctuation) or numerals (where it's desired that the title be sorted by the numeral's spelled out name).

This feature is supported by calibre:title_sort, so it could be added to what's extracted from the .opf

**Comment by advplyr** [comment] 2023-01-05 18:32
Duplicate of #1074

**Closed by advplyr** 2023-01-05 18:32 UTC
Labels: enhancement
