### ISSUE TITLE
[Enhancement]: Download Ebook Option in iOS/Android App

### ISSUE THREAD

**Issue by mslmn** [advplyr/audiobookshelf#2424] opened 2023-12-19 10:49 UTC
### Describe the feature/enhancement

A feature to download associated ebooks already exists in the web client. 

It would be nice if that was extended to the app version so that one could directly download an ebook from the Audiobookshelf app to read within their own reader app of choice e.g Play Books, iBooks etc.

**Comment by advplyr** [comment] 2023-12-19 14:13
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/860

**Closed by advplyr** 2023-12-19 14:13 UTC
Labels: enhancement

**Comment by advplyr** [comment] 2023-12-19 14:35
The abs web client also works on mobile as a solution for now
