### ISSUE TITLE
[Enhancement]: variation in execution minute of hourly podcast RSS refreshes

### ISSUE THREAD

**Issue by xo9agq46a8k** [advplyr/audiobookshelf#2827] opened 2024-04-05 22:16 UTC
### Describe the feature/enhancement

OPML imported podcasts appear to default to refreshing at the top of each hour, which in my case (500+ feeds) resulted in ABS web UI becoming super slugish for the first few of minutes of each hour. How about having them default to refreshing based on the createdAt minute? Such that a createAt timestamp in the podcasts table of "2024-04-05 13:43:22.012 +00:00" would receive an autoDownloadSchedule value of "43 * * * *"? Or perhaps just a random minute value to maximally spread out the tasks of feed refreshing and podcast downloading?

To solve the problem in my specific case I executed the following SQL against the database to randomize the minute of each refresh. I had it generate a number between 8 and 58 assuming those were perhaps the minutes of lightest load on the network/servers. Thanks for reading my feature request!
`UPDATE podcasts SET autoDownloadSchedule = (8 + (ABS(RANDOM()) % 51)) || ' * * * *';`

**Comment by nichwall** [comment] 2024-04-05 23:03
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2312

**Comment by advplyr** [comment] 2024-04-06 21:55
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2312

**Closed by advplyr** 2024-04-06 21:55 UTC
Labels: enhancement
