### ISSUE TITLE
direct one toogle filter for audio book VS text book in library views

### ISSUE THREAD

**Issue by allnamesaregoneallready** [advplyr/audiobookshelf#2402] opened 2023-12-09 18:35 UTC
### Describe the feature/enhancement

show only audio books and show only text book

**Comment by nichwall** [comment] 2023-12-09 19:27
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1889

**Comment by advplyr** [comment] 2023-12-09 19:28
Duplicate of #1889

**Closed by advplyr** 2023-12-09 19:28 UTC
Labels: enhancement
