### ISSUE TITLE
[Bug]: Playlist / Collections for Ebooks

### ISSUE THREAD

**Issue by oOStroudyOo** [advplyr/audiobookshelf#1908] opened 2023-07-15 23:00 UTC
### Describe the issue

Hello,
I noticed that for Ebooks on the web browser there's no option to add a book to a playlist, only a Collection.
However on the Android app, there's no option to add a book to a collection, only a playlist.

This obviously makes it awkward to segregate books into piles if the user uses both platforms.

Thank you.

### Steps to reproduce the issue

1. Click on a book
2. Click Options (3 dots).

### Audiobookshelf version

v2.3.0 (Web browser) & v0.9.65-beta (Android)

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment] 2023-07-16 13:54
Support for collections in the mobile app has been requested here https://github.com/advplyr/audiobookshelf-app/issues/207

I don't think ebooks should included in playlists because this is for audio content only. Once collections are supported in the mobile app I think this will meet your needs.

**Comment by advplyr** [comment] 2023-07-16 13:54
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/207

**Closed by advplyr** 2023-07-16 13:54 UTC
Labels: bug
