### ISSUE TITLE
Search: search over all metadata combined

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#2340] opened 2023-11-22 10:18 UTC
### Describe the feature/enhancement

Related
- #1401

## Case Now:
Searching for "{book title} {author}" does not match the book.
Searching for "{book title}" or "{author}" individually results in a match.

## Expected:
Match a book when search terms relating to multiple metadata fields are used.

## additional context
 - this would be lower on the hierarchy of search results and combining it with fuzzy search would make searching an excellent feature.

 - I am thinking this could be implemented by combing all metadata into one single field and doing a search over that instead of each field individually.

**Comment by advplyr** [comment] 2023-11-22 13:32
Which search are you referring to?

**Comment by Dr-Blank** [comment] 2023-11-23 09:05
sorry, i should have been more precise

`/library/[id]/search?q=atomic%20habits`
vs.
`/library/[id]/search?q=atomic%20habits%20james%20clear`

these urls and also the global search bar

![image](https://github.com/advplyr/audiobookshelf/assets/64108942/e4fae679-2a64-4687-9804-118cd1c0ab5e)

![image](https://github.com/advplyr/audiobookshelf/assets/64108942/f1dc9487-c5d0-4c2e-b77e-49921c3e9014)

**Comment by iconoclasthero** [comment] 2023-11-25 13:12
Is there some way to easily make the search fuzzier?

**Comment by advplyr** [comment] 2023-11-25 16:27
Duplicate of #1401

**Closed by advplyr** 2023-11-25 16:27 UTC
Labels: enhancement

**Comment by advplyr** [comment] 2023-11-25 16:29
This is basically the same thing as fuzzy search. @mikiher has been doing work on this for matching https://github.com/advplyr/audiobookshelf/pull/2186

**Comment by Dr-Blank** [comment] 2023-11-25 18:58
> Duplicate of #1401
> This is basically the same thing as fuzzy search.

I did link #1401 in my issue because it would be needed to implement this. What that issue did not cover was inclusion of other metadata fields for searching, it mentioned only searching in book title, hence this issue to support searching in title as well as authors/genres/etc. altogether.

I feel #2186 covers both, this and fuzzy matching.
