### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Terminal-Grasshopper** [advplyr/audiobookshelf#3702] opened 2024-12-10 18:36 UTC
### What happened?

When in the library, every time a book or audiobook is deleted, the file does get deleted but the site refreshes and takes me to the top of the page

### What did you expect to happen?

the user should stay at the same place when scrolling down and deleting a book/audiobook

### Steps to reproduce the issue

1. scroll down and delete a book/audiobook

### Audiobookshelf version

v2.17.5

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (list in "Additional Notes" box)

### Additional Notes

ABS is hosted on docker (truenas) and the issue is present on all clients OS

**Comment by advplyr** [comment] 2024-12-10 18:38
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1956

**Closed by advplyr** 2024-12-10 18:38 UTC
Labels: bug
