### ISSUE TITLE
[Enhancement]: Volume Boost

### ISSUE THREAD

**Issue by scgf** [advplyr/audiobookshelf#2254] opened 2023-10-27 06:26 UTC
### Describe the feature/enhancement

Please incorporate a volume boost like some other apps do - Smart Audiobook Reader and Pocket Casts, for example. When listening to audiobooks through bone conducting headphones the maximum volume isn't quite loud enough when cycling in traffic or downhill in the wind.

**Comment by advplyr** [comment] 2023-10-27 08:58
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/195

**Closed by advplyr** 2023-10-27 08:58 UTC
Labels: enhancement
