### ISSUE TITLE
[Enhancement]: "Delete from file system" should _always_ be unchecked

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3056] opened 2024-06-09 20:52 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

I know that I deleted a book several days ago from my instance of AudioBookShelf, but I was surprised when I tested the delete function again and saw this:

![image](https://github.com/advplyr/audiobookshelf/assets/6700159/f024067c-4764-4d40-b9f1-610a17407720)

The "Delete from File system" was still checked. It should be unchecked.

### Why would this be helpful?

It is possible that implementation of AudioBookShelf is on a *nix system or a Docker container running on a *nix system. Under my experience, once you delete something under *nix, it is gone forever with little hope of recovery. Thus, anything in regards to permanent deletions from the file system should not be "sticky" from previous usages. (Although a good backup also comes in handy).

### Future Implementation (Screenshot)

Not applicable

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

https://github.com/advplyr/audiobookshelf/assets/6700159/bae56a40-4a54-48a4-9ef2-586a8a899300

**Comment by advplyr** [comment] 2024-06-09 21:00
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1689

**Closed by advplyr** 2024-06-09 21:00 UTC
Labels: enhancement
