### ISSUE TITLE
[Enhancement]: Import Audible Chapter names only in M4B

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#630] opened 2022-05-24 19:50 UTC
### Describe the feature/enhancement

#435 allows updating chapter metadata in ABS which is great. But some of the M4Bs I've tested it with have chapter marks a few seconds different from where audnexus reports them. But the number of chapters and relative lengths/positions are very close (+/- a few seconds). But this small difference is very noticeable when skipping chapters. Playback can sometimes start in the middle of a chapter name.

I propose allowing importing of chapter names, with an option to leave chapter start times unmodified. I imagine this is not an issue with split chapter MP3s since the files will not be modified.

**Comment by advplyr** [comment] 2022-09-25 22:23
This is now a duplicate of #991 will use that as the main thread for this. #927 is also relevant

**Closed by advplyr** 2022-09-25 22:23 UTC
Labels: enhancement
