### ISSUE TITLE
[Bug]: Store metadata with item doesn't work

### ISSUE THREAD

**Issue by zrwd01** [advplyr/audiobookshelf#2032] opened 2023-08-26 09:30 UTC
### Describe the issue

Store metadata with item doesn't work

### Steps to reproduce the issue

1. always

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-08-26 21:32
Duplicate of #1952

**Closed by advplyr** 2023-08-26 21:32 UTC
Labels: bug
