### ISSUE TITLE
[Enhancement]: Please expand the ability to add data for book authors...

### ISSUE THREAD

**Issue by Otnak** [advplyr/audiobookshelf#3041] opened 2024-06-04 08:15 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be nice to expand the ability to add an author’s photo to a library of books via a folder on disk. You can add a button to the author editing window "Upload picture".
But you can also add this capability to the Library Folder Scanner by first configuring it to do the following. All photos of the authors should be in the root of the Author's folder.
In the same directory you can put desc.txt files describing the biography of the authors.

### Why would this be helpful?

It is known that you can only add a photo of the author via a URL; This is not always convenient when, for example, I saved a photo in a folder and forgot where I got this photo from. For example, I create another or a new library of books and search the Internet for photographs when I have them on my disk. This way we will speed up the process of creating content with authors.
Today this is done only by hand. What if you need to reinstall the entire library again? Or I will put the library on another computer with different paths to the library files, etc. This will be very smart in every way.

### Future Implementation (Screenshot)

The idea to create such functionality came from the example of working with books and book covers. There it is automated as much as possible.

### Audiobookshelf Server Version

v2.10.1

**Comment by nichwall** [comment] 2024-06-04 13:23
Related to https://github.com/advplyr/audiobookshelf/issues/618
https://github.com/advplyr/audiobookshelf/issues/498#issue-1213723511

**Comment by advplyr** [comment] 2024-06-04 14:47
Duplicate of #618 and #498

**Closed by advplyr** 2024-06-04 14:47 UTC
Labels: enhancement
