### ISSUE TITLE
[Bug]: audiobookshelf didn't laucn on arm64 with 2.12

### ISSUE THREAD

**Issue by Machou** [advplyr/audiobookshelf#3234] opened 2024-08-05 08:35 UTC
### What happened?

I update as usual audiobookshelf, via docker compose, here is the file :

```yaml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
      - TZ=Europe/Paris
    ports:
      - 13378:80
    volumes:
      - /home/freebox/docker/audiobookshelf/audiobooks:/audiobooks
      - /home/freebox/docker/audiobookshelf/config:/config
      - /home/freebox/docker/audiobookshelf/podcasts:/podcasts
      - /home/freebox/docker/audiobookshelf/metadata:/metadata
    restart: unless-stopped
```

### What did you expect to happen?

n/a

### Steps to reproduce the issue

1. Update on ARM64 with docker-compose on arm64

### Audiobookshelf version

2.12

### How are you running audiobookshelf?

Docker

I have try with my config and without, new repertory with fresh install; on 2 différents Debian.

### What OS is your Audiobookshelf server hosted from?

Linux Debian

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:11.066] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:11.071] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:11.072] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:11.073] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:11.074] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:11.292] INFO: [BinaryManager] ffmpeg not found or version too old
audiobookshelf  | [2024-08-05 10:31:11.395] INFO: [BinaryManager] ffprobe not found or version too old
audiobookshelf  | [2024-08-05 10:31:11.397] INFO: [BinaryManager] unicode not found or version too old
audiobookshelf  | [2024-08-05 10:31:11.401] INFO: [BinaryManager] Installing binaries: ffmpeg, ffprobe, unicode
audiobookshelf  | [2024-08-05 10:31:19.742] INFO: [BinaryManager] Binaries installed to /
audiobookshelf  | [2024-08-05 10:31:19.880] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:19.881] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:19.999] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:19.999] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:20.000] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:20.001] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:20.002] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:20.120] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:20.122] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:20.129] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:20.132] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:23.378] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:23.383] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:23.384] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:23.385] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:23.386] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:23.561] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:23.562] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:23.670] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:23.671] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:23.672] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:23.673] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:23.675] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:23.778] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:23.780] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:23.787] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:23.791] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:26.989] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:26.995] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:26.996] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:26.997] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:26.998] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:27.191] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:27.193] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:27.303] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:27.304] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:27.305] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:27.306] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:27.308] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:27.419] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:27.422] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:27.428] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:27.431] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:30.711] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:30.716] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:30.717] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:30.718] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:30.719] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:30.900] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:30.902] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:31.007] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:31.008] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:31.009] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:31.010] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:31.012] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:31.124] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:31.126] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:31.132] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:31.136] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:34.823] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:34.828] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:34.830] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:34.830] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:34.832] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:35.015] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:35.017] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:35.123] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:35.125] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:35.126] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:35.126] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:35.129] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:35.229] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:35.231] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:35.237] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:35.240] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:39.814] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:39.819] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:39.820] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:39.821] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:39.822] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:40.018] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:40.020] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:40.128] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:40.129] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:40.130] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:40.131] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:40.133] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:40.245] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:40.247] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:40.254] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:40.257] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
audiobookshelf  | Config /config /metadata
audiobookshelf  | [2024-08-05 10:31:46.352] INFO: === Starting Server ===
audiobookshelf  | [2024-08-05 10:31:46.357] INFO: [Server] Init v2.12.0
audiobookshelf  | [2024-08-05 10:31:46.358] INFO: [Server] Node.js Version: v20.16.0
audiobookshelf  | [2024-08-05 10:31:46.358] INFO: [Server] Platform: linux
audiobookshelf  | [2024-08-05 10:31:46.360] INFO: [Server] Arch: arm64
audiobookshelf  | [2024-08-05 10:31:46.531] INFO: [BinaryManager] Found valid binary ffmpeg at /ffmpeg
audiobookshelf  | [2024-08-05 10:31:46.533] INFO: [BinaryManager] Updating process.env.FFMPEG_PATH
audiobookshelf  | [2024-08-05 10:31:46.639] INFO: [BinaryManager] Found valid binary ffprobe at /ffprobe
audiobookshelf  | [2024-08-05 10:31:46.641] INFO: [BinaryManager] Updating process.env.FFPROBE_PATH
audiobookshelf  | [2024-08-05 10:31:46.642] INFO: [BinaryManager] Found valid binary unicode at /unicode.so
audiobookshelf  | [2024-08-05 10:31:46.643] INFO: [BinaryManager] Updating process.env.SQLEAN_UNICODE_PATH
audiobookshelf  | [2024-08-05 10:31:46.645] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf  | [2024-08-05 10:31:46.754] INFO: [Database] Loading extension /unicode.so
audiobookshelf  | [2024-08-05 10:31:46.756] ERROR: [Database] Failed to load extension /unicode.so [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:236)
audiobookshelf  | [2024-08-05 10:31:46.765] ERROR: [Database] Failed to connect to db [Error: SQLITE_ERROR: Error loading shared library /unicode.so.so: No such file or directory] {
audiobookshelf  |   errno: 1,
audiobookshelf  |   code: 'SQLITE_ERROR'
audiobookshelf  | } (Database.js:214)
audiobookshelf  | [2024-08-05 10:31:46.769] FATAL: [Server] Unhandled rejection: Error: Database connection failed, promise: Promise {
audiobookshelf  |   <rejected> Error: Database connection failed
audiobookshelf  |       at Database.init (/server/Database.js:168:13)
audiobookshelf  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
audiobookshelf  |       at async Server.init (/server/Server.js:116:5)
audiobookshelf  |       at async Server.start (/server/Server.js:179:5)
audiobookshelf  | } (Server.js:171)
```

**Comment by mikiher** [comment] 2024-08-05 09:04
This is a duplicate of #3231. Please see discussion there.

**Closed** 2024-08-05 11:30 UTC
Labels: bug
