### ISSUE TITLE
[Bug]: Downloading new Podcast episodes fails with EAI_AGAIN

### ISSUE THREAD

**Issue by Arragon5xpwm** [advplyr/audiobookshelf#3484] opened 2024-10-05 10:30 UTC
### What happened?

New Podcast episodes fail to download for some podcast

### What did you expect to happen?

Episodes being downloaded

### Steps to reproduce the issue

1. Start search for new episodes to downlo

### Audiobookshelf version

2.13.4

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```
[2024-10-05 12:22:41.260] ERROR: [ffmpegHelpers] Failed to download podcast episode with url "https://plus.lagedernation.org/podlove/file/2676/s/feed/c/5iflglzc40mqf7efhg0awp8/LdN399-plus-aoihnwhw.mp3" AxiosError: getaddrinfo EAI_AGAIN cdn.lagedernation.org
```

### Additional Notes

I suspected an error with DNS setup first but the host can resolve the URL without problems
```
dig cdn.lagedernation.org

; <<>> DiG 9.16.42 <<>> cdn.lagedernation.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50387
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cdn.lagedernation.org.         IN      A

;; ANSWER SECTION:
cdn.lagedernation.org.  300     IN      CNAME   cdn.kicks-apps.com.
cdn.kicks-apps.com.     0       IN      A       139.162.176.53

;; Query time: 62 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Sat Oct 05 12:24:51 CEST 2024
;; MSG SIZE  rcvd: 98
```

Then I started the container with `--dns 1.1.1.1` but the error is still the same.

**Comment by nichwall** [comment] 2024-10-05 12:57
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3346

**Closed** 2024-10-05 13:02 UTC
Labels: bug
