### ISSUE TITLE
[Enhancement]: Send to Kindle & multiple Files (Editions/Formats/narators) for Audiobooks and E-books

### ISSUE THREAD

**Issue by GamerClassN7** [advplyr/audiobookshelf#2463] opened 2023-12-29 11:35 UTC
### Describe the feature/enhancement

Hello,
Just recently started using Audiobookshelf for my E-Books, and it is almost perfect for my needs :) but i stood upon few thinks i wanted to ask if they are considered somewhere down the road. Also would be nice to see some updates regarding the E-Books part. Since only other alternative i know of is Calibre Web which is really not so user friendly and hard to understand. on other hand would be perfect to have Audiobooks and E-Books in one place (service)

Would be possible to implement feature to send e-books file to your kindle ? and alsou setting to autosend it to kindle ?
![image](https://github.com/advplyr/audiobookshelf/assets/22167469/a2185dea-fb18-448e-92ad-5b26a16fe99d)
and maybe add button upload another format to this section because it is really hard to upload multiple files of same e-book to not be discovered as another e-book. Also this feature would be appreciated also for Audiobooks, Since at least for me (i am probable not alone) have same audiobook in multiple Edition from different narrators and languages.
Or at least add button when 2 and more books are selected to merge.
![image](https://github.com/advplyr/audiobookshelf/assets/22167469/d4ce44dc-9bd8-42bc-b48e-d576bca51b7a)

**Comment by nichwall** [comment] 2023-12-29 13:40
Send to Kindle is already supported. You can add devices in the Email page of the settings (top section is where the email sends from, can use a normal Gmail or other email provider, you don't need to self host it).

Multiple formats is duplicate of https://github.com/advplyr/audiobookshelf/issues/2315 and probably another that I can't find at the moment.

**Comment by GamerClassN7** [comment] 2023-12-29 14:48
> Send to Kindle is already supported. You can add devices in the Email page of the settings (top section is where the email sends from, can use a normal Gmail or other email provider, you don't need to self host it).
> 
> Multiple formats is duplicate of #2315 and probably another that I can't find at the moment.

Thank you for first part found it nice :)

in deed second part is also similar to my sugestion

**Comment by advplyr** [comment] 2023-12-29 21:43
Duplicate of #2315

**Closed by advplyr** 2023-12-29 21:43 UTC
Labels: enhancement
