### ISSUE TITLE
[Bug]: Continue Series Shelf only shows next book in series when you are listening to a book

### ISSUE THREAD

**Issue by endangered-maritime-walrus** [advplyr/audiobookshelf#545] opened 2022-05-01 15:35 UTC
### Describe the issue

What happened:
Next book in series not staying on Continue Series Shelf unless the previous book in the series is being listened to. After completion of book, the series is removed from the Continue Series Shelf.

Expected behavior:
If a series is not complete, the next book not started should show on the Continue Series Shelf, regardless if there is a book in that series currently being listened to.

### Steps to reproduce the issue

1. Start a book in a series, next book in series shows in Continue Series Shelf.
2. Finish book, when it is removed from Continue Listening Shelf, the next book in the series is also removed from Continue Series Shelf. It should stay on Continue Series Shelf indefinitely.

### Audiobookshelf version

v2.0.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-05-03 00:36
Fixed in [v2.0.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.9)

**Closed by advplyr** 2022-05-03 00:36 UTC
Labels: bug

**Comment by MidnightSnowleopard** [comment] 2022-05-03 14:19
Doesn't seem to have changed the behavior for me with v2.0.9

**Comment by advplyr** [comment] 2022-05-03 21:44
I just tested and it works for me. There are a few caveats like it will if you have multiple books with progress/finished it will take the one with the largest sequence.
Can you give a step by step on how I can reproduce?

**Comment by MidnightSnowleopard** [comment] 2022-05-03 22:45
1. Have books in a series.
2. Start playing the first book.
3. Pause the book
4. Check front page where "Continue Series" section and see the next book in the series is listed

Tested with multiple series, already started and other ones.

One thing I do have to ask is this something that's in the "edge" image or one tagged for v2.0.9?

**Comment by advplyr** [comment] 2022-05-03 23:07
What you described is the intended behavior though. What were you expecting?

**Comment by MidnightSnowleopard** [comment] 2022-05-03 23:21
Apologies, misread the ticket.  Thought the intended behavior was only to show the next in the series once the current one in the series has been completed.
