### ISSUE TITLE
[Bug]: Windows Tray App Doesn't see update

### ISSUE THREAD

**Issue by MarauderSeeker** [advplyr/audiobookshelf#3507] opened 2024-10-13 00:30 UTC
### What happened?

The Windows Tray doesn't recognize there is an update past v2.14.0, when clicking Check for Updates. It says "No Updates Available"

### What did you expect to happen?

It to say/install the update shown on the dashboard for v2.15.0

### Steps to reproduce the issue

1. Right click tray icon (running v2.14.0)
2. select Check for Updates

### Audiobookshelf version

V2.14.0

### How are you running audiobookshelf?

Windows Tray App

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

**Comment by nichwall** [comment] 2024-10-13 00:41
Looks like https://github.com/mikiher/audiobookshelf-windows built the new version, but doesn't have a release available

**Comment by mikiher** [comment] 2024-10-13 11:08
The [new release](https://github.com/mikiher/audiobookshelf-windows/releases/tag/v2.15.0) is there is marked as latest. I installed  it on my own desktop using `Check for Updates`.

I'm not able to reproduce this. Is anyone else seeing this behavior?

**Comment by mikiher** [comment] 2024-10-13 11:29
Perhaps you had some temporary network issue that caused the tray app not to be able to connect to Github? Does anything show up in the Tray app log? You can usually find it in `%localappdata%\AudiobookshelfTray\logfile.txt`

**Comment by mikiher** [comment] 2024-10-13 11:50
Ah, the bug report is from 11 hours ago. The new release wasn't published yet then. Try again now and it should work.

(_Some explanation for those interested_: while the Windows app is still in Beta, the release draft is built automatically but is not automatically published, to allow me to perform some last sanity checks on it before I publish. All the last releases were built without any issues, so I will soon probably also start publishing the release automatically. This will significantly decrease the time between a new Audiobookshelf server and the corresponding Audiobookshelf-Windows release, from hours to minutes)

**Comment by advplyr** [comment] 2024-10-13 12:53
Thanks this is just a case of the windows version wasn't released yet.

**Closed by advplyr** 2024-10-13 12:53 UTC
Labels: bug
