### ISSUE TITLE
[Bug]: Search does not show all items!

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2842] opened 2024-04-11 10:26 UTC
### Describe the issue

When I search for "Fluch"(1) I got this result:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/6d212804-df06-4b70-ac05-e6b921c77121)

But the new added item (3) is missing in the search result (2).
When I do it by using ODBC directly on table books I got this:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/b5247a3e-f59b-4eb7-ba34-b340dd580778)

The best solution will be to filter within Register "Library" as you do when search for a author and then click on it.
It would be also good to have it on Series ( and Authors)
This Bug is related to #2719 where the performance -problem is solved.
The app shows me 5 results but also there book (2) is missing!

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.8.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2024-04-12 21:58
The search is not just searching on the title. If those items have "fluch" anywhere in the subtitle, description, etc. then it will be shown in there.

The dropdown shows 3 results for each category. If you press enter it will show more.

**Comment by Gru0810** [comment] 2024-04-13 07:43
Ok, but this works only within WebApp and unfortunately not in the mobile App. 
Now I see more. But when I type "Kommissar" and press "ENTER" within the WebApp I got this:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/54ba5600-597e-48dc-bb37-38c54159bdae)
A direkt ODBC-Call on books returns me 63 matching Books:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/73ea41ca-ba23-43d0-84b0-9a97642e4867)
From my point of view it would be the best way to show all these 63 books within the register "Library" as you do when searching for a Author like "Arthur Conan Doyle" which return 52 books:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/502c9864-160e-41b8-8a55-44a00b0c53c8)
perhaps you can open then FIlter-Elemnt for freetext:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/5cfc1013-9ce6-4c9e-bd94-7ccb925cf9b4)
and for matched within Series you can perhaps add a filter-element within register "Series"?

**Comment by advplyr** [comment] 2024-04-13 16:46
This was discussed in https://github.com/advplyr/audiobookshelf/issues/923 and is planned

**Comment by advplyr** [comment] 2024-04-13 16:47
Duplicate of https://github.com/advplyr/audiobookshelf/issues/923

**Closed by advplyr** 2024-04-13 16:47 UTC
Labels: bug, waiting

**Comment by Gru0810** [comment] 2024-04-18 06:14
Great news that it's planned (by https://github.com/advplyr/audiobookshelf/issues/923) ! AND ONCE AGAIN:  SUPER MEGA COOL app and Mediaserver you and all the other developer have built. I and my Users love it!
