### ISSUE TITLE
[Bug]: new issues since 2.3.0

### ISSUE THREAD

**Issue by rweatherly** [advplyr/audiobookshelf#1913] opened 2023-07-16 12:55 UTC
### Describe the issue

A number of issues started showing up since upgrading to 2.3.0 via docker using docker compose
1.) meta data is now missing author and series info (rest is still there)
2.) on android app, for a series that I repopulated (after bug 1), the series page shows a 404 time error in the mobile app
3.) all settings reset to default
4.) all user sessions and listening history gone

### Steps to reproduce the issue

Variety of issues, but are after simple docker compose down / pull / up

### Audiobookshelf version

2.3.0

### How are you running audiobookshelf?

Docker

**Comment by SilentStray** [comment] 2023-07-16 13:00
From this listed items, I can concure that I am experiencing issue #2 only.

**Comment by advplyr** [comment] 2023-07-16 13:25
@rweatherly Did you happen to get the server logs when the container started up? This is the only way for me to see what happened for your migration

**Comment by rweatherly** [comment] 2023-07-16 13:28
i stopped the container (backup the folder now), cause I was going to try and revert to the previous version. I'm not sure if the container logs are still there, do they persist after stopping ?

**Comment by advplyr** [comment] 2023-07-16 13:29
@rweatherly I think it depends on whether you removed the container or not. And how you are using docker. In the terminal you would do `docker ps -a` then get the ID of the container. Then `docker logs <container id>`

**Comment by advplyr** [comment] 2023-07-16 13:30
You may want to wait until I put out a patch because I did identify a few things to fix. I'm going to try to get the patch out today

**Comment by advplyr** [comment] 2023-07-16 13:31
If you want to revert to the previous version you will need to extract the old database files in `/config/oldDb.zip` and delete the `/config/absdatabase.sqlite` file. That will put you right back to where you were until the patch

**Comment by rweatherly** [comment] 2023-07-16 13:34
i use docker-compose, and that removed the container so docker ps -a doesn't list anything.
ok thanks, i was worried about the DB thing cause i saw something about a new one, i was thinking about going to my duplicati backup from the previous night, but that would make it easier.. 
i have a couple of other people looking to listen to books this morning so i want to try and get something that is working for them. i will make sure to save logs if i run through the upgrade process again

**Comment by advplyr** [comment] 2023-07-16 13:38
@SilentStray Your issue was reported in #1914 and I just fixed it for the upcoming patch

**Comment by BDaddyG** [comment] 2023-07-16 14:02
I also have issues after the upgrade.  Mine are related to issue #1 meta data.  "Series", "Collections", and "Authors" are all missing.

I was able to get the following partial logs (attached file)

[AudioBookShelf_v2.3.0_upgrade_errors_redacted.txt](https://github.com/advplyr/audiobookshelf/files/12064197/AudioBookShelf_v2.3.0_upgrade_errors_redacted.txt)

Docker running on unRAID

**Comment by captainnapalm** [comment] 2023-07-16 16:41
these are my errors. app won't start:

```
audiobookshelf    | Config /config /metadata
audiobookshelf    | [2023-07-16 16:39:44] INFO: === Starting Server ===
audiobookshelf    | [2023-07-16 16:39:44] INFO: [Server] Init v2.3.0
audiobookshelf    | [2023-07-16 16:39:44] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf    | [2023-07-16 16:39:44] INFO: [Database] Db connection was successful
audiobookshelf    | [2023-07-16 16:39:44] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
audiobookshelf    | 
audiobookshelf    | <--- Last few GCs --->
audiobookshelf    | 
audiobookshelf    | [1:0x7f3eb60ba3f0]     9718 ms: Mark-sweep (reduce) 4093.3 (4129.3) -> 4093.3 (4129.3) MB, 23.8 / 0.0 ms  (+ 4.4 ms in 1 steps since start of marking, biggest step 4.4 ms, walltime since start of marking 31 ms) (average mu = 0.916, current mu = 0.334) all[1:0x7f3eb60ba3f0]     9752 ms: Mark-sweep (reduce) 4094.3 (4130.3) -> 4094.3 (4130.3) MB, 31.3 / 0.0 ms  (average mu = 0.828, current mu = 0.062) allocation failure scavenge might not succeed
audiobookshelf    | 
audiobookshelf    | 
audiobookshelf    | <--- JS stacktrace --->
audiobookshelf    | 
audiobookshelf    | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
audiobookshelf exited with code 139
```

**Comment by Gauva1n** [comment] 2023-07-16 16:46
Running into the same issue after upgrading to v2.3.0 with the "JavaScript heap out of memory" error when the container is trying to start. Running Ubuntu Server 22.04.2 LTS, Docker version 20.10.21.

**Comment by rweatherly** [comment] 2023-07-16 16:53
mine started, just had those listed issues.. here are my versions, for reference
OS: Raspberry Pi OS / Debian 11 (latest version all patches applied)
Docker version: 24.0.4, build 3713ee1
Compose version: 1.29.2

**Comment by Gauva1n** [comment] 2023-07-16 17:14
Tried rolling back to the backup I took of the latest version, and it started at least. But looks like the db is borked. Totally blank collections and getting the following from the application logs:

> 2023-07-16 17:06:00
> 
> ERROR
> 
> JWT Verify Token Failed JsonWebTokenError: invalid signature
> 
> 2023-07-16 17:06:00
> 
> ERROR
> 
> Verify Token User Not Found

**Comment by Hallo951** [comment] 2023-07-16 17:16
I am running Abs on Ubuntu Linux and have just updated to the latest version. I also had everything reset to default and my audiobook library no longer exists. I have now started to re-read everything :(

**Comment by Gauva1n** [comment] 2023-07-16 17:24
Okay, got everything back again running v2.2.23. Read the release notes and saw there was a database upgrade in this version. After restoring the backup I took with `docker load` and updating my docker-compose file to use the local backup image, I found in an oldDb.zip archive in my /config folder. Moved all of the following folders in /config to a junk folder of /new-db-broken:

authors
collections
feeds
libraries
libraryItems
playlists
series
sessions
settings
users

Made sure to stop the container, unzipped the oldDb.zip folder into the /config folder, restarted the container and now we're good back at v2.2.23 at least with all my items.

**Comment by rweatherly** [comment] 2023-07-16 17:25
> Tried rolling back to the backup I took of the latest version, and it started at least. But looks like the db is borked. Totally blank collections and getting the following from the application logs:
> 
> > 2023-07-16 17:06:00
> > ERROR
> > JWT Verify Token Failed JsonWebTokenError: invalid signature
> > 2023-07-16 17:06:00
> > ERROR
> > Verify Token User Not Found
> 
> Edit: Meh, actually I cat'd out the database and I can see everything OK in there. App's just not connecting to it anymore.

if you were using the build in backup/restore, I believe you have to manually restore the old db, as this version introduced a new SQLlite db.. it should have been backed up to oldDb.zip.. 
I couldn't find it and used a duplicate restore, but [advplyr](https://github.com/advplyr) mentioned a few posts back that it should have been backed up and stored

**Comment by Gauva1n** [comment] 2023-07-16 17:27
Yep, think I posted my last comment about the same time you did. Manual database restore worked for me, going to keep it at v2.2.23 for now.

**Comment by Hallo951** [comment] 2023-07-16 21:11
Where can I find this oldDb.zip file for restoring the old library under Linux Ubuntu? I found the config and metadata folders under /usr/share/audiobookshelf but the oldDb.zip file is not there.... Can you help me?

**Comment by advplyr** [comment] 2023-07-16 21:14
I would suggest waiting for the patch I'm releasing shortly where I will put in instructions on what to do. Trying to revert and messing with other config files may cause more problems.

**Comment by Hallo951** [comment] 2023-07-16 21:25
Ok, then I'll wait. My current situation is that I have updated to version 2.3.0 and everything has been reset to standard. I thought that I would now restore the old state and then wait for your patch, but if you have a better solution, I'd rather wait...

**Comment by advplyr** [comment] 2023-07-16 21:26
The patch notes will include instructions for you to restore to your old state. No data was lost for you, it just didn't go into the new database properly.

**Comment by advplyr** [comment] 2023-07-16 22:16
The patch is released with instructions on the fix: https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.1

Basically you want to update, then stop the container, delete the `absdatabase.sqlite` file, then start the container. The database will be recreated from your old database.

**Comment by captainnapalm** [comment] 2023-07-16 22:21
I followed your instructions, and I'm still getting the JavaScript heap out of memory. Here's the end of the logs:

```
audiobookshelf    | 2023-07-16T22:19:57.424970832Z [2023-07-16 22:19:57] INFO: [oldDbFiles] Old db files have been zipped in /config/oldDb.zip. 111398425 total bytes
audiobookshelf    | 2023-07-16T22:19:57.439108711Z [2023-07-16 22:19:57] INFO: [dbMigration] Migration complete. Elapsed 29.97s
audiobookshelf    | 2023-07-16T22:20:05.014784717Z 
audiobookshelf    | 2023-07-16T22:20:05.014808302Z <--- Last few GCs --->
audiobookshelf    | 2023-07-16T22:20:05.014812660Z 
audiobookshelf    | 2023-07-16T22:20:05.014815626Z [1:0x7f55f45023f0]    40191 ms: Mark-sweep (reduce) 4093.8 (4130.0) -> 4093.8 (4130.0) MB, 16.5 / 0.0 ms  (+ 8.1 ms in 2 steps since start of marking, biggest step 8.1 ms, walltime since start of marking 29 ms) (average mu = 0.899, current mu = 0.334) all[1:0x7f55f45023f0]    40235 ms: Mark-sweep (reduce) 4094.7 (4130.9) -> 4094.7 (4131.2) MB, 42.5 / 0.0 ms  (average mu = 0.760, current mu = 0.029) allocation failure scavenge might not succeed
audiobookshelf    | 2023-07-16T22:20:05.014828630Z 
audiobookshelf    | 2023-07-16T22:20:05.014831105Z 
audiobookshelf    | 2023-07-16T22:20:05.014834211Z <--- JS stacktrace --->
audiobookshelf    | 2023-07-16T22:20:05.014836735Z 
audiobookshelf    | 2023-07-16T22:20:05.014839120Z FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by advplyr** [comment] 2023-07-16 22:23
@captainnapalm What is the size of the sqlite file?

**Comment by captainnapalm** [comment] 2023-07-16 22:25
> @captainnapalm What is the size of the sqlite file?

```
brendan@prometheus:/mnt/nvmetank/appdata/audiobookshelf$ ll
total 121867
drwxr-xr-x  4   99 users         6 Jul 16 16:19 .
drwxrwxrwx 54   99 users        55 Jul  5 13:59 ..
drwxr-xr-x  4   99 users         5 Mar  6  2022 audiobooks
drwxr-xr-x  8   99 users         8 Oct 27  2022 metadata
-rw-r--r--  1 root root   77881344 Jul 16 16:19 absdatabase.sqlite
-rw-r--r--  1 root root  111398425 Jul 16 16:19 oldDb.zip
```

**Comment by advplyr** [comment] 2023-07-16 22:30
What are you running Abs on? That shouldn't be very much memory to load that in.

To migrate back to v2.2.23 you can just unzip the `oldDb.zip`. For those where `oldDb.zip` isn't there you can just revert back. When upgrading in the future from v2.2.23 you will want to make sure `/config/absdatabase.sqlite` is deleted so it can be re-created.

I'll be looking into reducing the memory usage further tomorrow

**Comment by captainnapalm** [comment] 2023-07-16 22:35
Running in Ubuntu server 22.04, Docker 24.0.4, docker-compose 1.29.2, with 128GB RAM, Ryzen 9 5950X, etc.

**Comment by captainnapalm** [comment] 2023-07-16 22:40
Is this how /config/ should look after unzipping the oldDB.zip?

```
total 108392
drwxr-xr-x 14   99 users        15 Jul 16 16:38 .
drwxrwxrwx 54   99 users        55 Jul  5 13:59 ..
drwxr-xr-x  4   99 users         5 Mar  6  2022 audiobooks
drwxr-xr-x  4 root root          5 Jul 16 16:38 authors
drwxr-xr-x  4 root root          5 Jul 16 16:38 collections
drwxr-xr-x  4 root root          5 Jul 16 16:38 feeds
drwxr-xr-x  4 root root          5 Jul 16 16:38 libraries
drwxr-xr-x  4 root root          5 Jul 16 16:38 libraryItems
drwxr-xr-x  8   99 users         8 Oct 27  2022 metadata
drwxr-xr-x  4 root root          5 Jul 16 16:38 playlists
drwxr-xr-x  4 root root          5 Jul 16 16:38 series
drwxr-xr-x  4 root root          5 Jul 16 16:38 sessions
drwxr-xr-x  4 root root          5 Jul 16 16:38 settings
drwxr-xr-x  4 root root          5 Jul 16 16:38 users
-rw-r--r--  1 root root  111398425 Jul 16 16:19 oldDb.zip
```

**Comment by Gauva1n** [comment] 2023-07-17 00:45
Confirming that v2.3.1 is still failing for me as well with the same heap allocation limit error. Tried deleting the absdatabase.sqlite file as per instructions after updating but before launching. 

Successfully rolled back to v2.2.23 once more, the manual database reversion method is still working. Not sure if it's worth mentioning, but this time around after upgrading, all the directories and files in /config were deleted but nothing was recreated except for the new absdatabase.sqlite file. With v2.3.0 it at least recreated the contents of those files/folders. 

My instance of ABS is running on a small headless server, only 8GB of RAM but 5GB currently free. Ubuntu 22.04, Docker Compose version v2.19.1, Docker 20.10.21. My working absdatabase.sqlite file is 3.9 MB.

**Comment by roadkingvrod** [comment] 2023-07-17 03:48
It appears that after 2.3, it broke using a cifs share for the config folder....

**Comment by freakadings** [comment] 2023-07-17 05:27
From the above on my instance only 2.) occured, the patched fixed it for me. Thank you very much!

**Comment by Hallo951** [comment] 2023-07-17 07:53
I have now updated to the new version under Linux Ubuntu and followed your instructions, but I do not have this oldDb.zip file (see screenshot). What else can I do?

![Screenshot_20230717_094615_com brave browser](https://github.com/advplyr/audiobookshelf/assets/40667862/2e68dbef-99f6-43f9-a965-5b8352322ec1)

**Comment by warwolf** [comment] 2023-07-17 09:43
Im also experiencing bug 2, everything works fine in web interface tho but not on android app.

![Screenshot_20230717_113224_audiobookshelf](https://github.com/advplyr/audiobookshelf/assets/745677/3283af93-ad5d-4265-b3bd-1f3a91cfc25d)

This is Docker log when trying to access series:
`TypeError: Cannot read properties of undefined (reading 'checkCanAccessLibrary')
    at checkCanAccessLibraryItem (/server/objects/user/User.js:361:15)
    at Array.filter (<anonymous>)
    at ApiRouter.middleware (/server/controllers/SeriesController.js:73:49)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:284:15
    at param (/node_modules/express/lib/router/index.js:365:14)
    at param (/node_modules/express/lib/router/index.js:376:14)`

**Comment by skyzuma** [comment] 2023-07-17 10:12
try the latest server version / patch ... 2.3.1 ... its fixed ...

**Comment by warwolf** [comment] 2023-07-17 10:18
Yea sry about that, i was sure i did pull the new image but for some reason it was still 2.3.0.
Can confirm it works fine in 2.3.1

**Comment by Hallo951** [comment] 2023-07-17 11:19
Is it possible that this olddb.zip file is located in a different path under Linux ubuntu than in the Audiobookshelf folder? for me it simply does not exist....

**Comment by JakobTischler** [comment] 2023-07-17 17:00
> try the latest server version / patch ... 2.3.1 ... its fixed ...

FWIW, I still get the heap limit bug with 2.3.1.

**Comment by advplyr** [comment] 2023-07-17 23:40
Memory crash should be fixed in [v2.3.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.2)

Let me know how it goes

**Comment by captainnapalm** [comment] 2023-07-20 03:24
Can confirm, upgraded from 2.2.23 to 2.3.3 and all seems to be working as expected. Thanks @advplyr!

**Comment by captainnapalm** [comment] 2023-07-20 15:32
Nope, I spoke too soon. I am able to get a few hours of running, but I still run into the `Javascript heap out of memory` error. Container restarts with `unless-stopped` and it will run again for a few hours and then hit this same issue.

**Comment by advplyr** [comment] 2023-07-20 22:06
@captainnapalm I was sent 2 databases that had this issue which helped me to recreate the OOM crash and push up fixes for it. I'm not able to reproduce any crashes now on 2.3.3. If you or anyone on here still having that issue wants to send me a copy of your DB I'll see if I can reproduce it. Or if you can find some pattern for when the crash happens that would be helpful also.

**Comment by mattj415** [comment] 2023-07-20 22:15
I had the OOM error with 2.3.1 and rolled back. Didn't get a chance to try 2.3.2 but 2.3.3 fixes the issue for me! 
Thanks so much for this awesome project!

**Comment by roadkingvrod** [comment] 2023-07-20 22:30
In my case, I was running the config on a CIFS external share.  2.3.0 broke that with the DB error.  2.3.3 it seems to work great.

**Comment by captainnapalm** [comment] 2023-07-21 16:16
> @captainnapalm I was sent 2 databases that had this issue which helped me to recreate the OOM crash and push up fixes for it. I'm not able to reproduce any crashes now on 2.3.3. If you or anyone on here still having that issue wants to send me a copy of your DB I'll see if I can reproduce it. Or if you can find some pattern for when the crash happens that would be helpful also.

Where can I send my db? To your email dev@advplyr.com? I'm basically seeing the OOM error every 4 hours right now.

**Comment by advplyr** [comment] 2023-07-21 16:40
@captainnapalm Yeah you can send to that email or you can DM me in the Discord server. If you zip the sqlite file it should reduce the file size a lot.

**Closed** 2023-09-13 21:25 UTC
Labels: bug, waiting
