### ISSUE TITLE
[Enhancement]: Users should be allowed to add and manage ereader devices

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2992] opened 2024-05-19 01:30 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

 There should be two options added for ereaders:

- If the end user is given permission to manage their ereader devices 
- Allow the end user to add the name and email address of the ereader device

### Why would this be helpful?

As currently implemented and documented at https://www.audiobookshelf.org/guides/send_to_ereader#add-e-reader , "E-reader devices can only be added to ABS by an admin." This adds an unnecessary administrative burden for a task that should be self-service. (But, then again, knowing some end users)

### Future Implementation (Screenshot)

This would be an extension of the current ereader support in AudioBookShelf in that a end user can see the admin-added devices as well as add their own devices. 

### Audiobookshelf Server Version

2.9.0

### Current Implementation (Screenshot)

From Kavita:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/5283542b-a49d-4e96-be84-d04aa20ac4e2)

**Comment by nichwall** [comment] 2024-05-19 01:41
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1982

**Closed** 2024-05-20 15:15 UTC
Labels: enhancement
