### ISSUE TITLE
[Enhancement]: Show search book results on multiple lines

### ISSUE THREAD

**Issue by DDriggs00** [advplyr/audiobookshelf#2948] opened 2024-05-07 21:18 UTC
### Describe the feature/enhancement

Currently, when searching (using the search box at the top of the screen), the books returned from the search are collapsed onto a single line, which you must click through horizontally. Would it be possible to show the book results on multiple lines, in a more library-like format when there are more than a single row?

**Comment by advplyr** [comment] 2024-05-09 17:49
Duplicate of https://github.com/advplyr/audiobookshelf/issues/923

**Closed by advplyr** 2024-05-09 17:49 UTC
Labels: enhancement, sorting/filtering/searching

**Comment by advplyr** [comment] 2024-05-09 17:50
The original issue was for multiple rows. I updated it to add a "View all" link which would also be compatible on the home page
