### ISSUE TITLE
[Bug]: Auto download does not seems to work for podcast imported with OPML

### ISSUE THREAD

**Issue by TheBlusky** [advplyr/audiobookshelf#2160] opened 2023-09-29 12:55 UTC
### Describe the issue

When importing podcasts with an OPML, created podcasts aren't scheduled for auto download, even if the toggle was checked.

Below what's inside de sqlite database for those podcasts (is "autoDownloadScheduled" supposed to be null ?) :

![vivaldi_EgW9xdnwyW](https://github.com/advplyr/audiobookshelf/assets/441709/faff9ed9-335c-4d0c-bb57-de6bc65eb22f)

### Steps to reproduce the issue

1. Create a new ABS instance
2. Import an OPML file
3. Podcasts are shown as scheduled for auto download every hour
4. `CronManager` isn't start every hours 
5. Change any Podcast scheduling
6. New scheduling is taking into account for this podcast only

### Audiobookshelf version

v2.4.3

### How are you running audiobookshelf?

Docker

**Comment by TheBlusky** [comment] 2023-09-29 13:19
I got the same screen as you :

![vivaldi_FBFdtfEApB](https://github.com/advplyr/audiobookshelf/assets/441709/a0ac34a6-e8e8-4c4f-8028-db192472d7d2)

It was previously displayed as scheduled for 15:00, but `CronManager` hasn't fired (and I got log level at Debug)

Now displayed (as you can see) for 16:00

**Comment by advplyr** [comment] 2023-09-29 13:41
Yeah it looks like a bug. If auto scan is enabled that download schedule shouldn't be null. Just to confirm, you were able to get it working for a podcast by changing the schedule and changing it back? I would guess that sets the column correctly

**Comment by TheBlusky** [comment] 2023-09-29 13:46
You guessed correctly.

Switching one podcast to "Every day" :

![vivaldi_jKBTpzl5Zh](https://github.com/advplyr/audiobookshelf/assets/441709/5f435d52-45ea-4657-9092-26b1f05a52e7)

Re-switching to "Every hour" :

![vivaldi_WLeDzy8Kt1](https://github.com/advplyr/audiobookshelf/assets/441709/e671817f-9894-4e95-9d59-d5d05e812154)

**Comment by truthsword** [comment] 2023-09-29 21:43
Just started with podcasts a week ago, and I can confirm this. Updates are not happening.

If I use the manual "search" tool for each individual podcast, all the new episodes are found for downloading.

Looking forward to a fix. Thanks!

**Comment by advplyr** [comment] 2023-09-30 21:58
Fixed in [v2.4.4](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.4)

**Closed by advplyr** 2023-09-30 21:58 UTC
Labels: bug, awaiting release

**Comment by advplyr** [comment] 2023-09-30 21:59
This fix is for newly added podcasts. Existing podcasts will have to toggle the schedule to set that column correctly
