### ISSUE TITLE
[Enhancement]: See progress % when converting to m4b.

### ISSUE THREAD

**Issue by xAhlen** [advplyr/audiobookshelf#2651] opened 2024-02-23 07:21 UTC
### Describe the feature/enhancement

Hi
Would it be possible to add a progress bar or text with % how far the conversion has come?

**Comment by nichwall** [comment] 2024-02-23 13:34
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1986

**Closed** 2024-02-23 14:18 UTC
Labels: enhancement
