### ISSUE TITLE
[Enhancement]: 'Add all to playlist' option, instead of requiring users to add every episode of a 300-episode podcast manually one by one in order to play them...

### ISSUE THREAD

**Issue by nirurin** [advplyr/audiobookshelf#3039] opened 2024-06-03 18:54 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

At the moment, podcasts do not autoplay. When you get to the end of an episode it just stops, and you have to get your phone out and open up the app and find the next episode and play it. 
This is asinine, by the way, but it's already been well documented on here that everyone is waiting for this 'feature' to be implemented. 

The current only alternative is to add all the episodes of a podcast, to a playlist specific to that podcast... which basically just means duplicating what is already there, but ok whatever. 

However... you can't actually do this. There's no option (that I can find?) to add all the episodes of a podcast to a playlist. You can only do it one-by-one. Which for many podcasts with 100+/200+/300+ episodes, is a pain in the ass. 

I know this whole platform is still in beta and everything, but hopefully bare-bones-basic functionality like this gets priority over the other nice-to-have features. Currently listening to podcasts in the car with this app is actually dangerous, and relies on being able to -PARK THE CAR- in order to move to the next track. Which is.... yeh, no, what are you doing. 

The audiobook side of things has been so good the last few months, that I had expected podcasts to be equally as well thought out. I'm hoping it's just a really new feature that hasn't been playtested yet, cos so far it's been a real disappointment. 

### Why would this be helpful?

Well it would be user-friendly. And much less dangerous while driving. And not a terrible design. 

### Future Implementation (Screenshot)

Look at any podcast app. Or any app ever. Youtube also allows it. Basic functionality. 

### Audiobookshelf Server Version

2.10.1

### Current Implementation (Screenshot)

Podcasts.

**Comment by nichwall** [comment] 2024-06-03 23:17
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/416

**Comment by nirurin** [comment] 2024-06-04 00:40
> Duplicate of [advplyr/audiobookshelf-app#416](https://github.com/advplyr/audiobookshelf-app/issues/416)
> 
> Code contributions are welcome.

No it isn't? 

That report is for requesting that podcasts should auto play the next one in the queue, instead of stopping. 

My request is asking for the ability to add an entire podcast to a playlist with a single click. It's a completely different thing. 

Both of these things should exist. Not just one or the other.

**Comment by nichwall** [comment] 2024-06-04 01:01
Thanks, I copied the wrong issue link

**Comment by nirurin** [comment] 2024-06-04 01:06
Ahh makes more sense.

**Comment by advplyr** [comment] 2024-06-04 08:54
Is this regarding the mobile app or the web client?

**Comment by nirurin** [comment] 2024-06-04 11:30
Mobile app. The Web client does seem to autoplay, which is ... a janky
workaround for the short term. But the web player is missing too many
features to be a long term solution on mobile.

**Comment by advplyr** [comment] 2024-06-04 15:02
Bulk selecting episodes and adding to a playlist is a feature that can be added but I'm not sure that is what you are looking for here.

The web client has differentiated between a "queue" and a "playlist". The podcast implementation in the web client is lacking a feature right now to allow for setting the sort or play order of episodes so it is not complete and may seem confusing.

For example, if I click play on an episode that has unplayed episodes that are more recent then these unplayed episodes will show up in the queue.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/454ddd48-32a3-44b2-994b-1d3e13c5e7f6)

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/503a8b35-e709-4d73-b0c8-065fe57f5946)

For playlists and collections a queue is added in the player when pressing the play button at the top of the page.

The remaining issue with podcasts in the web client is to be able to set the episode order. When that feature is added I don't believe you will need to bulk add podcast episodes to a playlist.

I'm not sure if I'm explaining that well enough but this is similar to how youtube differentiates a playlist and a queue. This is the logic that I'm planning to build into the mobile apps the same way.

There is also this button in the web client that shows up when the player is open to add an item to the queue.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/a531209d-cb37-4454-a667-78e1106ffc29)

**Comment by advplyr** [comment] 2024-06-04 15:16
What I'm pointing out is that it depends on what you consider the "next" episode is. I'm assuming for your podcasts you want to listen to them from most recent to oldest?

**Comment by nirurin** [comment] 2024-06-04 15:25
No... do people do that?

I'd want to listen to them in order, which is from oldest to newest. I
don't know of any podcast that would be listened to in reverse order
(newest to oldest). They're episodic releases, they're even mostly labelled
"episode 1" "episode 2" etc.

**Comment by advplyr** [comment] 2024-06-04 15:37
Oh okay, so the web client behaves as you expect it in terms of the player queue.

So what you are looking for is https://github.com/advplyr/audiobookshelf-app/issues/416 which you already commented on and I had to remove so users didn't get misled.

As for adding an entire podcast to a playlist in a single click I don't see much benefit for this since a) the queue works as you expect in the web client and b) the queue isn't supported on the mobile apps yet so putting them in a playlist isn't going to autoplay like you are looking for.

> The current only alternative is to add all the episodes of a podcast, to a playlist specific to that podcast... which basically just means duplicating what is already there, but ok whatever.

This isn't an alternative?

**Comment by nirurin** [comment] 2024-06-04 15:43
Oh, I had assumed that the android app would play through a playlist
non-stop, instead of stopping after every episode. I didn't realise this
also counted as a queue (and so doesn't currently work). If that's the case
then no I guess playlists are also not a solution.

Playing from the Web browser does work as expected though, but running
media from the Web browser on a mobile device has a bunch of issues such as
battery drain and it also means I lose features such as the automatic sleep
timer etc. But it does work as a temporary workaround.

**Comment by advplyr** [comment] 2024-06-04 16:15
You may prefer opening up an RSS feed and putting that RSS feed into a full featured podcast client.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/f56d7d0b-865d-416e-984f-40188adfc28c)

Abs is a side project worked on in the free time of a few contributors that ask for no compensation. That feels necessary to mention after some of the comments you've made.

**Closed by advplyr** 2024-06-04 16:15 UTC
Labels: enhancement
