### ISSUE TITLE
[Bug]: Files with chinese characters become garbage after upload

### ISSUE THREAD

**Issue by andrewchen5678** [advplyr/audiobookshelf#1831] opened 2023-06-08 23:49 UTC
### Describe the issue

After uploading files with chinese characters, the characters become garbage instead of remaining as unicode characters:

### Steps to reproduce the issue

1. upload the file named "Radio Television Hong Kong - 有你同行 - 心的練習曲.m4b", and then the folder is named properly according to the title but not the file itself. 

2. upload a folder named "sop_heaven_season_1" with m4a files with chinese characters.

<img width="1168" alt="Screenshot 2023-06-08 at 4 42 20 PM" src="https://github.com/advplyr/audiobookshelf/assets/2096114/a18a772a-fa36-4b94-b7a1-00a4a7df9457">

### Audiobookshelf version

2.2.22

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-06-09 00:14
This is fixed for the next release already from #1816 and reported in #1815

**Comment by advplyr** [comment] 2023-06-09 00:14
Duplicate of #1815

**Closed by advplyr** 2023-06-09 00:14 UTC
Labels: bug
