### ISSUE TITLE
[Bug]: Podcast Max new episodes to download per check cannot be set to 0

### ISSUE THREAD

**Issue by einikisa** [advplyr/audiobookshelf#2680] opened 2024-02-27 21:28 UTC
### Describe the issue

The limit for max number of downloads for podcasts defaults at "3" and when changed to any other number even "0" it will revert back to "3" after moving to another tab.

### Steps to reproduce the issue

1. Reinstalled and updated application with same result. Tried a different podcast and same result.

### Audiobookshelf version

2.8.8

### How are you running audiobookshelf?

Debian/PPA

**Comment by nichwall** [comment] 2024-02-27 21:51
https://www.audiobookshelf.org/guides/podcasts

In general if you're wanting to download new podcasts automatically, you want to use the "Schedule" tab or the "Find Episodes" modal. This is expected behavior for that tab.

**Comment by einikisa** [comment] 2024-02-27 21:55
I have but I cant change the download maxes for either one. For example: The podcast I have in the library released 7 new episodes today but because I cant change the amounts different then 3, it only downloaded 3 of them. I would like to set both setting quantities to "0" for max.

**Comment by nichwall** [comment] 2024-02-27 22:00
So specifically on the "Schedule" tab the max number isn't being saved?
Yeah that should be persistent, there's been some confusion around the tab because people think the "Check and Download" tab is how they set up a schedule and see the fields don't get saved.

**Comment by einikisa** [comment] 2024-02-27 22:01
Yes sir that is correct. It is not being saved.

Thank you

**Comment by advplyr** [comment] 2024-02-27 22:12
Are you pressing the "Save" button after updating it?

**Comment by einikisa** [comment] 2024-02-27 22:21
Yes. I tried several different times. It saves the other setting but just
not those.

Thank you

**Comment by advplyr** [comment] 2024-02-27 22:30
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/8bf24385-4f70-4a6f-9544-3915f5245e8b)

Make sure you are doing this here.

Also, you reported that you are on Abs version 2.8.8 but I assume you mean 2.8.0?

**Comment by advplyr** [comment] 2024-02-27 22:32
From your original post it seems like you are trying to update this one. This one will not save.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/80a20bc0-2732-4c05-bccb-31c518db8be9)

**Comment by einikisa** [comment] 2024-02-27 22:36
Yes you are correct about the version. My apologies. Also, yes, that is
where it won’t save. Trying to save it to 0 but it won’t stay. Also the
other setting tab like that one as well.

Thank you

**Comment by advplyr** [comment] 2024-02-27 22:39
Okay I found it. This is specific to setting that value to 0

**Comment by einikisa** [comment] 2024-02-27 22:41
I also tested with trying other values but it was the same result. It went
back to 3.

**Comment by advplyr** [comment] 2024-03-16 23:05
Fixed in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)

**Closed by advplyr** 2024-03-16 23:05 UTC
Labels: bug, awaiting release
