### ISSUE TITLE
[Enhancement]: add ignore/exclude folder to library scan

### ISSUE THREAD

**Issue by adispi** [advplyr/audiobookshelf#2497] opened 2024-01-06 08:48 UTC
### Describe the feature/enhancement

please add an option to ignore a folder in the scan.
my issue:
synology has a subfolder for each folder named @eaDir which holds indexing information for synology file system.
every time synology updates the indexer, for examle defrag, all the files in those folders change, and the watcher or scanner see changes to all books in the library and scan them as if the book has change and since i have a big library can run for 1-2 days. not to mention it doubles my library files. 

thank you.
adi.

**Comment by nichwall** [comment] 2024-01-06 14:58
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1641

**Comment by advplyr** [comment] 2024-01-06 18:36
Duplicate of #1641

**Closed by advplyr** 2024-01-06 18:36 UTC
Labels: enhancement
