### ISSUE TITLE
[Enhancement]: Sort Series Numbers Numerically THEN Alphabetically

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#2808] opened 2024-04-01 19:53 UTC
### Describe the feature/enhancement

I have the Warriors (Warrior Cats) series, and have been including titles as [series#].[volume#]. eg 2.1, 2.2, 3.1.
I then added a one-off in the series, from a set called "Super Editions." So I added said book as "SE 1". 

However, doing so sorted "SE 1" at the front of the list, before "1.1". This is not how titles should be sorted. It should be numbers first, then letters. Please fix.

ABS v2.8.1; Docker

![image](https://github.com/advplyr/audiobookshelf/assets/12549803/af771ce5-c61e-418e-9a2c-7d2ce39ad12d)

**Comment by nichwall** [comment] 2024-04-01 21:00
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2281?

**Closed** 2024-04-01 21:36 UTC
Labels: enhancement
