### ISSUE TITLE
[Bug]: No option to save chapter markers when simply using the “Shift Times” option

### ISSUE THREAD

**Issue by danseitz** [advplyr/audiobookshelf#1648] opened 2023-04-05 01:59 UTC
### Describe the issue

When editing chapter data, it seems that simply using the “Shift Times” option does not trigger the “Save” button to appear to commit the chapter edits. I have to manually fiddle with one of the chapter times (e.g., change it and change it back) to get the Save button to appear.

### Steps to reproduce the issue

1. Open the chapter editor for a book.
2. Use “Shift Times” without making any other changes to the chapter data.
3. No option to “Save” is available.

### Audiobookshelf version

 v2.2.18

### How are you running audiobookshelf?

Docker

**Comment by Dr-Blank** [comment] 2023-04-05 05:49
Could not replicate through your method at first attempt. I shifted all the times by +1, hit save and it worked. However, trying to change once again back by -1, the UI did not load the save button to start with! I had to look up chapters through audible and then was able to make the button appear and save.

**Comment by jessearmstrong** [comment] 2023-04-11 00:36
I have also able to replicate this, and found that the "Save" Button will reappear if you manually change the time of one of the chapters.

**Comment by AarynRobinson** [comment] 2023-04-11 13:38
I too have experienced this bug, or seeming lack of feature if it was intended

**Comment by advplyr** [comment] 2023-04-11 14:28
This is already fixed for the next release.

**Comment by advplyr** [comment] 2023-04-16 22:38
Fixed in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)

**Closed by advplyr** 2023-04-16 22:38 UTC
Labels: bug, awaiting release
