### ISSUE TITLE
[Enhancement]: Sleep Notification Sound

### ISSUE THREAD

**Issue by DaVoodoo** [advplyr/audiobookshelf#1668] opened 2023-04-11 17:34 UTC
### Describe the feature/enhancement

A sleep notification sound option would be much appreciated.

When listening to some books, especially dramatisations, one can not clearly hear the audio fading out and a option to hear a sound would enhance the user experience.

**Comment by advplyr** [comment] 2023-04-11 17:46
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/600

**Closed by advplyr** 2023-04-11 17:46 UTC
Labels: enhancement
