### ISSUE TITLE
[Enhancement]:  Fetch episodes  but not download them to show as newest/latest episodes

### ISSUE THREAD

**Issue by gerroon** [advplyr/audiobookshelf#1523] opened 2023-02-20 17:48 UTC
### Describe the feature/enhancement

Hi

It would be super duper if it fetches all the latest episodes and show them in a newest episodes. The user then can download the necessary ones.

As of now the user has to click on each podcasts, fetch the episodes and   download them one by one which is a lot of work. I track couple hundred podcasts and as of now I do not know which podcasts have new episodes. I do not want to automatically download the episodes due to the number of podcasts I follow. I could be downloading couple hundred episodes every other day. 

I use AntennaPod on Android, it solves this propblem by fetching the episodes in a section called "Inbox", then the user can download or addthe episodes of the interest to queue from that window.

Thanks

**Comment by advplyr** [comment] 2023-02-20 18:43
Duplicate of #1516

**Closed by advplyr** 2023-02-20 18:43 UTC
Labels: enhancement
