### ISSUE TITLE
[Enhancement]: Share progress with other users

### ISSUE THREAD

**Issue by tboudreaux** [advplyr/audiobookshelf#1327] opened 2022-12-28 12:13 UTC
### Describe the feature/enhancement

Often I will start a book with friends and family in the car on road trips. When the road trip is over I'll help them manually scrub to the location in the book where we left off. It would be helpful to have some way to share progress in a book from user to user.

One idea for what form this could take is that of a share button on the "Your Progress" div which, when clicked, opens a list of users. When the user selects a user then a book mark entitled something like "Progress from <Your Username> Shared at <time>".

Some hacked together screenshots to clarify what I mean above

<img width="824" alt="Screen Shot 2022-12-28 at 7 05 35 AM" src="https://user-images.githubusercontent.com/6620251/209809666-5c275ac7-040a-4860-b84d-a3d401e05bda.png">

<img width="1035" alt="Screen Shot 2022-12-28 at 7 12 02 AM" src="https://user-images.githubusercontent.com/6620251/209810402-e6b404f2-08b8-4598-a25b-bb06f3ded6fb.png">

<img width="705" alt="Screen Shot 2022-12-28 at 7 13 16 AM" src="https://user-images.githubusercontent.com/6620251/209810548-8d1d8e76-e2d2-4995-a77d-cf4a0e7719d4.png">

**Comment by advplyr** [comment] 2023-08-01 20:55
Duplicate of #375

**Closed by advplyr** 2023-08-01 20:55 UTC
Labels: enhancement
