### ISSUE TITLE
[Enhancement]: Add Select All Option within a series view or Author View

### ISSUE THREAD

**Issue by gh0sti** [advplyr/audiobookshelf#2679] opened 2024-02-27 20:25 UTC
### Describe the feature/enhancement

Please add a toggle button to select all books within a view such as a series.
<img width="1458" alt="select option" src="https://github.com/advplyr/audiobookshelf/assets/4202657/abd79332-eebc-41fe-9ca9-2479165a2fa8">

**Comment by advplyr** [comment] 2024-02-27 21:56
Duplicate of #1708

**Closed by advplyr** 2024-02-27 21:56 UTC
Labels: enhancement
