### ISSUE TITLE
[Bug]:  key \"ino\" changed 

### ISSUE THREAD

**Issue by ThePlaidHatHacker** [advplyr/audiobookshelf#2794] opened 2024-03-27 16:58 UTC
### Describe the issue

Starting several days ago my library scans started taking several hours and using a fairly steady amount of CPU and disk I/O.  Looking at the scan logs it appears every single item in my library is listed with a log entry that includes "key \"ino\" changed from \"<VALUE>\" to \"<NEWVALUE>\".  This is causing it edit the metadata.json file for every item in the library.  Looking at the metadata.json files in the folders, every one has a modified timestamp during the most recent scan.

I am not sure what the "ino" key is and why a value might have changed.

I have several libraries, my main one is fairly large with 5,000+ books in it.  The others are smaller with just a couple hundred books each at most.  This is happening on all of the library scans.

 I am running ABS 2.8.1 in a Proxmox LXC build from the TTECK install script.  The ABS server has been running for maybe a year now and has been kept up today regularly.  The files are stored on a Synology NAS mapped via NFS.

I am not sure if the issue started right after updating to 2.8.1.  I updated from 2.8.0 on 3/20/24, but just noticed the issue on 3/25/24.  based on some of the scan logs this may have been happening before i updated to 2.8.1.   I have a scan log from 3/15/24 that shows similar behavior.

Example log entry for an audiobook in the library:
{"timestamp":"2024-03-27T04:37:57.765Z","message":"Library item \"Cory Doctorow/Lost Cause\" key \"ino\" changed from \"3571020\" to \"11544338\"","levelName":"DEBUG","level":1}
{"timestamp":"2024-03-27T04:37:57.766Z","message":"Library item \"Cory Doctorow/Lost Cause\" changed: [ino,size,lastScan]","levelName":"DEBUG","level":1}
{"timestamp":"2024-03-27T04:37:59.832Z","message":"\"Lost Cause\" Getting metadata with precedence [folderStructure, audioMetatags, txtFiles, opfFile, absMetadata]","levelName":"DEBUG","level":1}
{"timestamp":"2024-03-27T04:37:59.839Z","message":"Found metadata file \"/mnt/audiobooks/AudioBooks/Other Audiobooks/Cory Doctorow/Lost Cause/metadata.json\"","levelName":"INFO","level":2}
{"timestamp":"2024-03-27T04:37:59.852Z","message":"Success saving abmetadata to \"/mnt/audiobooks/AudioBooks/Other Audiobooks/Cory Doctorow/Lost Cause/metadata.json\"","levelName":"DEBUG","level":1}

### Steps to reproduce the issue

1. Run a library scan

### Audiobookshelf version

2.8.1

### How are you running audiobookshelf?

Other

**Comment by nichwall** [comment] 2024-03-27 17:22
Related to https://github.com/advplyr/audiobookshelf/issues/2509

**Comment by advplyr** [comment] 2024-03-27 19:45
This was the same in v2.8.0 and has to do with transient inode values. Please check #2509 because it is the same issue and at the moment I'm not aware of any way to resolve this if your file system doesn't support permanent inode values.

**Comment by advplyr** [comment] 2024-03-27 19:46
Duplicate of #2509

**Closed by advplyr** 2024-03-27 19:46 UTC
Labels: bug
