### ISSUE TITLE
[Enhancement]: Auto reorder file structure after changing information

### ISSUE THREAD

**Issue by alexanderkuenzel** [advplyr/audiobookshelf#3472] opened 2024-09-30 12:09 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

It would be great, if the folder structure on server would automatically change when meta data is edited. 

### Why would this be helpful?

For example if the series is edited, the audio file should automatically be moved in the new correct folder. Or if the Title or Author ist edited the file should be moved and renamed automatically, so the folder structure is always correct.

### Future Implementation (Screenshot)

No visual improvements necessary.

### Audiobookshelf Server Version

2.13.4

**Comment by nichwall** [comment] 2024-09-30 14:03
Duplicate of https://github.com/advplyr/audiobookshelf/issues/312

**Closed** 2024-09-30 16:34 UTC
Labels: enhancement
