### ISSUE TITLE
[Bug]: Error: getaddrinfo ENOTFOUND api.github.com

### ISSUE THREAD

**Issue by sourcecodemage** [advplyr/audiobookshelf#3293] opened 2024-08-16 17:31 UTC
### What happened?

I deployed ABS v2.12.0 to my kubernetes cluster. It crashes with "Error: getaddrinfo ENOTFOUND api.github.com" message and restarts in a continuous loop, or until I undeploy it.

### What did you expect to happen?

I expected the application to go into a running status. 

### Steps to reproduce the issue

1. Set ABS version to any in the range 2.12.0 - 2.12.3 
2. Deploy ABS application to K3S cluster. 
3. ABS POD is stuck in restart loop with above  getaddrinfo ENOTFOUND api.github.com (BinaryManager.js:99) error. 

### Audiobookshelf version

2.12.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

If I change the image tag to 2.11.0 , the container initialized and goes into "running" state. 
Compressed yaml deployment file.   
[crash_logs.txt.zip](https://github.com/user-attachments/files/16639788/crash_logs.txt.zip)
[audiobookshelf-deployment.yaml.zip](https://github.com/user-attachments/files/16639793/audiobookshelf-deployment.yaml.zip)

**Comment by nichwall** [comment] 2024-08-16 17:42
Should be resolved by https://github.com/advplyr/audiobookshelf/pull/3278

**Comment by advplyr** [comment] 2024-08-16 19:00
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3266

**Closed by advplyr** 2024-08-16 19:00 UTC
Labels: bug
