### ISSUE TITLE
[Enhancement]: Show only top level series

### ISSUE THREAD

**Issue by GamerClassN7** [advplyr/audiobookshelf#2105] opened 2023-09-15 14:15 UTC
### Describe the feature/enhancement

Hello,
Would be possible to implement  for series section checkbox "Show top only Series" or something similar ?

I my instance i have many author writings many brooks across many sub universes/series. etc.

For example i have: series of book's from series "Raganr" writhed by "William King",  which also wrote many books in different series in alternative Warhammer universe.

My folder structure:
1. William King
    1. Warhammer 40 000
        1. Raganr
            1. Raganr Claw
            2. Space Wolf
            3. etc.
    1. Warhammer
        1. Gotrek and Felix
            1. Goblin Slayer
            2. Skaven slayer
            3. etc.

But in my dashboard i would allow to show only The Warhammer and Warhammer 40 000 and under it its respective sub serise.
Which is working now so only little tweak would be to show only top level sese on first level

Would be this possible  ? 

i think i would greatly improve readability of  whole section "series" :)

Thank you for your time!
have a nice day :)

**Comment by advplyr** [comment] 2023-09-17 13:01
I believe this is the same as #2092 but let me know if yours is different or you could add notes to that feature request

**Comment by advplyr** [comment] 2023-09-17 13:01
Duplicate of #2092

**Closed by advplyr** 2023-09-17 13:01 UTC
Labels: enhancement
