### ISSUE TITLE
[Bug]: Broken book numbers for Series in Series

### ISSUE THREAD

**Issue by Blindie92** [advplyr/audiobookshelf#1450] opened 2023-01-28 12:08 UTC
### Describe the issue

When you Put multiple Series in a another Series and group them by Series, the number of book in the theries are broken.

### Steps to reproduce the issue

1. Generate a Series and add Multiple sub Series, only number the books in the sub series
2. go to the main series
3. group the books by series
![Screenshot 2023-01-28 130746](https://user-images.githubusercontent.com/94938390/215265608-e83df414-bcde-4cf9-bb71-0c31afe38730.png)

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by hobesman** [comment] 2023-01-28 15:21
To clarify, are you talking about the fact that it says 19 items instead of the total number of books? Or are you talking about all the "#,,,," labels?

**Comment by Blindie92** [comment] 2023-01-28 15:30
i mean all the labels, i think this has something todo that the books ar numbered in the subseries, but not in the main series

**Comment by jmt-gh** [comment] 2023-01-29 03:05
Can you provide some more detailed steps for this please:

>Generate a Series and add Multiple sub Series, only number the books in the sub series

I'm not exactly sure what to be doing to attempt to reproduce this.

**Comment by Blindie92** [comment] 2023-01-29 07:18
You need to edit a lot of books and add two series, one with IDs and one without, the one with IDs are the smaller series with 5-10 books. And the big series without IDs are like the complete universe. In the end you need like one series with 50 books without numbers and 5 subseries with 10 and each series have books with ids from 1 to 10.

**Comment by wtanksleyjr** [comment] 2023-01-29 18:27
@Blindie92 - I was able to see this.
1. Create a big series (more than 2 books) with no series ordering -- that is, add the same series name to more than 3 books.
2. Take 2 or more of those books and make up a series name and ordering for them -- add that new series name, alongside the old one, to them, along with a nice numeric ordering 1-2 (or 1-3 etc).

Now when you view the #1 series, you'll see the books grouped together, but instead of just displaying the count of books as it should (because the main #1 series being displayed has no ordering), it'll display `#,,`. The number of commas in there will be one less than the number of books -- it's trying to print a subsequence like `#1,5,17` or `#1-3` but there are no actual numbers to print.

I said "more than 2 books." If you create a subseries that has only 1 book, or if the subseries is not ordered, it will correctly just display the count of books contained in the subseries without trying to produce a subsequence. I think this latter behavior is correct: if there are any unordered books in a subseries, one cannot print a comma-separated description of their subsequence.

**Comment by advplyr** [comment] 2023-01-31 23:22
Fixed in [v2.2.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.13)

**Closed by advplyr** 2023-01-31 23:22 UTC
Labels: bug, awaiting release
