### ISSUE TITLE
[Enhancement]: ability to connect to server without internet

### ISSUE THREAD

**Issue by jaud7of8** [advplyr/audiobookshelf#3174] opened 2024-07-18 01:20 UTC
### Type of Enhancement

Android App

### Describe the Feature/Enhancement

Would like to use Audiobookshelf on android phones using the Audiobookshelf app when the phone is connected to on an offline network, one without access to the internet.

While traveling, I have laptop creating a hotspot for the kids phones to connect to and stream media from Emby stored on the laptop to the kids phones.  This works with the laptop not having access to the internet, it just creates a hotspot and the kids phones connect to the ip address and port for the Emby server from the Emby app.  It would be great to have this setup available for Audiobookshelf app.
I am aware Audiobookshelf will connect to a server on an offline network when using a browser, but as the mobile devices connect to networks with and without internet access, the young kids don't have access to the browser.

Many Thanks

### Why would this be helpful?

This would enable users to utilize Audiobookshelf in a completely off the grid environment, with only the server having to have the data, not every user only having what was predownloaded.

### Future Implementation (Screenshot)

This would be a backend network configuration, not something frontend related, a screenshot would not apply.

### Audiobookshelf Server Version

v2.11.0

### Current Implementation (Screenshot)

This would be a backend network configuration, not something frontend related, a screenshot would not apply.

**Comment by nichwall** [comment] 2024-07-18 02:19
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/566

**Closed** 2024-07-19 21:56 UTC
Labels: enhancement
