### ISSUE TITLE
[Enhancement]: Custom name

### ISSUE THREAD

**Issue by MikeGold** [advplyr/audiobookshelf#3268] opened 2024-08-10 23:26 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

It would be great if we could have the option in the settings to change the name "audiobookshelf" from the front page and the tab to whatever custom name we like.
Currently it's only possible through editing files in the docker, but if it was an option, we could just change it and don't worry about it reverting after update.

### Why would this be helpful?

It would add a nice personalisation.

### Future Implementation (Screenshot)

![image_2024-08-11_002505826](https://github.com/user-attachments/assets/af57feb0-7603-4e90-9c9b-951ae74506d7)

### Audiobookshelf Server Version

2.12.3

**Comment by advplyr** [comment] 2024-08-10 23:56
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1102

**Closed by advplyr** 2024-08-10 23:56 UTC
Labels: enhancement
