### ISSUE TITLE
[Bug]: After library rescan, audiobookshelf shows issue (item directory is missing)

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#474] opened 2022-04-21 08:56 UTC
### Describe the issue

From time to time I made a rescan of my library (normal). After this rescan, audiobookshelf shows me issues (left hand side)
![grafik](https://user-images.githubusercontent.com/15927779/164418175-8584546a-254c-4ca4-85f7-f1db0cf7f833.png)

I checked the file location but I don't find any missing file (album complete)

If I make a re-scan, the issue goes away.
![grafik](https://user-images.githubusercontent.com/15927779/164418561-9287f763-a439-43cb-a7c6-5b46b681fdd2.png)

I have that problem since the beginning.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

1.7.2 and 2.0.0

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment] 2022-04-21 16:21
Hi, some more info.
Looks like a normal library re-scan doesn't end correct.

Here the outbut from log:
```
[2022-04-21T16:10:20.605Z]  INFO: [Scanner] Library scan lscan_q6cttcy0wumyhfuadk completed in 7:31.0 | 1 Added | 12 Updated | 14 Missing           
[2022-04-21T16:10:20.607Z]  INFO: [LibraryController] Scan complete    
```
But the dashboard showing "Scanning Main"

In additional to this, if I try to rescan a single album to remove the issue, the rescan process doesn't start. I d not see anything in the logfile and the issue still exists. 
In 1.72 was this function ok and the issue about missing file/directory  goes away.

**Comment by VGITC** [comment] 2022-05-16 19:49
Similar issue in v2.0.14 (Unraid Docker)

- All working normally
- Did a library scan (from settings->Libraries->"selected library"->scan
- 41 books were marked as "Item directory is missing" (interestingly 40 from the same series and one from another series, other series and books were unaffected)
- Checked Edit->Files -> Full Path is correct -> confirmed by terminal command -> stat "pasted full path"
- a re-scan of the library did not correct
- a re-scan from the 3 dot menu on the file(s) did not correct (debug log does not show anything occurred"
- a re-scan from the "edit" menu of the files(s) did correct (debug log shows found and library updated)
- did this for all 41 and all returned to normal

**Comment by Everett115** [comment] 2022-06-13 03:24
I am having the same issue. When I click on the book it says what parts are missing. When I check, they do exist in the file directory and they show up in the "library files" section on the AudioBookShelf page. Some books had this issue from the start and more had the same problem after a force re-scan.

**Comment by Everett115** [comment] 2022-06-13 03:44
I just figured out the issue but I'm not sure why it occurs. When I click on the "manage tracks" button I see that the files arent ordered properly. When I manually edit them the problem is fixed. I double-checked the naming and track metadata and they were correct so for some reason AudioBookShelf is putting them in the wrong order and then thinks files are missing. [Here is a screenshot that shows the issue.](https://i.postimg.cc/HxJM3gbz/Capture.jpg). In the screenshot, you can see that the server sees the proper track number from the metadata and filename but for some reason has assigned them in the wrong order. Rescanning does not fix, I had to manually reorder the tracks in AudioBookServer. [Here is a link to my daily log in case anyone wants to figure out why this issue is occuring](https://drive.google.com/file/d/1zT9ttIlAZFnEDomB5YVad-Z5syWRQnbq/view?usp=sharing).

**Comment by advplyr** [comment] 2022-06-18 22:35
Can you give steps to reproduce this? It will probably require showing what your directory structure looks like.

**Closed** 2022-06-28 23:47 UTC
Labels: bug

**Comment by danielnbalasoiu** [comment] 2023-02-04 10:43
This bug is still there (`v2.2.14`):

<details>
    <summary>docker-compose.yaml</summary>

```yaml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - ../../_volumes/audiobookshelf/audiobooks:/data/audiobooks
      - ../../_volumes/audiobookshelf/books:/data/books
      - ../../_volumes/audiobookshelf/podcasts:/data/podcasts
      - ../../_volumes/audiobookshelf/config:/config
      - ../../_volumes/audiobookshelf/metadata:/metadata
```

</details>

<details>
  <summary>Screenshots</summary>
I don't know if the backslash `\` is the reason, but this doesn't seem right to me 🤔

![image](https://user-images.githubusercontent.com/46020698/216761589-de883ae6-e1d4-4158-b15d-53b6a615cf50.png)
![image](https://user-images.githubusercontent.com/46020698/216761609-0eeae00d-a6b4-4321-8efa-a5ad7168c389.png)
![image](https://user-images.githubusercontent.com/46020698/216761641-89b0ac73-edd7-450e-8b89-6ebdc5bc1e40.png)

</details>

**Comment by advplyr** [comment] 2023-02-04 14:03
It could be the backslash. It should be checking for backslash and replacing it if on windows. Are you running docker on windows?

**Comment by danielnbalasoiu** [comment] 2023-02-04 14:04
No. Forgot to mention. I'm on Ubuntu 22.04.1 LTS

**Comment by advplyr** [comment] 2023-02-04 14:24
When you are re-importing your OPML file are there podcasts in that OPML file that are already on your server?

**Comment by danielnbalasoiu** [comment] 2023-02-04 14:25
No. No podcast in the library

**Comment by danielnbalasoiu** [comment] 2023-02-04 14:51
Here is a snippet from the OPML file I'm using to import podcasts.

```opml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>Podcast Subscriptions</title>
  </head>
  <body>
    <outline type="rss" text="2.5 Admins" title="2.5 Admins" xmlUrl="https://2.5admins.com/feed/podcast" htmlUrl="https://2.5admins.com"/>
    <outline type="rss" text="99% Invisible" title="99% Invisible" xmlUrl="https://feeds.simplecast.com/BqbsxVfO" htmlUrl="https://99percentinvisible.org"/>
    <outline type="rss" text="A Death In Cryptoland" title="A Death In Cryptoland" xmlUrl="https://www.cbc.ca/podcasting/includes/adeathincryptoland.xml" htmlUrl="www.cbc.ca/podcasts"/>
  </body>
</opml>
```

**Comment by advplyr** [comment] 2023-02-04 15:01
I just uploaded that as an OPML file and it worked for me.

The backslash does need to be updated so it doesn't cause other issues down the line, but it is not the reason for this. This must be something with your file system. Have you checked the docker logs?

![image](https://user-images.githubusercontent.com/67830747/216774310-1aeb90b6-b78e-49b2-9f3f-b1a865b7de5d.png)

**Comment by danielnbalasoiu** [comment] 2023-02-04 15:06
Can you post your `docker-compose.yaml` file please?

**Comment by advplyr** [comment] 2023-02-04 15:08
I don't use docker-compose but you can refer to the one in the docs. You can also check the docker logs that will have errors in there about the item not being found.

**Comment by danielnbalasoiu** [comment] 2023-02-04 15:09
I have just tested in my home directory
```yaml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13379:80
    volumes:
      - ./audiobookshelf/data/audiobooks:/data/audiobooks
      - ./audiobookshelf/data/books:/data/books
      - ./audiobookshelf/data/podcasts:/data/podcasts
      - ./audiobookshelf/config/config:/config
      - ./audiobookshelf/config/metadata:/metadata
      - ./audiobookshelf/backups:/metadata/backups
```

and imported the sample OPML file:
![image](https://user-images.githubusercontent.com/46020698/216774752-2076a796-7e74-4d09-b196-80783fbefa52.png)

**Comment by danielnbalasoiu** [comment] 2023-02-04 15:30
Can you try to reproduce the same scenario and let me know how it goes?
- use the docker-compose file above
- import the OPML

I don't have any errors in the container while importing the OPML file.

**Comment by advplyr** [comment] 2023-02-04 16:34
When the item is not found on the server there will be errors in the logs. You should find those errors and see what they say.

**Comment by danielnbalasoiu** [comment] 2023-02-04 17:03
## Steps to reproduce

#### 1. Import the OPML file

<details>
    <summary>container logs during import process</summary>

```
audiobookshelf_1  | [2023-02-04 16:45:15] INFO: [CoverManager] Downloaded libraryItem cover "/data/podcasts\2.5 Admins/cover.png" from url "https://2.5admins.com/wp-content/uploads/powerpress/2.5-admins-1600.png" for "2.5 Admins"
audiobookshelf_1  | [2023-02-04 16:45:16] INFO: [CoverManager] Downloaded libraryItem cover "/data/podcasts\99% Invisible/cover.jpg" from url "https://image.simplecastcdn.com/images/5b7d8c77-15ba-4eff-a999-2e725db21db5/c43e134f-15e6-41ae-9a2e-5e57cf761473/3000x3000/stitcher-cover-99percentinvisible-3000x3000-r2021-final.jpg?aid=rss_feed" for "99% Invisible"
audiobookshelf_1  | [2023-02-04 16:45:17] INFO: [CoverManager] Downloaded libraryItem cover "/data/podcasts\A Death In Cryptoland/cover.jpg" from url "https://www.cbc.ca/radio/podcasts/images/adeathincryptoland-promo.jpg" for "A Death In Cryptoland"
```

</details>

#### 2. Download an episode
The episode should be saved in the `podcast` directory but there is nothing there:

```shell
# tree -L 2
.
├── audiobooks
├── books
└── podcasts
```

#### 3. Force rescan podcast library

<details>
    <summary>container logs during rescan</summary>

```
audiobookshelf_1  | [2023-02-04 16:51:37] INFO: [Scanner] Starting library scan lscan_tdl7uztc7kkg6qaesq for pods
audiobookshelf_1  | [2023-02-04 16:51:37] ERROR: Root path has no media folders: /data/podcasts (scandir.js:191)
audiobookshelf_1  | [2023-02-04 16:51:37] INFO: [Scanner] Library scan lscan_tdl7uztc7kkg6qaesq completed in 0:00.0 | 0 Added | 0 Updated | 3 Missing
audiobookshelf_1  | [2023-02-04 16:51:37] INFO: [LibraryController] Scan complete
audiobookshelf_1  | [2023-02-04 16:51:37] INFO: [LibraryScan] Scan log saved "/metadata/logs/scans/2023-02-04_lscan_tdl7uztc7kkg6qaesq.txt"
```

</details>

#### 4. Check scan log

<details>
    <summary>scan log</summary>

```
# cat 2023-02-04_lscan_tdl7uztc7kkg6qaesq.txt
{"id":"lscan_tdl7uztc7kkg6qaesq","type":"scan","libraryId":"lib_3q2zcu36yjvny4s6y2","libraryName":"pods","libraryMediaType":"podcast","folders":[{"id":"fol_2qdgzm399q7kke0k1p","fullPath":"/data/podcasts","libraryId":"lib_3q2zcu36yjvny4s6y2","addedAt":1675523275927}],"scanOptions":{"forceRescan":true,"parseSubtitles":false,"findCovers":false,"storeCoverWithItem":false,"preferAudioMetadata":false,"preferOpfMetadata":false,"preferMatchedMetadata":false,"preferOverdriveMediaMarker":false},"startedAt":1675529497357,"finishedAt":1675529497380,"elapsed":23,"resultsAdded":0,"resultsUpdated":0,"resultsMissing":3}
{"timestamp":"2023-02-04T16:51:37.363Z","message":"0 item data found in folder \"/data/podcasts\"","levelName":"INFO","level":2}
{"timestamp":"2023-02-04T16:51:37.363Z","message":"Library Item \"A Death In Cryptoland\" is missing","levelName":"WARN","level":3}
{"timestamp":"2023-02-04T16:51:37.363Z","message":"Library Item \"2.5 Admins\" is missing","levelName":"WARN","level":3}
{"timestamp":"2023-02-04T16:51:37.363Z","message":"Library Item \"99% Invisible\" is missing","levelName":"WARN","level":3}
```

</details>


### Screenshots

<details>
    <summary>Expand me</summary>

![image](https://user-images.githubusercontent.com/46020698/216779954-a19e7168-76d8-4952-85fa-acfdf17a00f6.png)
![image](https://user-images.githubusercontent.com/46020698/216779968-888815a5-6d09-43be-921e-34a5e7076800.png)


</details>

**Comment by advplyr** [comment] 2023-02-04 17:08
If you add a podcast through the search and download an episode are you able to see the downloaded episode?

**Comment by danielnbalasoiu** [comment] 2023-02-04 17:10
Yes 

```shell
 tree
.
├── audiobooks
├── books
└── podcasts
    └── Darknet Diaries
        ├── 131 -  Welcome to Video.mp3
        └── cover.jpg
```

**Comment by advplyr** [comment] 2023-02-04 17:25
Interesting. You can look inside the docker container to see where it is creating the folders for those podcasts from your OPML.

See https://stackoverflow.com/a/36265910/7431543 on how to access the shell for the docker container. Once you have the shell open you can navigate around and see where the folders are.

**Comment by danielnbalasoiu** [comment] 2023-02-04 18:17
Is should be under `podcasts` directory but since the naming is wrong (has `\` instead of `/`), the directories are not being created:

```shell
# tree /data/
/data/
├── audiobooks
├── books
└── podcasts
    └── Darknet Diaries
        ├── 131 -  Welcome to Video.mp3
        └── cover.jpg

4 directories, 2 files
```

For example, if I manually create the (wrong) path and download an episode it works.

```shell
# mkdir "/data/podcasts\2.5 Admins/"

/data/
├── audiobooks
├── books
├── podcasts
│   └── Darknet Diaries
│       ├── 131 -  Welcome to Video.mp3
│       └── cover.jpg
└── podcasts\2.5 Admins
    └── 2.5 Admins 127 -  Public Why-Fi.mp3

```

![image](https://user-images.githubusercontent.com/46020698/216782978-352f581c-e5f6-4590-8280-b590951e01d3.png)

**Comment by danielnbalasoiu** [comment] 2023-02-04 18:24
Ohh.. Forgot to mention that the OPML file is not on the container.
