### ISSUE TITLE
[Bug]: ID3 tags not used for chapter names - file name always used instead

### ISSUE THREAD

**Issue by Grandfather-Paradox** [advplyr/audiobookshelf#1611] opened 2023-03-17 23:33 UTC
### Describe the issue

The ID3 tags for my audio files aren't being used to populate their chapter names. Instead, the file name is always used. The "prefer audio metadata" setting is enabled. I have verified that the chapter names are present using ffprobe. I have tried re-scanning and clearing the entire library several times.

How the chapter titles appear:
![Screenshot from 2023-03-17 19-25-22](https://user-images.githubusercontent.com/86918786/226069140-4f95680c-d7c0-48df-8bd5-35a2525d0046.png)

Results of ffprobe:
`Input #0, mp3, from '01 - By Way of Introduction....mp3': `
  `Metadata:`
  ` title           : By Way of Introduction...`
  ` artist          : Philip Ball`
    `album_artist    : Philip Ball`
    `album           : Beyond Weird`
    `comment         : Chapter 20`
    `track           : 01/20`
   `genre           : Audiobook`
    `date            : 2018`
  `Duration: 00:01:45.79, start: 0.046042, bitrate: 74 kb/s`
  `Stream #0:0: Audio: mp3, 24000 Hz, stereo, fltp, 64 kb/s`
   ` Metadata: encoder         : LAME3.99r`
    `Side data: replaygain: track gain - -0.500000, track peak - unknown, album gain - unknown, album peak - unknown,` 
  `Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)`
   ` Metadata: `
 `comment         : Other`

Log after re-scanning:
![Screenshot from 2023-03-17 19-33-19](https://user-images.githubusercontent.com/86918786/226069641-396f3425-f00e-427c-bb29-f2414feb303e.png)

### Steps to reproduce the issue

1. Add an audiobook
2. The chapter title is the file name instead of the ID3 title

### Audiobookshelf version

2.2.16

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-03-17 23:55
Duplicate of #679

**Closed by advplyr** 2023-03-17 23:55 UTC
Labels: bug
