### ISSUE TITLE
[Enhancement]: OPF parser , add missing data for Subtitle and ASIN

### ISSUE THREAD

**Issue by superpawko** [advplyr/audiobookshelf#1349] opened 2023-01-01 12:08 UTC
### Describe the feature/enhancement

There is no way to fill field **Subtitle** and **ASIN** from .OPF file.

**Comment by advplyr** [comment] 2023-01-01 15:18
Duplicate of #1330 

#1330 doesn't include subtitle but you can add a comment to that feature request. Also, I will need an example of what it looks like in the OPF file.

**Closed** 2023-01-01 15:18 UTC
Labels: enhancement
