### ISSUE TITLE
[Enhancement]: show categories

### ISSUE THREAD

**Issue by Beulu** [advplyr/audiobookshelf#2434] opened 2023-12-20 00:30 UTC
### Describe the feature/enhancement

Is there a way to have lines for "last adds" and "discover" but for each categories and/or series, with extended line as Netflix or Prime ?

Categories doesn't appear in the library

Is it possible to add an icon and/or color for each line title ?

**Comment by advplyr** [comment] 2023-12-20 14:10
Is this the same as https://github.com/advplyr/audiobookshelf/issues/1241?

**Comment by Beulu** [comment] 2023-12-21 17:21
yes, sort of. :)

**Comment by advplyr** [comment] 2023-12-21 17:42
Duplicate of #1241

**Closed by advplyr** 2023-12-21 17:42 UTC
Labels: enhancement
