### ISSUE TITLE
“Continue listening” to ebooks

### ISSUE THREAD

**Issue by sevenlayercookie** [advplyr/audiobookshelf#3061] opened 2024-06-10 16:37 UTC
### What happened?

Small easy fix. On e-book libraries, Audiobookshelf displays the text “continue listening“ at the top of the page as if it were an audiobook.

![image](https://github.com/advplyr/audiobookshelf/assets/15989705/ec0cb076-8a3d-4099-adb5-19cbb7987f75)

### What did you expect to happen?

Would expect it to say “Continue Reading”

### Steps to reproduce the issue

1. Open ebook library
2. text Is visible at top of page

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by advplyr** [comment] 2024-06-10 16:43
This may be able to get grouped with https://github.com/advplyr/audiobookshelf/issues/2314

Before the db migration there was a continue reading shelf but that might only come back when adding an ebook only library setting.

**Comment by advplyr** [comment] 2024-06-11 18:32
Duplicate of #2314

**Closed by advplyr** 2024-06-11 18:32 UTC
Labels: bug
