### ISSUE TITLE
[Enhancement]: Option to set default playlist for podcasts

### ISSUE THREAD

**Issue by lamons** [advplyr/audiobookshelf#3667] opened 2024-12-01 04:49 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

User could set a default/pre-configured playlist to a subscribed podcast show, then when there are new episode come in, it will be automatically added to the set playlist. 

### Why would this be helpful?

Current podcast playlist function is on episodes basis, which make sense. Though in many cases the episodes could be sorted by the shows they belong to, for example I would want to put all new episodes from my subscribed music podcasts in a "Music" playlist so I can play them in a row when I want to listen to music, also "News" etc. 

### Future Implementation (Screenshot)

![CleanShot 2024-11-30 at 23 41 52@2x](https://github.com/user-attachments/assets/3b33e732-fb46-424d-9f89-55783b59b1d7)
![CleanShot 2024-11-30 at 23 46 37@2x](https://github.com/user-attachments/assets/952dacca-7523-4526-93a1-cacaaec98c4e)

### Audiobookshelf Server Version

v2.17.3

**Comment by nichwall** [comment] 2024-12-01 15:14
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1477

**Closed** 2024-12-01 18:52 UTC
Labels: enhancement
