### ISSUE TITLE
Playback speed by library

### ISSUE THREAD

**Issue by pquerner** [advplyr/audiobookshelf#1980] opened 2023-07-30 21:15 UTC
### Is your feature request related to a problem? Please describe.
Problem: Have more than 1 library, ie. 1 audio book library and 1 audio podcasts (such as music podcasts)
Put playback speed to something bigger than 1x for current playback.
The playback speed persists across libraries.

### Describe the solution you'd like
Have a function to control the playback speed by library (or item(s)).
Some items within the audio podcast library should still control its own playback speed, so its a setting on different paths for full control of the users desire. ("global", "library", "item")

### Describe alternatives you've considered
Use a locally run userscript which fixes it for me. Would exclude other clients of course.

### Additional context
I like to listen to audio books in 1.2 to 1.4 speed, because most of the time I get the context just fine.
Listening to audio podcasts however, and its still set to 1.2 playback speed, makes the listening experience not-so-great.
I have to manually switch back to 1x playback speed - and when I later on go back to the audio book its again set to 1x speed from previous session - and I have to set it to 1.2x - and so forth.

**Comment by advplyr** [comment] 2023-10-21 22:23
Duplicate of #1785

**Closed by advplyr** 2023-10-21 22:23 UTC
Labels: enhancement
