### ISSUE TITLE
[Enhancement]: seperate folders one book

### ISSUE THREAD

**Issue by Silther** [advplyr/audiobookshelf#2749] opened 2024-03-15 22:11 UTC
### Describe the feature/enhancement

Allow to have the audiobook and ebook in different locations but still behave like primary and supplementary ebook. (maybe manuelly link audio book to ebook files)
this allows for having ebook and audiobook only librarys and a combined version.
it also makes the library more accessible for other services without sacrificing audiobookshelf functions

**Comment by advplyr** [comment] 2024-03-15 22:21
Duplicate of #2588

**Closed by advplyr** 2024-03-15 22:21 UTC
Labels: enhancement
