### ISSUE TITLE
[Enhancement]: Public or guest view

### ISSUE THREAD

**Issue by hackmonker** [advplyr/audiobookshelf#1348] opened 2023-01-01 08:04 UTC
### Describe the feature/enhancement

Would love to see a public or guest view that does not need a authentication. or simply allow to run the software without any authentication. Right now i need to set a authentication even for single local use. Maybe we can assign permissions for guests or something like that.

**Comment by advplyr** [comment] 2023-01-01 15:16
Duplicate of #1135

**Closed by advplyr** 2023-01-01 15:16 UTC
Labels: enhancement
