### ISSUE TITLE
[Bug]: potential memory leak 

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#2675] opened 2024-02-27 10:11 UTC
### Describe the issue

I just noticed this warning about a potential memory leak in the logs:

> Warning: connect.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and will not scale past a single process.

This appeared in a 2.7.2 Docker install as well as in 2.8.0 RPM install.

### Audiobookshelf version

2.7.2, 2.8.0

### How are you running audiobookshelf?

Docker, RPM

**Comment by nichwall** [comment] 2024-02-27 13:51
Related to
https://github.com/advplyr/audiobookshelf/issues/2538

**Comment by advplyr** [comment] 2024-02-27 14:30
Yeah I've been meaning to look into the options for this. I think #2538 can serve as the main issue for this, I just renamed it

**Comment by advplyr** [comment] 2024-02-27 14:30
Duplicate of #2538

**Closed by advplyr** 2024-02-27 14:30 UTC
Labels: bug
