### ISSUE TITLE
[Enhancement]: Add webhook/scrobbler support

### ISSUE THREAD

**Issue by ggrensteiner** [advplyr/audiobookshelf#2345] opened 2023-11-23 21:39 UTC
### Describe the feature/enhancement

It would be great to tie my reading/read statuses to storygraph, bookwyrm or goodreads.

**Comment by nichwall** [comment] 2023-11-23 21:41
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1857

**Comment by DieselTech** [comment] 2023-11-23 22:10
While it sounds good on paper syncing to other apps, the services themselves need to have an API so you can talk with them. Goodreads and Storygraph do not provide a way for that to happen. So that means ABS can't do anything in terms of sending them data.

**Comment by advplyr** [comment] 2023-11-24 10:47
Duplicate of #1857

**Closed by advplyr** 2023-11-24 10:47 UTC
Labels: enhancement
