### ISSUE TITLE
[Bug]: When scanning, the "Scanning" popup covers buttons

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#824] opened 2022-07-10 12:22 UTC
### Describe the issue

Well, when you start scanning libraries, the green popup indicating that the libriaries are being scanned covers, among other, the User and settings-button

https://i.imgur.com/FWPBaU3.png

### Steps to reproduce the issue

1. Start scanning your library

### Audiobookshelf version

2.0.23

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment] 2022-07-11 04:51
This is a duplicate of #819

**Closed** 2022-07-12 20:09 UTC
Labels: bug
