### ISSUE TITLE
[Enhancement]: Batch / Queue "embed metadata" for multiple books or series

### ISSUE THREAD

**Issue by leifi76** [advplyr/audiobookshelf#1642] opened 2023-04-01 21:43 UTC
### Describe the feature/enhancement

Hi, 

In a similar spirit to https://github.com/advplyr/audiobookshelf/issues/1569 (Queue to create mb4 files)

WHY:
I've been trailing the app for the last couple of weeks as a direct replacement for the Plex audiobook bodge and have been loving it for individual books but my library was a bit of a mess.. I've spent a couple hours this evening going through ~200 books to organise/match, sort in to series and get covers. It's been a lot more successful than my attempt with readarr which seems to match much less often and crash far more frequently.

WHAT:
Anyway - after spending all this time organising my library within ABS I went to the library screen to add all of the metadata to the files themselves but there's no option! 

I am able to perform this task individually via the:

`Library > (Select Audiobook) > Edit > Tools > Embed Metadata`

but performing this ~200 times is time consuming and incredibly monotonous. The ability to do this in batches either by series, or even library wide would be awesome. I appreciate there are dedicated tools out there for editing / updating metadata but ABS interface makes the whole thing so quick and easy and it seems sensible to add the metadata just in case something goes wrong in future.

Cheers,

**Comment by advplyr** [comment] 2023-04-01 21:47
Duplicate of #700

**Closed by advplyr** 2023-04-01 21:47 UTC
Labels: enhancement
