### ISSUE TITLE
[Bug]: Audiobookshelf is not able to subscribe to German Podacast "Lage der nation" 

### ISSUE THREAD

**Issue by femanuel** [advplyr/audiobookshelf#3579] opened 2024-11-02 12:36 UTC
### What happened?

Audiobookshelf in Podcast mode is not able to subscribe to German Podacast "Lage der Nation" (https://feeds.lagedernation.org/feeds/ldn-mp3.xml), although the podcast can be found via the built-in search function. Several months ago this was still working.

### What did you expect to happen?

ABS should be able to subscribe to the podact, but it issues a red error message "Fehler beim Abrufen des Podcast" (German)

### Steps to reproduce the issue

1.  Try to subscribe to podcast "Lage der Nation" which can be found via the search function or use the URL 'https://feeds.lagedernation.org/feeds/ldn-mp3.xml' to do this manually.

### Audiobookshelf version

2.16.2 and earlier

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### Logs

```shell
2024-11-02 12:59:55.205

DEBUG

[iTunes] Searching for podcast with term "lage der nation"

2024-11-02 12:59:55.761

DEBUG

[iTunes] Podcast search for "lage der nation" returned 1 results

2024-11-02 12:59:57.770

DEBUG

[podcastUtils] getPodcastFeed for "https://feeds.lagedernation.org/feeds/ldn-mp3.xml"

2024-11-02 13:00:05.375

ERROR

[podcastUtils] getPodcastFeed Error AxiosError: getaddrinfo EAI_AGAIN feeds.lagedernation.org at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) { hostname: 'feeds.lagedernation.org', syscall: 'getaddrinfo', code: 'EAI_AGAIN', errno: -3001, config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [Function: httpAdapter], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 12000, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function] }, validateStatus: [Function: validateStatus], headers: { Accept: 'application/rss+xml, application/xhtml+xml, application/xml, */*;q=0.8', 'User-Agent': 'audiobookshelf (+https://audiobookshelf.org; like iTMS)' }, url: 'https://feeds.lagedernation.org/feeds/ldn-mp3.xml', method: 'get', responseType: 'arraybuffer', httpAgent: Agent { _events: [Object: null prototype], _eventsCount: 2, _maxListeners: undefined, defaultPort: 443, protocol: 'https:', options: [Object: null prototype], requests: [Object: null prototype] {}, sockets: [Object: null prototype] {}, freeSockets: [Object: null prototype] {}, keepAliveMsecs: 1000, keepAlive: false, maxSockets: Infinity, maxFreeSockets: 256, scheduling: 'lifo', maxTotalSockets: Infinity, totalSocketCount: 0, maxCachedSessions: 100, _sessionCache: [Object], createConnection: [Function (anonymous)], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false, [Symbol(active)]: true }, httpsAgent: Agent { _events: [Object: null prototype], _eventsCount: 2, _maxListeners: undefined, defaultPort: 443, protocol: 'https:', options: [Object: null prototype], requests: [Object: null prototype] {}, sockets: [Object: null prototype], freeSockets: [Object: null prototype] {}, keepAliveMsecs: 1000, keepAlive: false, maxSockets: Infinity, maxFreeSockets: 256, scheduling: 'lifo', maxTotalSockets: Infinity, totalSocketCount: 1, maxCachedSessions: 100, _sessionCache: [Object], createConnection: [Function (anonymous)], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false, [Symbol(active)]: true }, data: undefined }, request: <ref *1> Writable { _events: { close: undefined, error: [Function: handleRequestError], prefinish: undefined, finish: undefined, drain: undefined, response: [Function: handleResponse], socket: [Array], timeout: undefined, abort: undefined }, _writableState: WritableState { highWaterMark: 16384, length: 0, corked: 0, onwrite: [Function: bound onwrite], writelen: 0, bufferedIndex: 0, pendingcb: 0, [Symbol(kState)]: 17580812, [Symbol(kBufferedValue)]: null }, _maxListeners: undefined, _options: { maxRedirects: 21, maxBodyLength: 10485760, protocol: 'https:', path: '/feeds/ldn-mp3.xml', method: 'GET', headers: [Object], agent: [Agent], agents: [Object], auth: undefined, hostname: 'feeds.lagedernation.org', port: null, nativeProtocols: [Object], pathname: '/feeds/ldn-mp3.xml' }, _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _eventsCount: 3, _onNativeResponse: [Function (anonymous)], _currentRequest: ClientRequest { _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, destroyed: false, _last: true, chunkedEncoding: false, shouldKeepAlive: false, maxRequestsOnConnectionReached: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, strictContentLength: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, _closed: false, socket: [TLSSocket], _header: 'GET /feeds/ldn-mp3.xml HTTP/1.1\r\n' + 'Accept: application/rss+xml, application/xhtml+xml, application/xml, */*;q=0.8\r\n' + 'User-Agent: audiobookshelf (+https://audiobookshelf.org; like iTMS)\r\n' + 'Host: feeds.lagedernation.org\r\n' + 'Connection: close\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: nop], agent: [Agent], socketPath: undefined, method: 'GET', maxHeaderSize: undefined, insecureHTTPParser: undefined, joinDuplicateHeaders: undefined, path: '/feeds/ldn-mp3.xml', _ended: false, res: null, aborted: false, timeoutCb: null, upgradeOrConnect: false, parser: null, maxHeadersCount: null, reusedSocket: false, host: 'feeds.lagedernation.org', protocol: 'https:', _redirectable: [Circular *1], [Symbol(shapeMode)]: false, [Symbol(kCapture)]: false, [Symbol(kBytesWritten)]: 0, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype], [Symbol(errored)]: null, [Symbol(kHighWaterMark)]: 16384, [Symbol(kRejectNonStandardBodyWrites)]: false, [Symbol(kUniqueHeaders)]: null }, _currentUrl: 'https://feeds.lagedernation.org/feeds/ldn-mp3.xml', _timeout: null, [Symbol(shapeMode)]: true, [Symbol(kCapture)]: false } }
```

### Additional Notes

I really like ABS very much and appreciate your excellent work. Would be great if you were able to fix this issue. Thank you very much for your efforts in advance!

**Comment by Vito0912** [comment] 2024-11-02 13:09
Duplicate of #3346

**Comment by femanuel** [comment] 2024-11-02 14:14
Could solve this issue with the solution described here:  https://github.com/advplyr/audiobookshelf/issues/3346#issuecomment-2335177670
Thanks for the quick help!

**Closed** 2024-11-02 14:14 UTC
Labels: bug
