### ISSUE TITLE
[Enhancement]: Do not flag items as 'in progress' for Continue Listening unless a user has listened for at least X seconds

### ISSUE THREAD

**Issue by BristleBeard** [advplyr/audiobookshelf#1546] opened 2023-02-24 00:42 UTC
### Describe the feature/enhancement

I have accidentally clicked on a few items before which immediately began playing, and ended up in the continue listening section. **I'm proposing that items aren't flagged until a few seconds of play time have happened.** How much- I'm not sure. Perhaps 30 seconds? Maybe configurable?

**Comment by ScuttleSE** [comment] 2023-04-10 06:29
I second this. Also, having a auto-purge after X days for the "continue listening" list would be very nice.

**Comment by watsonbox** [comment] 2023-05-12 20:56
As I side note, I believe bookmarks also currently immediately set the progress to their position. That's not so useful when re-visiting a snippet from a book previously completed. This feature could go some way towards improving that, especially if it were possible to set a higher value when seeking from a bookmark.

**Comment by advplyr** [comment] 2023-05-12 22:56
@watsonbox Sounds like you are talking about #1766 which I just marked as a dupe of #1653

As for this original issue I had the same frustration with accidentally playing an audiobook. The problem was that when you close the player it sends a sync request. The update I made is the first sync won't happen unless you have listened for 20 seconds. This means if you press play or you start the audiobook by pressing a timestamp link you will have to listen for 20 seconds before it starts syncing.

This also applies to podcast episodes btw. We can expand on this or making the length longer if this still causes issues.

**Comment by watsonbox** [comment] 2023-05-17 08:46
@advplyr Thanks for coming back to me and for the clarifications; indeed I did see #1766 afterwards 👍.

I actually explored a possible solution to the bookmarks issue in #1778 and commented here https://github.com/advplyr/audiobookshelf/issues/1653#issuecomment-1550993311. Let me know what you think. It's just a draft idea which I'm fine to throw away.

**Comment by advplyr** [comment] 2023-05-28 00:02
Added in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)

**Closed by advplyr** 2023-05-28 00:02 UTC
Labels: enhancement, awaiting release
