### ISSUE TITLE
[Enhancement]: SSO login support

### ISSUE THREAD

**Issue by wsguede** [advplyr/audiobookshelf#1538] opened 2023-02-22 21:29 UTC
### Describe the feature/enhancement

Something like github, google, or [authelia](https://www.authelia.com/) comes to mind.

**Comment by advplyr** [comment] 2023-02-22 21:43
Duplicate of #998

**Closed by advplyr** 2023-02-22 21:43 UTC
Labels: enhancement

**Comment by wsguede** [comment] 2023-02-22 21:57
oh it is; thank you for showing me, sorry my search was too restrictive.
