### ISSUE TITLE
[Bug]: Books not added automatically after being uploaded - Scan Error

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#2010] opened 2023-08-15 15:41 UTC
### Describe the issue

I uploaded a book, and it did not show up in the library. The logs are below.

The books show up after doing a regular scan from settings.

Log 1:
```
2023-08-15 15:33:43
INFO
Uploading 1 files to /audiobooks/Kurt Vonnegut/Cats Cradle

2023-08-15 15:33:46
DEBUG
[Watcher] File Added /audiobooks/Kurt Vonnegut/Cats Cradle/Cats Cradle.m4b

2023-08-15 15:33:46
DEBUG
[Watcher] Modified file in library "Audiobooks" and folder "c9df7773-8c97-490f-8dcb-383d198c9f45" with relPath "/Kurt Vonnegut/Cats Cradle/Cats Cradle.m4b"

2023-08-15 15:33:50
INFO
[Server] 1 Files Changed

2023-08-15 15:33:50
DEBUG
[Scanner] Scanning file update groups in folder "c9df7773-8c97-490f-8dcb-383d198c9f45" of library "Audiobooks"

2023-08-15 15:33:50
DEBUG
[Scanner] scanFolderUpdates fileUpdateGroup [object Object]

2023-08-15 15:33:50
DEBUG
[Scanner] Folder update group must be a new item "Kurt Vonnegut/Cats Cradle" in library "Audiobooks"

2023-08-15 15:33:50
DEBUG
[Scanner] Scanning new item "/audiobooks/Kurt Vonnegut/Cats Cradle"

2023-08-15 15:33:50
ERROR
[MediaFileScanner] Invalid data found when processing input : "/audiobooks/Kurt Vonnegut/Cats Cradle/Cats Cradle.m4b"

2023-08-15 15:33:50
WARN
[Scanner] Library item has no media files "/audiobooks/Kurt Vonnegut/Cats Cradle"

2023-08-15 15:33:50
DEBUG
[Scanner] Folder scan results [object Object]

2023-08-15 15:34:06
DEBUG
Setting permission "484" for uid 99 and gid 100 | "/audiobooks/Kurt Vonnegut"
```

Log 2:
```
2023-08-15 15:50:48
INFO
Uploading 1 files to /audiobooks/Neil Gaiman/American Gods

2023-08-15 15:50:51
DEBUG
[Watcher] File Added /audiobooks/Neil Gaiman/American Gods/American Gods.m4b

2023-08-15 15:50:51
DEBUG
[Watcher] Modified file in library "Audiobooks" and folder "c9df7773-8c97-490f-8dcb-383d198c9f45" with relPath "/Neil Gaiman/American Gods/American Gods.m4b"

2023-08-15 15:50:55
INFO
[Server] 1 Files Changed

2023-08-15 15:50:55
DEBUG
[Scanner] Scanning file update groups in folder "c9df7773-8c97-490f-8dcb-383d198c9f45" of library "Audiobooks"

2023-08-15 15:50:55
DEBUG
[Scanner] scanFolderUpdates fileUpdateGroup [object Object]

2023-08-15 15:50:55
DEBUG
[Scanner] Folder update group must be a new item "Neil Gaiman/American Gods" in library "Audiobooks"

2023-08-15 15:50:55
DEBUG
[Scanner] Scanning new item "/audiobooks/Neil Gaiman/American Gods"

2023-08-15 15:50:55
ERROR
[MediaFileScanner] Invalid data found when processing input : "/audiobooks/Neil Gaiman/American Gods/American Gods.m4b"

2023-08-15 15:50:55
WARN
[Scanner] Library item has no media files "/audiobooks/Neil Gaiman/American Gods"

2023-08-15 15:50:55
DEBUG
[Scanner] Folder scan results [object Object]

2023-08-15 15:51:51
DEBUG
Setting permission "484" for uid 99 and gid 100 | "/audiobooks/Neil Gaiman"
```

### Steps to reproduce the issue

1. Upload a book
2. Go to the library
3. Do not see book
4. Be sad

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2023-08-15 18:53
Have you verified the upload is completed by manually looking at the file in the filesystem?

Are you routing traffic through CloudFlare? CloudFlare has a 100 MB upload limit.

**Comment by kymahi** [comment] 2023-08-16 03:24
Yes, I verified that the file was finished uploading.

No, this was a local upload. Accessed the server directly through my server's internal IP. However, this has happened to other users of the server from outside the network as well, but either way, not routing traffic through CloudFlare

**Comment by nichwall** [comment] 2023-08-16 13:46
Ah, so you uploaded through the filesystem, not through the ABS interface?

Are these two book files "good"? Can you run ffprobe on them to see if there's any problems?

**Comment by kymahi** [comment] 2023-08-16 18:17
I uploaded through ABS, just at my LAN address (192.168.xxx.xxx) instead of from outside the network, but I've had other users have this same issue uploading from outside the network, so it's the same issue regardless of where it's uploaded from.

Yes, these files are good. Nothing in ffprobe and they play in ABS. Also, this happens with all books, not just these two. These are just the two most recent that I had could easily find logs for.

**Comment by advplyr** [comment] 2023-08-22 21:52
@nichwall has the correct idea here. The watcher is detecting the file before it has finished uploading. That is why it gets picked up after a regular scan.

There is another issue open for this #1362 that breaks down the issue

**Comment by advplyr** [comment] 2023-08-22 21:52
Duplicate of #1362

**Closed by advplyr** 2023-08-22 21:52 UTC
Labels: bug
