### ISSUE TITLE
[Bug]: No cover art rehosting RSS 

### ISSUE THREAD

**Issue by fillilutten** [advplyr/audiobookshelf#1979] opened 2023-07-30 10:52 UTC
### Describe the issue

The url to the cover art is just returning "Not Found" 

https://audiobookshelf.xxxx.com/feed/sib/cover

### Steps to reproduce the issue

1. Add podcast
2. Rehost with RSS
3. Add in Podcast player 

### Audiobookshelf version

v.2.3.3

### How are you running audiobookshelf?

Docker

**Comment by PulsarFTW** [comment] 2023-07-30 10:55
I am experiencing the same problem. I am also running v.2.3.3 with docker. Any other podcast app is not displaying the cover and going direct to the URL results in a "Not Found" error.

It also occurs when going via local IP.

**Comment by fillilutten** [comment] 2023-07-30 11:01
Sorry, missed that it was already posted. My bad!  https://github.com/advplyr/audiobookshelf/issues/1948

**Comment by advplyr** [comment] 2023-07-30 15:34
Duplicate of #1948

**Comment by advplyr** [comment] 2023-07-30 15:34
Yeah this will be fixed in the next release

**Closed by advplyr** 2023-07-30 15:34 UTC
Labels: bug
