### ISSUE TITLE
[Enhancement]: Ability to select cover from the epub files first page/cover page

### ISSUE THREAD

**Issue by dev-Blaze** [advplyr/audiobookshelf#2356] opened 2023-11-27 02:33 UTC
### Describe the feature/enhancement

Ability to select the book cover from the epub files first page/cover page. This helps for books that are not officially published but are grabbed from places like wattpad / royal road etc.

**Comment by advplyr** [comment] 2023-11-27 10:08
Duplicate of #1479

**Closed by advplyr** 2023-11-27 10:08 UTC
Labels: enhancement
