### ISSUE TITLE
[Enhancement]: Queue to create m4b files

### ISSUE THREAD

**Issue by skronenwerth** [advplyr/audiobookshelf#1569] opened 2023-03-01 12:58 UTC
### Describe the feature/enhancement

It would be super if a queue for creating m4b files could be implemented.

For example, if I add 10 audiobooks as mp3 files and want to convert them to m4b files, I can start the process for one audiobook and after completion I have to start the next process by hand. It would be great if instead I can add all 10 audiobooks to a queue for converting audiobooks, which will be processed by the system one by one.

**Comment by KaiStarkk** [comment] 2023-03-07 10:04
Bulk metadata embed would also be handy. 

ABS seems to have the best scanner out there, and does a better job of reading a directory structure than Readarr. Would be handy to be able to write ABS’ metadata back out to the ID3 tags of the whole library - then it can be imported into Readarr

**Comment by WarHawk8080** [comment] 2023-03-15 05:18
Would be nice to be able to click encode on the entire series, rather than having to go to each individual book in the series to start the m4b encoder

Best scanner, good player...easy to use...love it!  Just needs a few fine tuning tweaks is all  :)

**Comment by advplyr** [comment] 2023-06-14 13:47
Duplicate of #1267

**Closed by advplyr** 2023-06-14 13:47 UTC
Labels: enhancement
