### ISSUE TITLE
[Enhancement]: Series Metadata

### ISSUE THREAD

**Issue by AdamCerutti** [advplyr/audiobookshelf#2836] opened 2024-04-09 16:53 UTC
### Describe the feature/enhancement

It would be nice if series' had more metadata fields like a cover, description, etc.

I listen to a lot of audiobooks that have series covers and descriptions. My current workaround is to add a zero-ith book in the series called "Cover" that houses the cover. This makes it so that when I "collapse series" in the library view, the series cover appears, as opposed to the 1st book cover, which wouldn't represent the entire series' contents.

As for series descriptions, I've been placing them with the 1st book's description, with the description for the 1st book sitting beneath.

It's a bit clunky and bloats my library. I would love to be able to have these features for series themselves. Ideally, these would be visible/editable on the series page.

**Comment by advplyr** [comment] 2024-04-09 17:00
Duplicate of #711

**Closed by advplyr** 2024-04-09 17:00 UTC
Labels: enhancement
