### ISSUE TITLE
[Bug]: "Send Ebook to..." causes book vertical ellipses on book to jump to top left of browser

### ISSUE THREAD

**Issue by lkjfdsaofmc** [advplyr/audiobookshelf#3019] opened 2024-05-26 22:08 UTC
### What happened?

When clicking the vertical ellipses on a book which has an ebook version while having an e-reader added for the "Sent Ebook to" option the menu for "mark finished, add to playlist, sent ebook to, etc" jumps to the top left of the browser.  The menu is still accessible and functions as expected but is visually underneat the audiobookshelf logo making the top portion of it unavailable and the rest of it to be far from where it should be.  I've attached two photos, one of the issue occurring with a book with an ebook file and the other with a book with no ebook file working correctly.
![1](https://github.com/advplyr/audiobookshelf/assets/7034251/c1f17106-eaf3-4e24-a4d6-2631ac940323)
![2](https://github.com/advplyr/audiobookshelf/assets/7034251/46eda507-c3ca-47c6-805a-5897b89695a2)

### What did you expect to happen?

A book with an ebook file should have the drop down show up next to itself like any other book instead of in the top left of the browser.

### Steps to reproduce the issue

1. Have a library with an ebook (may also require it having an audiobook file, as all mine have both if they have an ebook)
2. Set up email to ereader options and add an ereader
3. As a user with access to sending to an ereader click the vertical ellipses on any book with an ebook file (epub in my testing)
4. Move the cursor over the drop down menu and it will immediately jump to the far top left of the browser

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Windows Tray App

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Edge

### Additional Notes

I tested this in both edge and chrome on multiple computers with the same results across multiple users.

**Comment by nichwall** [comment] 2024-05-26 22:10
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2980

**Comment by advplyr** [comment] 2024-05-26 22:14
This is fixed in the release building right now

**Closed by advplyr** 2024-05-26 22:14 UTC
Labels: bug
