### ISSUE TITLE
[Enhancement]: Modify path of backups

### ISSUE THREAD

**Issue by KellicTiger** [advplyr/audiobookshelf#2973] opened 2024-05-13 23:39 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

The target for where the backups are located is on the same volume where the application is installed

![image](https://github.com/advplyr/audiobookshelf/assets/42510565/4428188e-b1e4-48d4-be05-62a4132af2ac)

Best practice for backups is to put them on a volume other than where you are running the application or where the dataset is located.  While it is possible for me to symlink a location to where my backup drive it, the better option is to allow the path to be modified.

As a temp work around document where the pathing is stored.  I'm assuming it is in a config file somewhere.

### Why would this be helpful?

Adhering to best practices for backups.  As in the event of the drive where the app is stored you would also lose the backup.

Allowing the changing of the path to another drive would allow for better data protection.

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/42510565/31831ad3-2eab-485f-9ef6-966cf14c4a44)

### Audiobookshelf Server Version

v2.9.0

**Comment by nichwall** [comment] 2024-05-14 03:43
Duplicate of https://github.com/advplyr/audiobookshelf/issues/199 but this uses the new format and looks nicer :)

**Comment by noja11** [comment] 2024-05-14 20:44
Amazing that I'm just finding this right now and the request is so new! 

I'm currently moving ABS from Docker to an LXC and I'm having a hard time linking it to my standard services backup share. Either changing it from within the app or allowing it to be set in the config file at /etc/default/audiobookshelf would be amazing. Thank you all for your effort!

**Comment by ZLoth** [comment] 2024-05-18 01:02
As I'm running ABS as a Docker container on TrueNAS Scale. I just set up a mapping from /metadata/backups to my backups folder. That folder is then uploaded nightly to a off-site backup.

**Comment by advplyr** [comment] 2024-06-18 22:11
I made an update so that the backup path can be overridden with an environment variable BACKUP_PATH.

It is now stored in server settings so that we can eventually make the path editable in the UI. That may not make it in the next release so for anyone that wants to modify it now will be able to pass in the env variable.

**Comment by noja11** [comment] 2024-06-19 15:46
> It is now stored in server settings so that we can eventually make the path editable in the UI.

Thank you so much for that change!

I just tried an LXC where I edited the audiobookshelf config file at /etc/default/audiobookshelf to include BACKUP_PATH.  As that didn't work yet, I'm assuming I'll need to wait for the next release after 2.10.1? 

Again, thank you so much for this quality of life upgrade, I really appreciate it!

**Comment by nichwall** [comment] 2024-06-19 15:48
Yes, you'll need to either way for the next release, build form source, or use the `edge~ docker image.

**Comment by advplyr** [comment] 2024-06-19 22:17
I added the ability to edit the path in the UI for the next release. If you have used an env variable to set the backup path then it will be reverted to use the env variable path on a server restart. A warning will be showed in the logs in that case.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/aaf9ea6a-869c-4000-addb-1d3ddaeb4e3c)

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/df717457-dddf-4c81-bd00-d68811bd05f3)

**Comment by advplyr** [comment] 2024-07-09 20:39
Added in [v2.11.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.11.0)

**Closed by advplyr** 2024-07-09 20:39 UTC
Labels: enhancement, awaiting release
