### ISSUE TITLE
[Enhancement]: leaving comments on an audiobook or e-book

### ISSUE THREAD

**Issue by reshet86** [advplyr/audiobookshelf#2566] opened 2024-01-29 08:04 UTC
### Describe the feature/enhancement

Hi! Thank you so much for such wonderful software. I would really like to be able to leave comments on books so that other users of the server can also see them and read them, both from their phone and from their computer. This is very lacking, since the reader of the book may be bad or the book itself may not be interesting. I hope for your understanding)

**Comment by izyspania** [comment] 2024-01-29 13:16
I can also add to this that maybe an rating system would be nice too , like 1-5 stars.

**Comment by nichwall** [comment] 2024-01-29 13:28
Duplicate of:
https://github.com/advplyr/audiobookshelf/issues/1153
https://github.com/advplyr/audiobookshelf/issues/1890

Related to:
https://github.com/advplyr/audiobookshelf/issues/901
https://github.com/advplyr/audiobookshelf/issues/1139

**Comment by advplyr** [comment] 2024-01-29 21:33
Duplicate of #1890

**Closed by advplyr** 2024-01-29 21:33 UTC
Labels: enhancement
