### ISSUE TITLE
[Enhancement]: Add an opption to delete automatically listened episodes after x days.

### ISSUE THREAD

**Issue by edersong** [advplyr/audiobookshelf#2457] opened 2023-12-27 14:36 UTC
### Describe the feature/enhancement

Add an opption to delete automatically listened episodes after x days.

**Comment by advplyr** [comment] 2023-12-27 14:38
Duplicate of https://github.com/advplyr/audiobookshelf/issues/615

**Closed by advplyr** 2023-12-27 14:38 UTC
Labels: enhancement
