### ISSUE TITLE
[Enhancement]: Rename/Organize content on filesystem based on metadata

### ISSUE THREAD

**Issue by DeftNerd** [advplyr/audiobookshelf#949] opened 2022-08-29 17:14 UTC
### Describe the feature/enhancement

I'm particularly interested in a feature that would organize the audio books into proper Author/Year - Title directories. 

While this might be dangerous to perform on an entire library at once, especially if a book hasn't had it's metadata matched, it would be very useful to have on an individual book

Each audiobook's edit screen could have an option to move the directories, either as a button on the "Files" tab next to the "Full Path" toggle, or on the "Manage Tab". The Manage tab seems ideal. It could look like this:

![image](https://user-images.githubusercontent.com/3002275/187256560-6b120fc1-c22c-4432-a88b-e0403c9437d8.png)

Each library settings could also have an option to "Organize directories when matched" option that would automatically trigger the changes. 

This would be very useful for people who, like me, struggle to organize things manually.

**Comment by advplyr** [comment] 2023-03-31 22:07
Duplicate of #312

**Closed by advplyr** 2023-03-31 22:07 UTC
Labels: enhancement
