### ISSUE TITLE
[Feature Request] End of Chapter Sleep Timer

### ISSUE THREAD

**Issue by Atlantis-23** [advplyr/audiobookshelf#2790] opened 2024-03-26 23:02 UTC
### Describe the feature/enhancement

Many audiobook supporting apps provide the option to set a sleep timer that pauses the playback of the audiobook at the end of the current chapter.

This is a feature that I have been really missing over the long time I’ve been using ABS.

If it is possible and not too much work, it would be amazing to see this feature added.

Kind regards.

**Comment by nichwall** [comment] 2024-03-26 23:28
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2059

This functionality exists on the mobile apps, just not in the web client yet.

**Closed** 2024-03-27 19:51 UTC
Labels: enhancement
