### ISSUE TITLE
[Enhancement]: File Management

### ISSUE THREAD

**Issue by battousaifader** [advplyr/audiobookshelf#2535] opened 2024-01-20 00:20 UTC
### Describe the feature/enhancement

I would suggest if its possible for audiobookshelf to manage, organize, and import files. I like the way audiobookshelf handles metadata and I would like to have it organize my files accordingly. I know other people may have different software to organize their libraries, but if its possible, it could be an optional feature to be turned on. Thanks for your time, I really appreciate what ya'll have going on here. Love the software. Thank you very much.

**Comment by nichwall** [comment] 2024-01-20 05:44
Duplicate of #312

**Comment by advplyr** [comment] 2024-02-18 22:57
Duplicate of #312

**Closed by advplyr** 2024-02-18 22:57 UTC
Labels: enhancement
