### ISSUE TITLE
[Bug]: Library/Folder is disabled on file upload, which is an issue if you didn't choose something.

### ISSUE THREAD

**Issue by gone** [advplyr/audiobookshelf#581] opened 2022-05-10 02:51 UTC
### Describe the issue

Attempting to upload a file, I find the file from the file picker, get the "add a file" form w/ title/series/author but the top piece is disabled. I forgot to set a value there so I'm unable to save my file (getting an error for the missing values) but I'm also unable to update the values to get the form to validate. I have to cancel, select good values, and reenter data.

### Steps to reproduce the issue

1. choose a file in the file upload dialogue without choosing a library/folder

### Audiobookshelf version

[Server] Init v2.0.11  (is there a way to check this in app?)

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-05-10 22:28
When you go to the upload page values should be selected automatically, so it shouldn't be possible to have no value there.
Are you able to reproduce this every time you go to the upload page?

The reason for those fields getting disabled once you select a file is because the uploader works differently for podcast library types and book library types.

You can view the current version on the config page in the bottom of the sidebar.

**Comment by gone** [comment] 2022-05-10 22:34
I went to replicate this and am now unable to - the form w/ library and folder is now prepopulated. Is this potentially only true on a fresh install?

**Comment by advplyr** [comment] 2022-05-10 22:45
I just found the issue actually. If you refresh the page it is not always populating.

**Comment by advplyr** [comment] 2022-05-12 00:42
Fixed in [v2.0.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.13)

**Closed by advplyr** 2022-05-12 00:42 UTC
Labels: bug
