### ISSUE TITLE
Volume boost

### ISSUE THREAD

**Issue by hydrian** [advplyr/audiobookshelf#2801] opened 2024-03-31 14:08 UTC
### Describe the feature/enhancement

I'd liked to see per book client-side volume boosting. Many books, particularly audiobooks transfered from cassette tapes, have very low volumes. 

I have the use case of listening to an audiobook that was transfered from tape, going over a BT radio transmitter (which are notoriously quiet), to a car radio (a noisy environment). 

I know this is similar to #2776 but I'm not sure if the implementation would be the same.

**Comment by advplyr** [comment] 2024-03-31 14:23
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/195

**Closed by advplyr** 2024-03-31 14:23 UTC
Labels: enhancement
