### ISSUE TITLE
[Bug]: Autoplayed podcast episodes don't appear on "continue listening" row

### ISSUE THREAD

**Issue by ndarilek** [advplyr/audiobookshelf#2441] opened 2023-12-22 23:56 UTC
### Describe the issue

I'm listening to a serialized fiction podcast. If I manually start and stop listening to an episode, that episode appears on the "Continue listening" row. If I let the episode play and another starts, or if I fast-forward through the end of an episode and the next starts playing, that next episode doesn't appear on the "Continue listening" row.

If I listen to, say, episode 5 of a show, and episode 6 autostarts, I'd expect to see episode 6 as a choice of series I can continue listening to. It seems, though, that the episode is reported as finished and the reporting for the "continue listening" row doesn't register that the next episode is started.

### Steps to reproduce the issue

1. Open a podcast from the library. It should have at least 2 consecutive unplayed episodes.
2. Start playing the earliest episode.
3. After it's played for long enough to register in the "Continue listening" row, stop it. Note that it should now appear there.
4. Let the episode play through until the next autostarts and has played for long enough to appear on the "Continue listening" row.
5. Stop the episode. For me, it does not appear in the "Continue listening" row even though I'd expect it there..

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-12-23 16:56
This is the same issue as https://github.com/advplyr/audiobookshelf/issues/2392

I just tested and it's fixed for the next release coming today most likely.

**Comment by advplyr** [comment] 2023-12-23 16:56
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2392

**Closed by advplyr** 2023-12-23 16:56 UTC
Labels: bug
