### ISSUE TITLE
[Bug]: no more library update since 2.2.2 update

### ISSUE THREAD

**Issue by eskiiom** [advplyr/audiobookshelf#1137] opened 2022-11-10 10:25 UTC
### Describe the issue

Hello,

Since the last update from 2.2.1 to 2.2.2 I cannot update manually or automaticaly any of the podcasts.
It says "no new episode found" where there are if I check on the xml source
The "latest" page shows last updated 5 days ago when I performed the update to 2.2.2

It's the same if I add a new podcast to the library, if I check for new episodes it says no new ones, but stays empty

### Steps to reproduce the issue

1. add a podcast
2. check for new episodes with a date in the past (prior to the last published episode)
3. says no new episode even if there is

1. check new episode for existing podcast
2. says no new episode even if there is

### Audiobookshelf version

2.2.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-11-10 23:01
This is a duplicate of #1116 and will be fixed in the coming release.

**Closed by advplyr** 2022-11-10 23:01 UTC
Labels: bug
