### ISSUE TITLE
[Enhancement]: Write tags and categories in the metafile.abs

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1402] opened 2023-01-13 07:04 UTC
### Describe the feature/enhancement

What I think is very important is that the tags and categories are written into the abs file. In case of a database loss, a 100% recovery with all features would be guaranteed.

In this context a batch update possibility of all existing abs files would be very helpful. I mean a possibility to add tags and categories to all abs files afterwards. If you didn't have this, it would be almost impossible to add tags and categories to all abs files in a larger library.

**Comment by advplyr** [comment] 2023-01-13 19:58
Duplicate of #772

**Closed by advplyr** 2023-01-13 19:58 UTC
Labels: enhancement
