### ISSUE TITLE
[Bug]: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by GalaxyHopper** [advplyr/audiobookshelf#1926] opened 2023-07-17 14:18 UTC
### Describe the issue

After updating v2.3.1 Audiobookshelf stopped working. I tried to delete the sqlite file I'm not sure if it worked not much info on google how to delete a file inside a docker container or is it the sqlite file inside the mapped volume ?? The dev note is not clear. Anyways I deleted the one inside the mapped volume still the same error:

[2023-07-17 09:43:45] INFO: === Starting Server ===
[2023-07-17 09:43:45] INFO: [Server] Init v2.3.1
[2023-07-17 09:43:45] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
[2023-07-17 09:43:45] INFO: [Database] Db connection was successful
[2023-07-17 09:43:46] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
<--- Last few GCs --->
[1:0x7f5830ad63f0]     6685 ms: Scavenge 2023.9 (2067.0) -> 2023.5 (2077.5) MB, 4.5 / 0.0 ms  (average mu = 0.795, current mu = 0.638) allocation failure 
[1:0x7f5830ad63f0]     6719 ms: Scavenge 2030.4 (2077.5) -> 2030.2 (2078.2) MB, 4.6 / 0.0 ms  (average mu = 0.795, current mu = 0.638) allocation failure 
[1:0x7f5830ad63f0]     6733 ms: Scavenge 2031.2 (2078.2) -> 2030.4 (2100.0) MB, 9.3 / 0.0 ms  (average mu = 0.795, current mu = 0.638) allocation failure 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### Steps to reproduce the issue

n/a

### Audiobookshelf version

v2.3.1

### How are you running audiobookshelf?

Docker

**Comment by HStep20** [comment] 2023-07-17 14:38
I am seeing the same issue with the recent update. I followed the provided step to remove the migrated database, and let v2.3.1 rebuild it, however it is still crashing upon startup with the same error message

**Comment by GalaxyHopper** [comment] 2023-07-17 18:10
@HStep20  I fixed it by adding a new environment variable in Portainer and recreated the container. It worked!
NODE_OPTIONS=--max-old-space-size=4096

Steps in Portainer:
Stop the container then click Duplicate/Edit. Scroll down and click on Env tab then click on + Add an environment variable
Add the following with no spaces 
Name: NODE_OPTIONS 
value: --max_old_space_size=4096
Redeploy the container. 
Important to note that you've already mapped out your volumes outside the container otherwise redeploying will erase the container data and you may lose your data.

**Comment by HStep20** [comment] 2023-07-17 23:00
Thanks! I have multiple large libraries, so I needed to bump it up to 8gb (--max-old-space-size=8192)

If anyone else attempts to fix this and still sees the same issue, try a higher memory limit

**Comment by sp0rus** [comment] 2023-07-17 23:16
For those running docker compose, adding these variables to the environment section of my compose file allowed me to update without this problem:

    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=8192

I attempted to use 4096MB first and still ran into the same problem. 8192 seemed to be the magic number.

**Comment by Gauva1n** [comment] 2023-07-17 23:38
8192 was the magic number for me too, finally got it up and running with a successful database migration. Actually says it's running v2.3.2 which isn't up on this repo yet, maybe it got pushed to docker hub first. Either way even v2.3.2 didn't work until I added that NODE_OPTIONS environment variable.

**Comment by advplyr** [comment] 2023-07-17 23:39
Should be fixed in [v2.3.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.2)

I put in the `max-old-space-size` in the dockerfile in addition to removed some of the initial memory usage. Let me know how it goes

**Comment by Gauva1n** [comment] 2023-07-17 23:45
Removed the image, took the NODE_OPTIONS out of my compose fille and re-pulled v2.3.2, seems to be working now without putting those variables in the compose file. Thanks for the fix!

**Comment by GalaxyHopper** [comment] 2023-07-18 00:17
v2.3.2 is working I noticed that node options was included in the update. I reduced mine to 4096 since I have limited resources. Thanks @advplyr!

**Comment by advplyr** [comment] 2023-07-22 15:35
@adispi This got resolved from `v2.3.3` I'm assuming? You were posting on Discord about a separate crash with podcasts.

**Comment by advplyr** [comment] 2023-07-22 15:37
On the `edge` docker version I removed the `--max-old-space-size` from the Dockerfile. If anyone that had the out of memory crash before `v2.3.3` and doesn't mind testing `edge` that would be great

**Comment by adispi** [comment] 2023-07-22 15:37
You are correct. The breaking of loading items on 2.3.3 solved it for me.

**Comment by jacroe** [comment] 2023-08-17 03:11
I'm still receiving the error even while on `edge`. I've copied the output below. If there's anything specific details or steps you'd like me to do, please let me know.

```
audiobookshelf-audiobookshelf-1  | Config /config /metadata
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: === Starting Server ===
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Server] Init v2.3.3
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Db connection was successful
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [dbMigration] Migration patch 2.3.3+ - columns already on model
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Loading db data...
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [LibraryItem] Loading podcast episodes...
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [LibraryItem] Finished loading 7302 podcast episodes in 0.31s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [LibraryItem] Loading library items...
audiobookshelf-audiobookshelf-1  | [Query] Elapsed 20ms.
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [LibraryItem] Finished loading 35 library items in 0.05s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Loaded 35 library items
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Loaded 21 authors
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Loaded 1 series
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:12] INFO: [Database] Db data loaded in 0.43s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: [BackupManager] 1 Backups Found
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: [BackupManager] Auto Backups are disabled
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: [LogManager] Init current daily log filename: 2023-08-17.txt
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: [Watcher] Initializing watcher for "Podcasts".
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: [Watcher] Initializing watcher for "Audiobooks".
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:13] INFO: Listening on port :80
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:18] INFO: [Watcher] "Podcasts" Ready
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:18] INFO: [Watcher] "Audiobooks" Ready
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:36] INFO: [SocketAuthority] Socket Connected w448oAhSUwoVK_BTAAAB
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | <--- Last few GCs --->
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | [1:0x7facf48dd3f0]    44319 ms: Scavenge (reduce) 4092.0 (4116.2) -> 4092.0 (4116.2) MB, 0.8 / 0.0 ms  (average mu = 0.959, current mu = 0.562) allocation failure 
audiobookshelf-audiobookshelf-1  | [1:0x7facf48dd3f0]    44344 ms: Mark-sweep (reduce) 4093.4 (4117.6) -> 4093.4 (4117.6) MB, 7.6 / 0.0 ms  (+ 13.7 ms in 1 steps since start of marking, biggest step 13.7 ms, walltime since start of marking 23 ms) (average mu = 0.916, current mu = 0.255) al
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | <--- JS stacktrace --->
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
audiobookshelf-audiobookshelf-1  | Config /config /metadata
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: === Starting Server ===
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Server] Init v2.3.3
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Db connection was successful
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [dbMigration] Migration patch 2.3.3+ - columns already on model
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Loading db data...
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [LibraryItem] Loading podcast episodes...
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [LibraryItem] Finished loading 7302 podcast episodes in 0.28s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [LibraryItem] Loading library items...
audiobookshelf-audiobookshelf-1  | [Query] Elapsed 19ms.
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [LibraryItem] Finished loading 35 library items in 0.05s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Loaded 35 library items
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Loaded 21 authors
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Loaded 1 series
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:57] INFO: [Database] Db data loaded in 0.40s
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [BackupManager] 1 Backups Found
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [BackupManager] Auto Backups are disabled
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [LogManager] Removed daily log: 2023-07-18.txt
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [LogManager] Init current daily log filename: 2023-08-17.txt
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [Watcher] Initializing watcher for "Podcasts".
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: [Watcher] Initializing watcher for "Audiobooks".
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:58] INFO: Listening on port :80
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:59] INFO: [Watcher] "Audiobooks" Ready
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:07:59] INFO: [Watcher] "Podcasts" Ready
audiobookshelf-audiobookshelf-1  | [2023-08-17 03:08:40] INFO: [SocketAuthority] Socket Connected -lUs_R7DnsZbz7iRAAAB
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | <--- Last few GCs --->
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | [1:0x7f93996bf3f0]    63578 ms: Scavenge (reduce) 4091.9 (4116.2) -> 4091.9 (4116.2) MB, 0.7 / 0.0 ms  (average mu = 0.964, current mu = 0.581) allocation failure 
audiobookshelf-audiobookshelf-1  | [1:0x7f93996bf3f0]    63604 ms: Mark-sweep (reduce) 4093.3 (4117.6) -> 4093.2 (4117.6) MB, 7.9 / 0.0 ms  (+ 13.6 ms in 1 steps since start of marking, biggest step 13.6 ms, walltime since start of marking 23 ms) (average mu = 0.924, current mu = 0.249) al
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | <--- JS stacktrace --->
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | 
audiobookshelf-audiobookshelf-1  | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
audiobookshelf-audiobookshelf-1 exited with code 0
```

**Comment by advplyr** [comment] 2023-09-17 13:20
I'm going to close this one in favor of #2075. Most of the OOM issues have been resolved and the remaining one I'm aware of is with podcast libraries where you have thousands of episodes downloaded.

**Comment by advplyr** [comment] 2023-09-17 13:20
Duplicate of #2075

**Closed by advplyr** 2023-09-17 13:20 UTC
Labels: bug, waiting
