### ISSUE TITLE
[Enhancement]: implement "Faceted Search"/Multiple filters

### ISSUE THREAD

**Issue by Gru0810** [advplyr/audiobookshelf#2940] opened 2024-05-06 16:09 UTC
### Describe the feature/enhancement

While looking for an audio book, I came across the website “archive.org” by chance.
There I saw the possibility of “faceted search” as in online shops for electronics:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/0a346312-6279-4a8d-8df9-1c8d250cfebb)
Each selection in a block filters the entries in the other blocks.
In my opinion, the more objects there are, the better the ability to search and filter. I currently have over 3,000 audio books and filtering just by author, for example, is too rough.
For example, I have the author "Andrea Camilleri". He writes books that take place in different years (in German "Handlungzeit = HZ):
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/4a907c0b-1443-4d05-bce7-ff86817b8bb7)
I see the following filter blocks:
- block of authors
- Block of Narrators
- Limitation via “Publication year”
- Limitation by length
- block the genre
- Block of TAGs
- Blocks of Class (ePup, Audio...)
- Block of Languages

additional it would be great to have "userdefined blocks". In my case:
**- Blocks of Type**
  - complete audio book
  - abridged audio book
  - radio play
  - Live act (comedy)

**- scene of action (place or country)**
  - USA
  - Greek
  - Germany
  - France
  My items play on 114 different countries or regions:
![image](https://github.com/advplyr/audiobookshelf/assets/72630160/ec647013-5008-4871-8e22-a334d347305f)
**- year of action**
- 1913
- 100 BC
- 1984 (Georg Orwell)

**- age rating**
- 10 year
- 12 year
- 16 year
- 
**- target group**
- women
- men
- all

**Comment by advplyr** [comment] 2024-05-06 16:23
I think this can be grouped with https://github.com/advplyr/audiobookshelf/issues/1465 and https://github.com/advplyr/audiobookshelf/issues/2197

This is more filtering and not searching so I think #1465 can be used for this, what do you think?

**Comment by Gru0810** [comment] 2024-05-06 17:30
I agree it's more filtering but i know it under the technical name "faceted search"
Okay ... i found it also unter "https://www.prefixbox.com/blog/faceted-filtering/"

**Comment by advplyr** [comment] 2024-05-06 17:36
I was going to make this the primary thread for multiple filters since it is more detailed but realized that #1465 already has a bunch of support on it. I'll mention this thread over there and mark this as duplicate

**Comment by advplyr** [comment] 2024-05-06 17:36
Duplicate of #1465

**Closed by advplyr** 2024-05-06 17:36 UTC
Labels: enhancement
