### ISSUE TITLE
[Enhancement]: Bookmarks, notes and highlights for the ebook reader

### ISSUE THREAD

**Issue by petruut** [advplyr/audiobookshelf#3402] opened 2024-09-11 12:38 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

Most of us don’t just want to flick through pages while reading, but actively process the text. This means:

- Bookmarks
- Notes
- Highlights of passages

and ideally a way to get this metadata out/ export/ parse

### Why would this be helpful?

This would elevate the ebook reading experience and promote this app as the main one to have for both ebooks and audiobooks. Otherwise, I’m sure many of us are forced to seek secondary apps to interact with the ebooks in this way

### Future Implementation (Screenshot)

Most ebook readers with have this implemented - both open source (e.g. http://koreader.rocks/user_guide/#bookmarks) and closed source (e.g. screenshots). I don’t think we’d need to reinvent the wheel, only copy the lightest complete design heuristics.

<img width="685" alt="image" src="https://github.com/user-attachments/assets/e56005b9-9ece-435b-a615-69f03ecdcc15">

### Audiobookshelf Server Version

v2.13.4

**Comment by advplyr** [comment] 2024-09-11 13:28
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1709 and https://github.com/advplyr/audiobookshelf/issues/1558

**Closed by advplyr** 2024-09-11 13:28 UTC
Labels: enhancement
