### ISSUE TITLE
[Bug]: no local cover > mp3 to cover log

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#1916] opened 2023-07-16 18:16 UTC
### Describe the issue

i have a few loglines like this after the migration: " ... 001.mp3 -y -vf scale=400:-1 /metadata/cache/covers/113f4b0d-7815-4ae0-94e1-510d1466509e_400.webp (ffmpegHelpers.js:76)" ... 

this i happen when a folder has no local cover and the option "Find covers" is disabled ... (covers was there in the privious version) ... so i needed to apply "a new cover"

### Steps to reproduce the issue

1. ive no time to reproduce this but i hope this was if a folder has no local cover

### Audiobookshelf version

2.3.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-09-18 21:47
I found this issue and fixed it for the next release. Although it may not seem like it, this is the same issue https://github.com/advplyr/audiobookshelf/issues/2110 so I'm going to mark this is a duplicate

**Comment by advplyr** [comment] 2023-09-18 21:48
Duplicate of #2110

**Closed by advplyr** 2023-09-18 21:48 UTC
Labels: bug
