### ISSUE TITLE
[Enhancement]: More Library Icons or the option to upload my own

### ISSUE THREAD

**Issue by Daemonias** [advplyr/audiobookshelf#3494] opened 2024-10-09 13:24 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

Simple
- More options to choose from for library icons
- An option to upload my own icons

### Why would this be helpful?

I have 5 libraries at the moment and have run out of suitable icons for more libraries
With more icons to choose from I would have a higher chance to have one for different kinds of fantasy Genres for example
If I could upload my own I wouldn't have to compromise at all

### Future Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/685461bd-86b0-4f11-8881-1086801546a4)

### Audiobookshelf Server Version

 v2.14.0

### Current Implementation (Screenshot)

![image](https://github.com/user-attachments/assets/525a7814-7495-4b16-9f76-e56891bf16e8)

**Comment by nichwall** [comment] 2024-10-09 13:30
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2993

**Closed** 2024-10-16 22:00 UTC
Labels: enhancement
