### ISSUE TITLE
[Enhancement]: Add sort to authors page for number of books

### ISSUE THREAD

**Issue by methosinhiding** [advplyr/audiobookshelf#2547] opened 2024-01-23 14:50 UTC
### Describe the feature/enhancement

The authors view is currently sorted by Author name by default, but there are no other sorting/filtering options.

Since the addition of authors is automatic but removals are a manual action, a common interaction with the authors page is to use the browser search functionality to locate and then manually delete authors who have 0 books attributed to them (either because their name was wrong/corrected, the 'author' was multiple merged names that had since been split out, or because the file was removed/moved to a different library, etc)

It would be very useful for this repeated author removal task to either be able to sort the author list by book count so that 0-book authors could be deleted en-masse or to provide a shortcut to perform that specific action such as a 'Purge Authors who have no books' button

**Comment by nichwall** [comment] 2024-01-23 15:28
Duplicate of https://github.com/advplyr/audiobookshelf/issues/2466

**Comment by advplyr** [comment] 2024-01-24 00:22
I thought there was another feature request open for sorting options on the authors page but I couldn't find it

**Comment by nichwall** [comment] 2024-01-24 00:28
Author filters (not a comprehensive list, but getting the filter functionality there):
https://github.com/advplyr/audiobookshelf/issues/1678

Author sorting was a discussion: https://github.com/advplyr/audiobookshelf/discussions/2018

**Comment by advplyr** [comment] 2024-01-24 00:31
Great thanks, this FR can be specifically for sorting by number of books which would be nice to have.

**Comment by advplyr** [comment] 2024-03-16 23:00
Added in [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1)

**Closed by advplyr** 2024-03-16 23:00 UTC
Labels: enhancement, awaiting release
