### ISSUE TITLE
[Bug]: Podcast Sort Order Not Remembered

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf#980] opened 2022-09-12 03:55 UTC
### Describe the issue

For my podcasts, I manually add the episodes to my library folder from a yt-dlp script (which adds the upload date to the beginning of the filename, so that I can properly sort each episode), rather than have ABS directly download the episodes for me. 

As a result, I need to sort my episodes by title, rather than pub date (since ABS doesn't know the pub date, and therefore has the episodes out of order). I've noticed however that whenever I change the sort order for a podcast, then navigate to another screen, then navigate back, the sort order is always changed back to 'Pub Date'. 

I'm not sure if this is a bug or is actually a feature request, but I would imagine that ABS should remember the sort order (either globally or on a per podcast basis) set by the user.  

### Steps to reproduce the issue

1. Navigate to podcast library and select podcast (where there are a list of podcast episodes)
2. Click on the 'Pub Date' to change sort order to 'Title' (happens with other sort orders as well)
3. Navigate away from the screen
4. Navigate back to podcast episode listing
5. Sort order is reset to pub date

### Audiobookshelf version

2.1.5

### How are you running audiobookshelf?

Docker

**Comment by feerlessleadr** [comment] 2022-09-13 21:45
Understood - similar to the other discussion we had, I think a user defined setting (in this case, just remembering the last sort selection by the user) seems to be the KISS and/or most user intuitive solution. Your show though, so I'll leave it up to you.

**Comment by Skitals** [comment] 2022-12-02 16:40
A different and more general use case for this feature is serial podcasts that need to be listened to chronologically. If you import a new podcast and want to start from this beginning, this is basically impossible on Android Auto where you can't change the order. A option to the set the sort order for each podcast would be awesome.

**Comment by gbakeman** [comment] 2023-09-13 23:17
I don't know if this needs to be too conplicated from the start. I listen to everything I have in date added, oldest first and that's all I need. If the ABS web player could just remember the last order I had specified, I wonder if that would satisfy most users.

**Comment by advplyr** [comment] 2023-09-17 13:33
Duplicate of #1321

**Closed by advplyr** 2023-09-17 13:33 UTC
Labels: enhancement
