### ISSUE TITLE
[Enhancement]: Theming system for web app

### ISSUE THREAD

**Issue by SurjitSahoo** [advplyr/audiobookshelf#2754] opened 2024-03-16 14:38 UTC
### Describe the feature/enhancement

- Option to integrate 3rd party community themes into the web-app
- Audio visualisers + option to add 3rd party visualisers.

**Comment by nichwall** [comment] 2024-03-16 14:46
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1705

**Comment by advplyr** [comment] 2024-03-16 17:11
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1705

**Closed by advplyr** 2024-03-16 17:11 UTC
Labels: enhancement
