### ISSUE TITLE
[Bug]: Cannot Download Metadata content 

### ISSUE THREAD

**Issue by HeckerSec** [advplyr/audiobookshelf#3398] opened 2024-09-10 02:53 UTC
### What happened?

When attempting to use the automatic matching system in ABS an error message will appear after pressing the "submit" button. 

In The cover section of an audiobook, when searching for a cover, pressing on that cover thumbnail in the window results in the following error message to pop up on the screen "Failed to Download Image from URL: Unknown Error"

When attempting to use the match tab inside the audio book details page, all the appropriate data will display in the window, but upon pressing the "submit" button the error "Failed to update item details" pops up on the screen. 

Finally when attempting to quick match an author, the message "Author not found" pops up on the screen.  

### What did you expect to happen?

It is expected that when using the metadata matching tools that the data displayed in the interface is going to be applied to the book, and that tools like the author quick match will update the author details to contain their bio/photo/etc

### Steps to reproduce the issue

1. Setup Audiobookshelf as normal from the guide on the site
2. Attempt to use any of the aforementioned tools.

### Audiobookshelf version

v2.13.4

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
{"timestamp":"2024-09-09 00:46:28.017","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected e-Ux55f15-JUi8vzAAAf","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 00:56:52.192","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket e-Ux55f15-JUi8vzAAAf disconnected from client \"Erik\" after 624226ms (Reason: ping timeout)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:00:34.518","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected 3sJN0G3Q7wwoJV-YAAAh","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:00:51.936","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket 3sJN0G3Q7wwoJV-YAAAh disconnected from client \"Erik\" after 17531ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:10:00.856","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected _lp9f0sFVQ-rLO4eAAAj","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:10:33.595","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket _lp9f0sFVQ-rLO4eAAAj disconnected from client \"Erik\" after 32738ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:15:00.853","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected 5rxTS1A1qwoMhb9HAAAl","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:15:09.785","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket 5rxTS1A1qwoMhb9HAAAl disconnected from client \"Erik\" after 8932ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:15:20.826","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected t82tazUtnIVkKbN5AAAn","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:17:32.098","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket t82tazUtnIVkKbN5AAAn disconnected from client \"Erik\" after 131271ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:32:18.821","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected s7f_uCvI1fYYcElsAAAp","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 04:34:21.851","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket s7f_uCvI1fYYcElsAAAp disconnected from client \"Erik\" after 123029ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 05:18:17.258","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected XYM7HtJO1eau_sILAAAr","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 05:19:41.706","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket XYM7HtJO1eau_sILAAAr disconnected from client \"Erik\" after 84448ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:35:27.095","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected CyUvGT9W7kc014D0AAAt","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:36:34.629","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket CyUvGT9W7kc014D0AAAt disconnected from client \"Erik\" after 67559ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:36:51.047","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected 0nunBCxMwredTP_0AAAv","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:36:51.165","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket 0nunBCxMwredTP_0AAAv disconnected from client \"Erik\" after 118ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:37:59.682","source":"Server.js:171","message":"=== Starting Server ===","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:37:59.685","source":"Server.js:102","message":"[Server] Init v2.10.1","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:00.316","source":"Database.js:178","message":"[Database] Initializing db at \"/config/absdatabase.sqlite\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:00.559","source":"Database.js:206","message":"[Database] Db connection was successful","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.082","source":"Database.js:167","message":"[Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting, customMetadataProvider","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.286","source":"LogManager.js:66","message":"[LogManager] Init current daily log filename: 2024-09-09.txt","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.357","source":"BackupManager.js:260","message":"[BackupManager] 0 Backups Found","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.359","source":"BackupManager.js:57","message":"[BackupManager] Auto Backups are disabled","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.416","source":"Watcher.js:53","message":"[Watcher] Initializing watcher for \"Audio Books\".","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.451","source":"Server.js:325","message":"Listening on port :80","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:01.726","source":"Watcher.js:79","message":"[Watcher] \"Audio Books\" Ready","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:38:33.556","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected fthogo2aTxoA7szSAAAB","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:39:06.098","source":"fileUtils.js:269","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 06:39:06.099","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=oGGMDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 06:41:54.909","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket fthogo2aTxoA7szSAAAB disconnected from client \"Erik\" after 201351ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:52:00.560","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected ChG0JfSDwfU-oTUVAAAD","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:53:18.809","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket ChG0JfSDwfU-oTUVAAAD disconnected from client \"Erik\" after 78250ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:53:35.963","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected qqTla3oS-awyCX1tAAAH","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:55:06.115","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket qqTla3oS-awyCX1tAAAH disconnected from client \"Erik\" after 90152ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 06:59:06.177","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected jKJCqr1C7aOXSCLiAAAJ","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:00:38.136","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket jKJCqr1C7aOXSCLiAAAJ disconnected from client \"Erik\" after 91960ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:13:48.067","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected ez6seysh8QlEckK0AAAL","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:13:59.691","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket ez6seysh8QlEckK0AAAL disconnected from client \"Erik\" after 11624ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:01.993","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected 02RdPRmKdXvPWWiCAAAN","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:29.757","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket 02RdPRmKdXvPWWiCAAAN disconnected from client \"Erik\" after 27764ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:31.510","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected KVwcjueYlaRGquwOAAAP","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:50.293","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Ali+Hazelwood&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:51.145","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Ali Hazelwood AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:51.267","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Andy+Weir&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:52.073","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Andy Weir AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:52.184","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Brynne+Weaver&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:52.994","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Brynne Weaver AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:53.105","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Created+by+Stan+Lee&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:53.913","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Created by Stan Lee AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:54.032","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=David+Graeber&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:54.840","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for David Graeber AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:55.473","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=David+Wengrow&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:56.285","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for David Wengrow AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:56.395","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Emily+McIntire&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:57.205","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Emily McIntire AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:57.510","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Ernest+Cline&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:14:58.321","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Ernest Cline AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:14:59.456","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=George+Orwell&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:00.265","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for George Orwell AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:00.369","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=George+R.R.+Martin&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:01.174","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for George R.R. Martin AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:01.290","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Hannah+Nicole+Maehrer&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:02.102","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Hannah Nicole Maehrer AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:02.268","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=J.+C.+Cervantes&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:03.074","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for J. C. Cervantes AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:03.396","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Jacqueline+Novak&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:04.204","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Jacqueline Novak AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:04.373","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=James+A.+Michener&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:04.711","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket KVwcjueYlaRGquwOAAAP disconnected from client \"Erik\" after 33201ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:05.182","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for James A. Michener AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:05.295","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Jamie+Lee&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:06.099","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Jamie Lee AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:06.209","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected phMWYsFBwtvuDhjvAAAR","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:06.212","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Jared+Diamond&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:07.023","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Jared Diamond AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:07.126","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Jescie+Hall&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:07.934","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Jescie Hall AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:08.114","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Kat+Rosenfield&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:08.169","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket phMWYsFBwtvuDhjvAAAR disconnected from client \"Erik\" after 1960ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:08.273","source":"Audnexus.js:29","message":"[Audnexus] Searching for author \"https://api.audnex.us/authors?name=Kwame+Mbalia&region=us\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:15:08.925","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Kat Rosenfield AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:09.091","source":"Audnexus.js:36","message":"[Audnexus] Author ASIN request failed for Kwame Mbalia AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 07:15:09.113","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected Y6NLyWlUtpB0sjAzAAAT","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:17:42.219","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket Y6NLyWlUtpB0sjAzAAAT disconnected from client \"Erik\" after 153106ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:19:12.320","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected jyaqwRAqo7oJw1vLAAAV","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:20:01.552","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket jyaqwRAqo7oJw1vLAAAV disconnected from client \"Erik\" after 49230ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:44:57.280","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected gJLJMUCJcu3VzWmHAAAX","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:45:01.899","source":"RssFeedManager.js:278","message":"[RssFeedManager] Fetched all feeds","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:45:40.653","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket gJLJMUCJcu3VzWmHAAAX disconnected from client \"Erik\" after 43375ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:45:41.642","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected -TCplIZFNj15Jcg3AAAZ","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:45:48.867","source":"RssFeedManager.js:215","message":"[RssFeedManager] Opened RSS feed \"http://10.147.19.40:13378/feed/17d7578c-9a0a-47db-816e-6f14f5b82f4f\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:46:02.610","source":"RssFeedManager.js:257","message":"[RssFeedManager] Closed RSS feed \"http://10.147.19.40:13378/feed/17d7578c-9a0a-47db-816e-6f14f5b82f4f\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:46:28.041","source":"RssFeedManager.js:278","message":"[RssFeedManager] Fetched all feeds","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 07:46:30.650","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket -TCplIZFNj15Jcg3AAAZ disconnected from client \"Erik\" after 49008ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:32:04.210","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected -bOoxH5N14H4KoiMAAAb","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:33:13.325","source":"LibraryItem.js:393","message":"[LibraryItem] Library item \"17d7578c-9a0a-47db-816e-6f14f5b82f4f\" updated","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:33:39.550","source":"fileUtils.js:269","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 08:33:39.551","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=MQeHAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 08:35:44.899","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket -bOoxH5N14H4KoiMAAAb disconnected from client \"Erik\" after 220689ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:36:19.156","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected 5Z3w-9M496DJqm4TAAAd","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:36:53.894","source":"fileUtils.js:269","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 08:36:53.896","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=MQeHAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 08:39:10.102","source":"SocketAuthority.js:135","message":"[SocketAuthority] Socket 5Z3w-9M496DJqm4TAAAd disconnected from client \"Erik\" after 170945ms (Reason: transport close)","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 08:45:40.207","source":"SocketAuthority.js:108","message":"[SocketAuthority] Socket Connected S8VTxClM4t-3_npTAAAf","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 12:59:58.829","source":"Audnexus.js:58","message":"[Audnexus] Author request failed for B00G0WYW92 AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 13:15:47.797","source":"fileUtils.js:269","message":"[fileUtils] Failed to download file \"/audiobooks/Richard P. Feynman/Surely You're Joking, Mr. Feynman!/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 13:15:47.798","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=_gA_DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 13:17:04.189","source":"fileUtils.js:269","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 13:17:04.194","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=MQeHAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:26:23.290","source":"Server.js:191","message":"=== Starting Server ===","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.293","source":"Server.js:114","message":"[Server] Init v2.13.4","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.295","source":"Server.js:115","message":"[Server] Node.js Version: v20.17.0","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.296","source":"Server.js:116","message":"[Server] Platform: linux","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.297","source":"Server.js:117","message":"[Server] Arch: arm64","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.372","source":"Database.js:182","message":"[Database] Initializing db at \"/config/absdatabase.sqlite\"","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:23.504","source":"Database.js:210","message":"[Database] Db connection was successful","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:24.226","source":"Database.js:172","message":"[Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting, customMetadataProvider, mediaItemShare","levelName":"INFO","level":2}
{"timestamp":"2024-09-09 19:26:51.139","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Max Brooks/World War Z/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:26:51.141","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=RhCPEAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:38:34.643","source":"Audnexus.js:58","message":"[Audnexus] Author ASIN request failed for Andy Weir AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:43:46.091","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:43:46.092","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:43:56.864","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:43:56.865","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:44:05.783","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:44:05.785","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:44:57.928","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:44:57.930","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:45:20.435","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:45:20.436","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:46:48.657","source":"fileUtils.js:268","message":"[fileUtils] Failed to download file \"/audiobooks/Andy Weir/The Martian/cover\" AggregateError","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:46:48.658","source":"CoverManager.js:129","message":"[CoverManager] Download image file failed for \"https://books.google.com/books/content?id=9oGJDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api\" Unknown error","levelName":"ERROR","level":4}
{"timestamp":"2024-09-09 19:47:12.406","source":"Audnexus.js:58","message":"[Audnexus] Author ASIN request failed for Andy Weir AggregateError","levelName":"ERROR","level":4}
```

### Additional Notes

I have attempted to update the system, to the latest version, without success. 

I attempted running without the Mullvad VPN connection on the system, as well as disabling the pi-hole ad blocker, with no positive results. 

ABS is running on a Raspberry PI 4B.

**Comment by mikiher** [comment] 2024-09-10 15:45
I'm not sure what the root cause is, but obviously Logger doesn't handle AggregateError correctly.
I'm going to to try to fix that first.

**Comment by mikiher** [comment] 2024-09-19 09:35
Since this is now merged, you can attempt to install the edge version of the docker image, try again and reattach the logs.

Or you can wait for the next version if you're not comfortable with installing the edge version.

**Comment by mikiher** [comment] 2024-10-09 11:19
Pinging again, since this is in a released version now.

**Comment by HeckerSec** [comment] 2024-10-09 13:24
> Pinging again, since this is in a released version now.

Thanks for reaching out, and sorry for the radio silence.

Unfortunately I lost all my equipment in an accident and may not be able to replicate the bug. Although I'm planning on setting up a new system soon and will reply if the same issue pops up again

**Closed** 2024-10-09 13:48 UTC
Labels: bug, waiting
