### ISSUE TITLE
[Bug]: Authors → Match All Authors is resulting in a 429 Error from api.audnex.us, needs to be rate limited, possible warning message

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2931] opened 2024-05-05 18:23 UTC
### Describe the issue

In some of my AudioBookShelf library, I have hundreds of authors. When I attempt to do an author match using Authors → Match All Authors, I get a match on some authors, but errors on others, including well-known authors. A rescan results in some of those missed authors being matched up. When I review the servers logs, I see the following:
```
2024-05-05 12:44:57.626 - INFO - [Audnexus] Searching for author "https://api.audnex.us/authors/B004AIN4W4?region=us"
2024-05-05 12:44:57.705 - ERROR - [Audnexus] Author request failed for B004AIN4W4 AxiosError: Request failed with status code 429
2024-05-05 12:44:57.730 - INFO - [Audnexus] Searching for author "https://api.audnex.us/authors?name=David+Javerbaum&region=us"
2024-05-05 12:44:57.821 - ERROR - [Audnexus] Author ASIN request failed for David Javerbaum AxiosError: Request failed with status code 429
2024-05-05 12:44:58.060 - DEBUG - [Audnexus] Looking up author by name Day Keene
2024-05-05 12:44:58.061 - INFO - [Audnexus] Searching for author "https://api.audnex.us/authors?name=Day+Keene&region=us"
2024-05-05 12:44:58.133 - ERROR - [Audnexus] Author ASIN request failed for Day Keene AxiosError: Request failed with status code 429
```
This tells me that AudioBookShelf is sending too many requests to api.audnex.us within a short period of time and needs to slow down and be rate limited to maybe one request every .25 to .5 seconds. Having author's being matched up is not a time-critical function, and waiting several minutes for the matching to complete should not be an unexpected condition. It may warrant a warning message when the administrator clicks on the Match All Authors that it may take some time to complete.

Screenshot from logs screen:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/e622c051-2d2e-449c-ace3-d405d7a8bad8)

Example log file filtered for WARN-level messages: 
[429 Errors.txt](https://github.com/advplyr/audiobookshelf/files/15214049/429.Errors.txt)

### Steps to reproduce the issue

1. Go to a library with large number of authors
2. Go to Authors
3. Click on March All Authors 
4. Wait until red error messages appear.
5. Go to Settings → Logs
6. Filter for Warn-level messages
7. 

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2024-05-05 18:40
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1570

**Closed** 2024-05-05 20:26 UTC
Labels: bug
