### ISSUE TITLE
[Enhancement]: Homepage Categories as links / Customization

### ISSUE THREAD

**Issue by scuppasteve** [advplyr/audiobookshelf#2957] opened 2024-05-09 15:41 UTC
### Describe the feature/enhancement

On the homepage there are categories listed with books under them. Recently Added, Recent Series, Discover, Listen Again, etc. I would like to have those link to a filtered library based on that topic. Like for Recently Added it would go beyond the 8 or so most recent books and would go to the library view sorted for recently added for the whole library. 

My second request is if we could customize the homepage with other filtered lists that we choose.

**Comment by nichwall** [comment] 2024-05-09 16:08
Custom shelves related to https://github.com/advplyr/audiobookshelf/issues/1273

**Comment by advplyr** [comment] 2024-05-09 17:51
Duplicate of https://github.com/advplyr/audiobookshelf/issues/923

**Closed by advplyr** 2024-05-09 17:51 UTC
Labels: enhancement
