### ISSUE TITLE
[Bug]: Search not working correctly

### ISSUE THREAD

**Issue by dedors** [advplyr/audiobookshelf#2234] opened 2023-10-21 21:05 UTC
### Describe the issue

When I perform a search with numbers, the results are not what I am expecting.

Search Query:
TEXT 04

Expected Results:
13 Results, episode number 040 - 049, plus 004, 104 and 204 (etc) should be listed.

Both partial and full number does not work, it needs to be at begining and include the "-"

This affects the android and the web client.

### Steps to reproduce the issue

Number partially at end:
![Screenshot_20231021-223508~2](https://github.com/advplyr/audiobookshelf/assets/17786985/7c24d6b4-88df-474b-b983-5bb6d49492e8)
Number complete at end:
![Screenshot_20231021-223531~2](https://github.com/advplyr/audiobookshelf/assets/17786985/4f3411ad-637c-4ef3-bf82-d399ae6fe1ca)
Number in front without `-`
![Screenshot_20231021-223552~2](https://github.com/advplyr/audiobookshelf/assets/17786985/d979c6bf-3eb7-44bf-99ad-5823cb879b20)

Finally what works (for one number only). Placeholder `04* -` or `04? -` doesn't work too.
![Screenshot_20231021-223615~2](https://github.com/advplyr/audiobookshelf/assets/17786985/75726c1b-5da5-48cd-84c7-caf5a57e51f6)
for reference, partial text does work:
![Screenshot_20231021-223656~2](https://github.com/advplyr/audiobookshelf/assets/17786985/1a8d4bdc-a172-4032-9a1c-cea7a21990fb)

----

Additional issue: It also gives no results when alternative German Umlaut is used (ü = ue, ä = ae, ö = oe) which is sometimes used to avoid encoding issues.
It doesn't even work when there is some metadata (in the example below the autor) that uses the one I put in the search bar.

![Screenshot_20231021-223924~2](https://github.com/advplyr/audiobookshelf/assets/17786985/326ac8c4-261b-4c29-9331-f555753f3cba)
![Screenshot_20231021-223944~2](https://github.com/advplyr/audiobookshelf/assets/17786985/d215871d-5b57-47fc-8e3a-cb41a3107e35)

----
It would be nice to have fuzzy search (spelling error and it still gives results with lower sort priority). Maybe that could also weaken the Umlaut problem.
(Advanced search too, which was already posted https://github.com/advplyr/audiobookshelf/issues/2197 )

### Audiobookshelf version

2.4.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-10-21 22:20
I'm not seeing a bug here, it seems like you are requesting a fuzzy search feature. I'll mark this as a duplicate of #1401 unless you can clarify a bug.

There is a bug with capitalization that will be fixed in the next release: https://github.com/advplyr/audiobookshelf/issues/2187

**Comment by advplyr** [comment] 2023-10-21 22:20
Duplicate of #1401

**Closed by advplyr** 2023-10-21 22:20 UTC
Labels: bug

**Comment by dedors** [comment] 2023-10-21 22:41
As far as I understand fuzzy search is only for misspelling?

I hope this clarifies my description:

Currently, it only performs searches as if the query were enclosed in double quotation marks.
The order of words probably should not be a strict requirement, and demanding such exactness that even the use of ` - ` is necessary isn't something most people would anticipate, I believe.

Also it only searches the title, other metadata is ignored. I would assume that at least series, autor, narrator, genres, tags and year should be important too. (would fix what you see on the last 2 images)

**Comment by advplyr** [comment] 2023-10-21 22:50
Ah yes, got it. Currently the search is basic looking for exact string matches case-insensitive. What you are requesting would be handled if we implement the advanced search you mentioned in #2197. Feel free to add additional notes to that issue if it is missing something.



> Also it only searches the title, other metadata is ignored. I would assume that at least series, autor, narrator, genres, tags and year should be important too. (would fix what you see on the last 2 images)

It does search all of these but they have to be exact string matches.
