### ISSUE TITLE
[Bug]: New imports creating new author entries (Duplicating) not matching to existing

### ISSUE THREAD

**Issue by KeeperOfTheFort** [advplyr/audiobookshelf#2131] opened 2023-09-20 17:28 UTC
### Describe the issue

As per title... Upon running library scan to pickup new audiobooks, audiobookshelf keeps creating a new author (duplicating) rather than matching to existing author with identical name. 

Also, I can't seem to find a way of deleting authors - if anyone knows a way please do comment or I'll add this to 'Feature Request'

Thanks to all :)

### Steps to reproduce the issue

1. Load new audio file into library folder
2. Run library scan
3. View authors page 
4. See duplicates
5. Cry when you realise there are so many of them and can't delete the unnecessary duplicates from the search results or manual entry selection dropdown within audiobook 'Details' tab.

### Audiobookshelf version

v2.4.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment] 2023-09-20 17:42
Fixed in 2.4.3
https://github.com/advplyr/audiobookshelf/issues/2106

**Comment by advplyr** [comment] 2023-09-20 18:49
Duplicate of #2106

**Closed by advplyr** 2023-09-20 18:49 UTC
Labels: bug
