### ISSUE TITLE
[Enhancement]: Let me use bookmarks without losing reading stats

### ISSUE THREAD

**Issue by zblesk** [advplyr/audiobookshelf#1766] opened 2023-05-10 14:31 UTC
### Describe the feature/enhancement

I often make bookmarks when listening to a book, with the intent of revisiting them sometime after finishing the book. (I use the web version for this.)

Currently, I can only view bookmarks by going to the books' page, hitting Play, going to the Player and displaying the bookmarks there. 

The biggest disadvantage of this is that it deletes my previous progress. I like seeing which book I finished when; but when I go to revisit the bookmarks, ABS forgets when the book was finished and just keeps tracking it as a currently-reading book. I can only fix that by 'finishing' it again, which puts today's date there, messing up my history. 

I'd like to be able to play bookmarked locations without changing the 'finished' state and date of the book.

**Comment by Dr-Blank** [comment] 2023-05-10 23:16
#1653 would fix this as a side effect since multiple plays would not affect the finished status

**Comment by advplyr** [comment] 2023-05-11 19:01
I can see #1653 partially handling this by still showing that you have finished it before, but I don't see how this could be built so that it doesn't save your progress when resuming a bookmark.

This would require some type of preview audio player or an extra button saying to play without tracking progress. I don't see this being implemented unless you have some other idea.

**Comment by zblesk** [comment] 2023-05-12 06:46
Frankly, if I understood #1653 correctly - that is to say: that it would track progress, but count it as a _new_ reading, keeping the old one as-is, and letting me delete the new progress as easily as I can do it now - I'd be perfectly happy with that. 
I understand not wanting to add convoluted niche features to the app, and there's really no need

**Comment by mostlyvirtual** [comment] 2023-05-12 21:52
Don't want to hijack this thread, but I can't find the answer anywhere, and this is as close as I've gotten to my question:

Is there any way to export the bookmarks?

**Comment by advplyr** [comment] 2023-05-12 22:50
@zblesk Yeah we'll have to workout the details on how that functions but you are understanding correctly.

@mostlyvirtual I responded in Discord.

**Comment by advplyr** [comment] 2023-05-12 22:50
Duplicate of #1653

**Closed by advplyr** 2023-05-12 22:50 UTC
Labels: enhancement
