### ISSUE TITLE
[Enhancement]: Chapter details in playing UI/multiple narrators

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#3045] opened 2024-06-06 06:36 UTC
### Type of Enhancement

Web Interface/Frontend

### Describe the Feature/Enhancement

A way to display additional/different chapter details under the chapter title, instead of the author name under the title. 

### Why would this be helpful?

I just got [World War Z: Complete edition](https://www.audible.com/pd/World-War-Z-The-Complete-Edition-Audiobook/B00BIKAVHS). It has a large cast of narrators, each chapter has 2 people talking. I was trying if figure out a way to display this information in the playing UI.

It made sense to me to try and encode this data in ID3 tag "artist" but I see you use that as the primary author field (I would have thought "album artist"). The tracks currently have a comment field with the "read by" info but I don't see that anywhere in the UI. 

### Future Implementation (Screenshot)

![image](https://github.com/advplyr/audiobookshelf/assets/991618/882ba581-4779-47a4-bbd3-f7b89b2be53e)
Chapter 2 is read by "Max Brooks & Steve Park". I replaced author name with this data that would be encoded on the track somewhere....

It's hard to say where this data should be stored based on how ABS is reading tags and how [Seanap](https://github.com/seanap/Plex-Audiobook-Guide?tab=readme-ov-file#tags-that-are-being-set) is tagging

### Audiobookshelf Server Version

v2.10.1

**Comment by SenorSmartyPants** [comment] 2024-06-06 17:06
Or if narrator is stored per track, have an option in the player to display narrator instead of author.

**Comment by advplyr** [comment] 2024-06-06 21:30
Duplicate of https://github.com/advplyr/audiobookshelf/issues/785

**Closed by advplyr** 2024-06-06 21:30 UTC
Labels: enhancement
