### ISSUE TITLE
[Enhancement]:Option to still show m4b "tool" even when book only has single m4b

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#2192] opened 2023-10-07 08:30 UTC
### Describe the feature/enhancement

I store most books at 64k in single-channel format, unless they feature a soundscape, full cast, etc. I think that storing books at 128k and in dual-channel is a waste of space, the fact that a narrator records with a single channel microphone and especially if one uses libfdk-aac for encoding, the loss of fidelity is minimal and is worth it for size being cut in half. Well anyways that's my preference not here to debate it.

If I'm uploading just one book to the server, I'd rather not SSH in to encode it manually; I'd prefer to configure these settings through the UI.

I'd like to see a more advanced automation feature that allows for preset encoding settings to be applied upon import. For example, if an audiobook is 128k, dual-channel, and has a single narrator, it should be re-encoded to 64k and single-channel. If an audiobook is 320k, has two or more channels, and more than one narrator, then it should be re-encoded to 128k, dual-channel.

**Comment by advplyr** [comment] 2023-10-07 12:28
I think you can combine this with your previous issue #1257, some of it is the same

**Comment by advplyr** [comment] 2023-10-07 12:28
Duplicate of #1257

**Closed by advplyr** 2023-10-07 12:28 UTC
Labels: enhancement
