### ISSUE TITLE
[Bug]: File entry sometimes duplicate when editing outside of ABS

### ISSUE THREAD

**Issue by SenorSmartyPants** [advplyr/audiobookshelf#3050] opened 2024-06-08 23:52 UTC
### What happened?

I was updating tags in some files using MP3Tag and Picard. I then noticed sometimes a file would get two entries in ABS. If I renamed the file, ABS would then show the new name on those 2 files. The only solution I have come up with is to copy the duplicated file, delete the originally named file (that still has 2 entries in ABS), then rename the copy back to the original name.

### What did you expect to happen?

Files should not be listed twice in ABS.

### Steps to reproduce the issue

1. Use mp3tag to update a multi file book. When I did this on one 30+ file book, I got about 5 duplicates listed. mp3tag would report a failure to write to the file and I would hit retry and then it would work.

### Audiobookshelf version

v2.10.1

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

![image](https://github.com/advplyr/audiobookshelf/assets/991618/8d64ef87-fcb0-4882-a21e-292557c35bc7)

**Comment by nichwall** [comment] 2024-06-09 01:13
Duplicate of https://github.com/advplyr/audiobookshelf/issues/3034

**Closed** 2024-06-09 09:56 UTC
Labels: bug
