### ISSUE TITLE
Fatal javascript OOM in GC during deserialization with docker

### ISSUE THREAD

**Issue by Rilith** [advplyr/audiobookshelf#1967] opened 2023-07-26 10:28 UTC
### Steps to reproduce

1.  Install docker
2.  Install  docker compose
3.  create  the docker-compose.yml file
4.  docker  compose pull
5.  docker  compose up (without -d to check the  error)

### Expected behaviour
- Audiobookshelf  should start

### Actual behaviour
- this is  printer in console:

$ docker compose up
[+] Running 1/1
 ✔ Container audiobookshelf  Created                                                                                                                                 0.5s
Attaching to audiobookshelf
audiobookshelf  |
audiobookshelf  | <--- Last few GCs --->
audiobookshelf  |
audiobookshelf  |
audiobookshelf  | <--- JS stacktrace --->
audiobookshelf  |
audiobookshelf  |
audiobookshelf  | #
audiobookshelf  | # Fatal javascript OOM in GC during deserialization
audiobookshelf  | #
audiobookshelf  |
audiobookshelf  |
audiobookshelf exited with code 133

### Environment data

Audiobookshelf Version:  Latest
Docker version: 24.0.5, build ced0996
Docker compose version: 1.25.0-1
Hardware: Raspberry Pi 4

Thank you for you hard work!

**Comment by advplyr** [comment] 2023-07-26 13:30
Please try the `edge` docker version. That would be using the image `ghcr.io/advplyr/audiobookshelf:edge`

**Comment by advplyr** [comment] 2023-07-26 13:31
Duplicate of #1938

**Closed by advplyr** 2023-07-26 13:31 UTC
Labels: bug
