### ISSUE TITLE
[Enhancement]: Translation of the ABS app just like the web interface.

### ISSUE THREAD

**Issue by Hallo951** [advplyr/audiobookshelf#1732] opened 2023-04-27 08:52 UTC
### Describe the feature/enhancement

It would be wonderful if we could pass on the language translation from the website to the ABS app. Is there a way to do this?

**Comment by advplyr** [comment] 2023-04-27 22:30
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/448

**Comment by advplyr** [comment] 2023-04-27 22:30
Yep, we can do this.

**Closed by advplyr** 2023-04-27 22:30 UTC
Labels: enhancement
