### ISSUE TITLE
[Bug]: UI so slow it's unusable

### ISSUE THREAD

**Issue by MoSattler** [advplyr/audiobookshelf#2448] opened 2023-12-25 15:08 UTC
### Describe the issue

It worked in the beginning, but with time it got slower and slower. The UI is insanely slow now or not working at all. Sometimes restarting the container seems to make it slightly more usable, but not always.

I am running the Docker container on a Synology. 

I don't think it's a hardware issue, as CPU utilisation is not more than 30%, RAM not more than 20%. The Container has no resource limitation. 

My library has maybe 20 audiobooks, and 20 podcasts with maybe 3000 episodes.

### Steps to reproduce the issue

Not sure what the root issue is, so it's hard for me to say what the root cause could be. Here are the logs.

logs don't show anything useful
<img width="1183" alt="Screenshot 2023-12-25 at 16 07 14" src="https://github.com/advplyr/audiobookshelf/assets/64152453/0f52be97-d9f3-4c23-ae2d-ec6d690ecaac">

### Audiobookshelf version

2.5.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2023-12-25 15:26
Duplicate of #1549

**Closed by advplyr** 2023-12-25 15:26 UTC
Labels: bug

**Comment by advplyr** [comment] 2023-12-25 15:27
Specific to podcasts with around 1000+ episodes. Could be a little less or more depending on the server

**Comment by advplyr** [comment] 2023-12-25 15:39
There is plenty of room for optimization but the data model, API and frontend need a major overhaul
