### ISSUE TITLE
Series and Sub-Series

### ISSUE THREAD

**Issue by MikeBishop** [advplyr/audiobookshelf#1662] opened 2023-04-10 14:26 UTC
### Is your feature request related to a problem? Please describe.
Some overarching series have smaller series within them.  The current solution enables a book to be assigned to multiple series, so that both the parent and all child series appear in the series list.

### Describe the solution you'd like
- Ability to assign a series to another series with a position, similar to what is currently done with a book
- Series which are contained in another series get collapsed together in Series view (similar to how books in a series can be collapsed in Library view) and Library view (if collapsing Series is selected)
- Clicking into the larger series shows the list of smaller series, plus any books which are assigned directly to the larger series

### Describe alternatives you've considered
Using the current setup, where a book can be assigned to both the smaller and larger series, an alternative would be to hide the smaller series if it is completely contained by the larger series.

### Additional context
![image](https://user-images.githubusercontent.com/4273797/230920953-1d5f8504-dbf5-4c08-be41-3429fcb5f79f.png)

**Comment by advplyr** [comment] 2023-04-10 14:47
Have you looked at the series page, there is a collapse sub-series option there.

![image](https://user-images.githubusercontent.com/67830747/230925062-a6316e04-49b9-4d5b-b639-74f4ae1a96f6.png)

I think that is what you are talking about. Your screenshot is of the authors page though

**Comment by MikeBishop** [comment] 2023-04-10 22:48
That's part of it, and helps. The trouble is that all the smaller series still appear in the series listing, the author listing, etc. What I'd ideally see is those smaller series appearing only inside the larger series, and not treated as full-fledged series in other views.

I'd also like to be able to tag a series as belonging to a series, rather than having to have every book belong to 2+ series. Maybe a better way to express this is the ability to have a series be composed of both books and other series?

**Comment by AarynRobinson** [comment] 2023-04-11 13:37
A potential solution could be an option to hide a series from the series page. I think that would be satisfactory to me and seems simpler to implement.

**Comment by advplyr** [comment] 2023-04-13 13:56
What is the reason for hiding sub-series?

I don't think we are going to have a series be composed of both books and series. A few reasons for this but mainly the data model is not setup to support that and sub-series should still have a sequence.

**Comment by MikeBishop** [comment] 2023-04-13 18:08
Because there can be lots of them, and they create visual clutter.

Consider something like the *Deryni* series, which is composed mostly of trilogies set in different eras.  (Modulo the occasional stand-alone.)
![image](https://user-images.githubusercontent.com/4273797/231844710-b1ec136c-e4c1-4dbb-9ecd-43cdfcee2060.png)

It's already the case that if I click into Deryni, then see the different trilogies and stand-alones; clicking into one of them shows the books in that trilogy.  That's a great start.

But if they're all listed in the Series page, then I have ~6 Deryni series -- the overarching one and the 5 smaller ones it contains.  They then become a noticeable fraction of the series listing, when they're conceptually all one thing unless I want to dig in.  Same with *Valdemar*, *Pern*, *Mistborn*, etc.  I'd like the option to have only the overarching series show anywhere outside that series' page.

When adding, it would be nice to be able to say "This new book is number 3 in the Herald Spy series, and Herald Spy already has a sequence number in Valdemar," but I can understand that would entail some abstraction in the data model.  (I haven't looked at ABS's data model for series to see how insane that would be.)  On the other hand, without that linkage, it seems like hiding a sub-series becomes more complex; ABS only knows about books belong to series, and would have to either look for overlaps between all series or look for books that are assigned to multiple series as a clue for which ones to consider.

Still, if we keep the current model, that a book has to be assigned to be, say, 3 in Herald Spy and 7.3 in Valdemar, then something that simply hides the sub-series is a step in this direction.

> and sub-series should still have a sequence.

(I'm a little confused by this part, since I haven't suggested sub-series not having a sequence.)

**Comment by advplyr** [comment] 2023-04-13 18:19
> On the other hand, without that linkage, it seems like hiding a sub-series becomes more complex; ABS only knows about books belong to series, and would have to either look for overlaps between all series or look for books that are assigned to multiple series as a clue for which ones to consider.

If we support hiding sub-series from the series (and author) page then my initial reaction is this would be boolean flag on the series that you would have to manually turn on. It could get messy trying to detect what is a sub-series. Not to say auto-detecting sub-series wouldn't ever be supported but as a first step a manual flag makes sense. We may also change the data model. It has changed a few times now as more requests come in and handling use-cases I never thought of.



> > and sub-series should still have a sequence.
> 
> (I'm a little confused by this part, since I haven't suggested sub-series not having a sequence.)

I was thinking that if we added the option to put an entire series in another series then the UI for this would then somehow have to prompt for entering the sequence of each book in that series. Using the batch editor you can already group select all the books in a series, batch edit, and add a series to all the books. Then you would need to go into each book and set the sequence afterwards.
I was thinking about the UI/UX when I said that

**Comment by MikeBishop** [comment] 2023-04-13 22:39
I took a look at the code for collapsing automatically; I can post what I've got when I'm back at a keyboard. It's a relatively small addition, but might require some real-world testing to see how much the iteration over the books actually costs. In a large library, it's potentially a lot of traversing.

Since my main instance is running in a Docker container, I don't yet have a good setup to test the change, but I'll see if I can figure that out this weekend.

**Comment by advplyr** [comment] 2023-04-13 23:04
I think the rest of the feature should be figured out before doing auto hide sub-series. We would have to have a library setting to enable that also

**Comment by MikeBishop** [comment] 2023-04-14 02:28
I'd thought you were ruling out the data model change; sorry. Yes, I agree that route would require a series editor view, and possibly a series batch editor. (Other things that might go in there: Renaming a series. Setting a custom cover for the series, which is popular with Plex collections. Could also envision it containing something like the chapter reorder tool for the component items.) I have no Vue experience, so UI I would have more trouble being any help on.

As to the option, that's obviously possible. I was wondering if there would be people who explicitly *don't* want this behavior or if it could just be part of "Collapse series." Perhaps a question for the Discord?

**Comment by MikeBishop** [comment] 2023-04-14 02:51
Oh, one other thought -- if we did go the data model route, the difference in behavior could simply be whether the books belong to both series or one series belongs to another. No scanning for overlap, just a global statement that an element is hidden if a parent is shown.

**Comment by MikeBishop** [comment] 2023-04-17 21:04
Looks like this is mostly a duplicate of #870.

**Comment by advplyr** [comment] 2023-04-30 15:39
Duplicate of  #870

**Comment by advplyr** [comment] 2023-04-30 15:40
We'll just make that issue the main one for these sub-series requests. I don't know how to cleanly handle this and don't have anything in my library that requires it so hard to visualize.

**Closed by advplyr** 2023-04-30 15:39 UTC
Labels: enhancement, waiting
