### ISSUE TITLE
[Bug]: Sorting ordeer gets reset(?) when clicking back

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1278] opened 2022-12-16 20:05 UTC
### Describe the issue

If you click back in the browser, the previous view gets a messed up sort order

### Steps to reproduce the issue

1. Open up Series
2. Make sure you're viewing all series sorted by name in descending order
3. Click a series to open it up
4. Go back by hitting Alt+Left, or right-clicking in the browser and select to go back

### Audiobookshelf version

2.2.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment] 2022-12-16 23:55
Duplicate of #1272

**Closed by advplyr** 2022-12-16 23:55 UTC
Labels: bug
