### ISSUE TITLE
[Enhancement]: Recommend books to another user on a server

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#3339] opened 2024-08-26 03:21 UTC
### Type of Enhancement

Server Backend

### Describe the Feature/Enhancement

If ABS has multiple users configured, then it would nice to have a feature to "Recommend" an audiobook to another user. 

### Why would this be helpful?

My self-hosted audiobookshelf server has a few thousand audiobooks available which I share with other family members. This volume of books can be intimidating to someone who is new to listening to audiobooks. By providing a "Recommend" feature, I can recommend several audiobooks to try out for the first time listener along with some optional text behind the recommendation. The recommend icon can only appear if there are recommended books, and recommended books can appear on the home page. 

### Future Implementation (Screenshot)

Recommend feature would have two items:
- Specific User or All Users
- 150 character limit on suggestion

From Web Page:
![image](https://github.com/user-attachments/assets/5df29a9a-0c19-4b14-bd18-3632bd711bcc)

### Audiobookshelf Server Version

2.12.3

**Comment by nichwall** [comment] 2024-08-26 03:30
Duplicate of https://github.com/advplyr/audiobookshelf/issues/721

**Comment by ZLoth** [comment] 2024-08-27 09:51
Copied comments and mockup to original feature request.

**Closed** 2024-08-27 19:45 UTC
Labels: enhancement
