### ISSUE TITLE
[Enhancement]: Allow multiple books for the same series to be in the same folder

### ISSUE THREAD

**Issue by ElDubsNZ** [advplyr/audiobookshelf#2475] opened 2024-01-02 21:05 UTC
### Describe the feature/enhancement

Right now ABS requires each book to have its own folder. Even if library scanner is set to ignore folder structure, this basic requirement still exists.

Ideally, we'd have the option to only base this on the album field. That way if I have a specific folder structure for a reason (Mine matches the folder structure of the book series distributor so new releases slot in nicely), ABS would support this.

This would enable more flexibility for end users to decide how they want to structure their files by allowing ABS to build the library based on metadata alone.

**Comment by nichwall** [comment] 2024-01-02 21:13
The "ignore folder structure" is only for metadata parsing, books are still defined as by directory.

Duplicate of
#2208

Related, but different
#2396
#2315

**Comment by advplyr** [comment] 2024-01-02 21:14
Duplicate of #2208

**Closed by advplyr** 2024-01-02 21:14 UTC
Labels: enhancement
