### ISSUE TITLE
[Enhancement]: Import Formatted Text from Book Summary Information

### ISSUE THREAD

**Issue by KeeperOfTheFort** [advplyr/audiobookshelf#2132] opened 2023-09-20 17:50 UTC
### Describe the feature/enhancement

Would it be possible to pull all basic html formatted text `<p> <b> <ul>` etc. through from 'Book Summary' when matching books rather than plain stripped text?

This would save much of the manual editing of paragraph breaks and bulleted lists etc.

Thanks for considering :)

**Comment by nichwall** [comment] 2023-09-20 18:18
Duplicate of https://github.com/advplyr/audiobookshelf/issues/1820

**Comment by advplyr** [comment] 2023-09-20 18:32
Duplicate of #1820

**Closed by advplyr** 2023-09-20 18:32 UTC
Labels: enhancement
