### ISSUE TITLE
[Bug]: Home/Library screen - Display authors in entered order instead of alphabetical

### ISSUE THREAD

**Issue by hjk321** [advplyr/audiobookshelf#2859] opened 2024-04-17 16:49 UTC
### Describe the feature/enhancement

Here's a screenshot from viewing an individual audiobook:
![image](https://github.com/advplyr/audiobookshelf/assets/37224753/c0ca2406-de73-4c16-9c1f-1793192680a8)

You'll notice that Orson Scott Card is listed as the first author, and Aaron Johnston is listed as the second author. It is listed in this order because that was the order they were entered in metadata. This is how it should be - after all, Card is the "primary" author of the work so he should be listed first.

However, on the home and library screens, the behavior is different:
![image](https://github.com/advplyr/audiobookshelf/assets/37224753/103cb42e-c382-4733-850d-8984a240e214)

Here the authors are listed alphabetically by first name, which is not only inconsistent with the book view but is often not the desired behavior. In this image, the current sorting makes it seem like Aaron Johnston is the primary author and Orson Scott Card is the secondary author.

**A good enhancement would be to make these two behaviors consistent.** Personally, I would favor the book view's behavior, but this is obviously open to discussion if someone has a better idea.

**Comment by advplyr** [comment] 2024-04-17 21:29
I'm not able to reproduce this. Can you share a screenshot of the authors in the edit modal?

Can you share what version of the server you are on?

**Comment by advplyr** [comment] 2024-04-18 21:23
Can you try reproducing this again by removing "Aaron Johnston" then press the "Save" button. After saving add "Aaron Johnson" again.

Let me know if you still see the authors listed with "Aaron Johnston" first.

I think this may have been a fluke with the cache or something because I'm not able to reproduce this in all my testing.

**Comment by jeff47** [comment] 2024-05-16 16:43
I seem to be seeing the same thing.  Here's the book:
<img width="795" alt="Screen Shot 2024-05-16 at 12 33 35 PM" src="https://github.com/advplyr/audiobookshelf/assets/7215369/06fc3297-30bc-4820-9788-571f5ad53a73">

I would expect this to be sorted as "Burns, James Macgregor" or "Appleman, Roy E", but some for reason it's going under "Stevens, John".
<img width="444" alt="Screen Shot 2024-05-16 at 12 31 44 PM" src="https://github.com/advplyr/audiobookshelf/assets/7215369/d6c25207-7c3a-4985-92fa-f5d67102f412">

The author names seem to be combined in reverse alphabetical order (Stevens -> Gugeler -> Burns -> Appleman).

**Comment by advplyr** [comment] 2024-05-16 17:03
I'm seeing this now along with some weird behavior around deleting authors

**Comment by advplyr** [comment] 2024-05-16 20:06
I found an issue with the sorting of the author names but wasn't able to replicate the author name order issue again on this third attempt.

The only way I can replicate this is by:
1. Press edit on a book with multiple authors
2. Re-order the authors and press save
3. Observe the book in the library updated in real-time to reflect the new order

However, if you refresh the page after that it will revert back because that new sort order isn't actually being saved. The way the order has to be adjusted is by removing an author and pressing save, then re-adding the author in the correct order.

**Comment by advplyr** [comment] 2024-05-27 21:34
Fixed in [v2.10.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.10.0)

**Closed by advplyr** 2024-05-27 21:34 UTC
Labels: bug, awaiting release
