### ISSUE TITLE
[Enhancement]: native mobile notifications

### ISSUE THREAD

**Issue by ThinkSalat** [advplyr/audiobookshelf#1694] opened 2023-04-18 13:24 UTC
### Describe the feature/enhancement

Notifications originating from the mobile app that deeplink to new podcast episodes or audio books. Currently the notifications must be set up through apprise and setting up is pretty difficult depending on user skill level. Since there's already a mobile app, it seems like a great way to add functionality to the app. Most notification systems either cost money, are limited/freemium, and aren't capable of deeplinking, which would be a big step up from receiving the notification and then searching the app for the episode

**Comment by advplyr** [comment] 2023-04-18 15:37
Duplicate of https://github.com/advplyr/audiobookshelf-app/issues/197

**Closed as not planned by advplyr** 2023-04-18 15:37 UTC
Labels: enhancement

**Comment by advplyr** [comment] 2023-04-18 15:38
I only know how to do this using firebase and a central server so probably not something that would come anytime soon
